


# drivers/image/gdma/Makefile

EXTRA_CFLAGS = -DSDEBUG_T

#ccflags-y += -I$(MTK_PATH_SOURCE)/drivers/gdma/

#obj-$(CONFIG_MTK_GDMA) += gdma_driver.o
obj-y += gdma_driver.o

#obj-y += gfmt/gdma_fmt_driver.o

gdma_driver-objs := gdma_drv_6589_ctl.o gdma_drv.o


#gdma_driver-objs := jpeg_drv_6589_dec.o jpeg_drv.o

obj-y += gfmt_driver.o

gfmt_driver-objs := gfmt_drv_6589_fmt.o gfmt_drv.o


# EOF
