#ifndef __CFG_CAMERA_FILE_MAX_SIZE_H__
#define __CFG_CAMERA_FILE_MAX_SIZE_H__

#define MAXIMUM_NVRAM_CAMERA_DEFECT_FILE_SIZE      (4096) //BYTE 81920
#define MAXIMUM_NVRAM_CAMERA_SHADING_FILE_SIZE      (1050652) //BYTE 81920--> 16000 for meta tool limitation

#define MAXIMUM_NVRAM_CAMERA_ISP_FILE_SIZE         (22528)
#define MAXIMUM_NVRAM_CAMERA_3A_FILE_SIZE          (4096)
#define MAXIMUM_NVRAM_CAMERA_SENSOR_FILE_SIZE      (4096)
#define MAXIMUM_NVRAM_CAMERA_LENS_FILE_SIZE		   (4096)

#endif
