# Makefile for the linux kernel.

obj-y += vdec_verify_main.o
obj-y += vdec_verify_common.o
#obj-y += vdec_verify_errinfo.o
#obj-y += vdec_verify_fgt.o
obj-y += vdec_verify_vdecode.o
obj-y += vdec_verify_filesetting.o
obj-y += vdec_verify_mm_map.o
obj-y += vdec_verify_irq_fiq_proc.o
obj-y += vdec_verify_mpv_data.o
obj-y += vdec_verify_file_common.o
obj-y += vdec_verify_imgresz_rm.o
obj-y += vdec_verify_vparser_avs.o
obj-y += vdec_verify_vparser_h264.o
obj-y += vdec_verify_vparser_mpeg4.o
obj-y += vdec_verify_vparser_mpeg.o
obj-y += vdec_verify_vparser_rm.o
obj-y += vdec_verify_vparser_vp6.o
obj-y += vdec_verify_vparser_vp8.o
obj-y += vdec_verify_vparser_wmv.o
# obj-y += RvdUtil.o          
# obj-y += sata_file_io.o     
obj-y += sata_fs_io.o       
# obj-y += usb_io.o
# obj-y += vdec_ide.o         
# obj-y += vdec_verify_dvdec.o