
#ifndef FTM_CUST_LED_H
#define FTM_CUST_LED_H

#define CUST_LED_HAVE_RED
//#define CUST_LED_HAVE_GREEN
//#define CUST_LED_HAVE_BLUE
//#define CUST_LED_HAVE_BUTTON_BACKLIGHT
//#define CUST_LED_HAVE_KEYPAD_BACKLIGHT
#endif /* FTM_CUST_LED_H */
