# Makefile for the linux kernel.

obj-y += vdec_hal_if_common.o
obj-y += vdec_hw_common.o
obj-y += vdec_hal_if_avs.o
obj-y += vdec_hal_if_h264.o
obj-y += vdec_hal_if_mpeg.o
obj-y += vdec_hal_if_rm.o
obj-y += vdec_hal_if_vp6.o
obj-y += vdec_hal_if_vp8.o
obj-y += vdec_hal_if_wmv.o
# obj-y += vdec_hal_slt_rm.o
obj-y += vdec_hw_avs.o
obj-y += vdec_hw_h264.o
obj-y += vdec_hw_mpeg.o
obj-y += vdec_hw_rm.o
obj-y += vdec_hw_vp6.o
obj-y += vdec_hw_vp8.o