

#ifndef __CUST_GPIO_BOOT_H__
#define __CUST_GPIO_BOOT_H__


//Configureation for Pin 0
#define GPIO0_MODE      GPIO_MODE_01
#define GPIO0_DIR       GPIO_DIR_IN
#define GPIO0_PULLEN    GPIO_PULL_ENABLE
#define GPIO0_PULL      GPIO_PULL_UP
#define GPIO0_DATAOUT   GPIO_OUT_ZERO
#define GPIO0_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 1
#define GPIO1_MODE      GPIO_MODE_01
#define GPIO1_DIR       GPIO_DIR_IN
#define GPIO1_PULLEN    GPIO_PULL_ENABLE
#define GPIO1_PULL      GPIO_PULL_UP
#define GPIO1_DATAOUT   GPIO_OUT_ZERO
#define GPIO1_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 2
#define GPIO2_MODE      GPIO_MODE_01
#define GPIO2_DIR       GPIO_DIR_IN
#define GPIO2_PULLEN    GPIO_PULL_ENABLE
#define GPIO2_PULL      GPIO_PULL_UP
#define GPIO2_DATAOUT   GPIO_OUT_ZERO
#define GPIO2_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 3
#define GPIO3_MODE      GPIO_MODE_01
#define GPIO3_DIR       GPIO_DIR_IN
#define GPIO3_PULLEN    GPIO_PULL_ENABLE
#define GPIO3_PULL      GPIO_PULL_UP
#define GPIO3_DATAOUT   GPIO_OUT_ZERO
#define GPIO3_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 4
#define GPIO4_MODE      GPIO_MODE_01
#define GPIO4_DIR       GPIO_DIR_OUT
#define GPIO4_PULLEN    GPIO_PULL_DISABLE
#define GPIO4_PULL      GPIO_PULL_DOWN
#define GPIO4_DATAOUT   GPIO_OUT_ONE
#define GPIO4_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 5
#define GPIO5_MODE      GPIO_MODE_01
#define GPIO5_DIR       GPIO_DIR_IN
#define GPIO5_PULLEN    GPIO_PULL_ENABLE
#define GPIO5_PULL      GPIO_PULL_UP
#define GPIO5_DATAOUT   GPIO_OUT_ZERO
#define GPIO5_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 6
#define GPIO6_MODE      GPIO_MODE_01
#define GPIO6_DIR       GPIO_DIR_OUT
#define GPIO6_PULLEN    GPIO_PULL_ENABLE
#define GPIO6_PULL      GPIO_PULL_DOWN
#define GPIO6_DATAOUT   GPIO_OUT_ZERO
#define GPIO6_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 7
#define GPIO7_MODE      GPIO_MODE_01
#define GPIO7_DIR       GPIO_DIR_IN
#define GPIO7_PULLEN    GPIO_PULL_ENABLE
#define GPIO7_PULL      GPIO_PULL_UP
#define GPIO7_DATAOUT   GPIO_OUT_ZERO
#define GPIO7_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 8
#define GPIO8_MODE      GPIO_MODE_01
#define GPIO8_DIR       GPIO_DIR_IN
#define GPIO8_PULLEN    GPIO_PULL_ENABLE
#define GPIO8_PULL      GPIO_PULL_UP
#define GPIO8_DATAOUT   GPIO_OUT_ZERO
#define GPIO8_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 9
#define GPIO9_MODE      GPIO_MODE_01
#define GPIO9_DIR       GPIO_DIR_IN
#define GPIO9_PULLEN    GPIO_PULL_ENABLE
#define GPIO9_PULL      GPIO_PULL_UP
#define GPIO9_DATAOUT   GPIO_OUT_ZERO
#define GPIO9_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 10
#define GPIO10_MODE      GPIO_MODE_01
#define GPIO10_DIR       GPIO_DIR_IN
#define GPIO10_PULLEN    GPIO_PULL_ENABLE
#define GPIO10_PULL      GPIO_PULL_UP
#define GPIO10_DATAOUT   GPIO_OUT_ZERO
#define GPIO10_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 11
#define GPIO11_MODE      GPIO_MODE_00
#define GPIO11_DIR       GPIO_DIR_IN
#define GPIO11_PULLEN    GPIO_PULL_ENABLE
#define GPIO11_PULL      GPIO_PULL_DOWN
#define GPIO11_DATAOUT   GPIO_OUT_ZERO
#define GPIO11_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 12
#define GPIO12_MODE      GPIO_MODE_06
#define GPIO12_DIR       GPIO_DIR_IN
#define GPIO12_PULLEN    GPIO_PULL_DISABLE
#define GPIO12_PULL      GPIO_PULL_DOWN
#define GPIO12_DATAOUT   GPIO_OUT_ZERO
#define GPIO12_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 13
#define GPIO13_MODE      GPIO_MODE_00
#define GPIO13_DIR       GPIO_DIR_OUT
#define GPIO13_PULLEN    GPIO_PULL_DISABLE
#define GPIO13_PULL      GPIO_PULL_DOWN
#define GPIO13_DATAOUT   GPIO_OUT_ZERO
#define GPIO13_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 14
#define GPIO14_MODE      GPIO_MODE_00
#define GPIO14_DIR       GPIO_DIR_IN
#define GPIO14_PULLEN    GPIO_PULL_ENABLE
#define GPIO14_PULL      GPIO_PULL_DOWN
#define GPIO14_DATAOUT   GPIO_OUT_ZERO
#define GPIO14_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 15
#define GPIO15_MODE      GPIO_MODE_00
#define GPIO15_DIR       GPIO_DIR_IN
#define GPIO15_PULLEN    GPIO_PULL_ENABLE
#define GPIO15_PULL      GPIO_PULL_DOWN
#define GPIO15_DATAOUT   GPIO_OUT_ZERO
#define GPIO15_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 16
#define GPIO16_MODE      GPIO_MODE_00
#define GPIO16_DIR       GPIO_DIR_IN
#define GPIO16_PULLEN    GPIO_PULL_ENABLE
#define GPIO16_PULL      GPIO_PULL_DOWN
#define GPIO16_DATAOUT   GPIO_OUT_ZERO
#define GPIO16_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 17
#define GPIO17_MODE      GPIO_MODE_00
#define GPIO17_DIR       GPIO_DIR_IN
#define GPIO17_PULLEN    GPIO_PULL_ENABLE
#define GPIO17_PULL      GPIO_PULL_DOWN
#define GPIO17_DATAOUT   GPIO_OUT_ZERO
#define GPIO17_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 18
#define GPIO18_MODE      GPIO_MODE_00
#define GPIO18_DIR       GPIO_DIR_OUT
#define GPIO18_PULLEN    GPIO_PULL_DISABLE
#define GPIO18_PULL      GPIO_PULL_DOWN
#define GPIO18_DATAOUT   GPIO_OUT_ZERO
#define GPIO18_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 19
#define GPIO19_MODE      GPIO_MODE_00
#define GPIO19_DIR       GPIO_DIR_IN
#define GPIO19_PULLEN    GPIO_PULL_ENABLE
#define GPIO19_PULL      GPIO_PULL_DOWN
#define GPIO19_DATAOUT   GPIO_OUT_ZERO
#define GPIO19_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 20
#define GPIO20_MODE      GPIO_MODE_00
#define GPIO20_DIR       GPIO_DIR_IN
#define GPIO20_PULLEN    GPIO_PULL_ENABLE
#define GPIO20_PULL      GPIO_PULL_DOWN
#define GPIO20_DATAOUT   GPIO_OUT_ZERO
#define GPIO20_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 21
#define GPIO21_MODE      GPIO_MODE_00
#define GPIO21_DIR       GPIO_DIR_IN
#define GPIO21_PULLEN    GPIO_PULL_ENABLE
#define GPIO21_PULL      GPIO_PULL_DOWN
#define GPIO21_DATAOUT   GPIO_OUT_ZERO
#define GPIO21_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 22
#define GPIO22_MODE      GPIO_MODE_00
#define GPIO22_DIR       GPIO_DIR_IN
#define GPIO22_PULLEN    GPIO_PULL_ENABLE
#define GPIO22_PULL      GPIO_PULL_DOWN
#define GPIO22_DATAOUT   GPIO_OUT_ZERO
#define GPIO22_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 23
#define GPIO23_MODE      GPIO_MODE_00
#define GPIO23_DIR       GPIO_DIR_OUT
#define GPIO23_PULLEN    GPIO_PULL_DISABLE
#define GPIO23_PULL      GPIO_PULL_DOWN
#define GPIO23_DATAOUT   GPIO_OUT_ONE
#define GPIO23_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 24
#define GPIO24_MODE      GPIO_MODE_00
#define GPIO24_DIR       GPIO_DIR_OUT
#define GPIO24_PULLEN    GPIO_PULL_DISABLE
#define GPIO24_PULL      GPIO_PULL_DOWN
#define GPIO24_DATAOUT   GPIO_OUT_ONE
#define GPIO24_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 25
#define GPIO25_MODE      GPIO_MODE_00
#define GPIO25_DIR       GPIO_DIR_OUT
#define GPIO25_PULLEN    GPIO_PULL_DISABLE
#define GPIO25_PULL      GPIO_PULL_DOWN
#define GPIO25_DATAOUT   GPIO_OUT_ZERO
#define GPIO25_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 26
#define GPIO26_MODE      GPIO_MODE_02
#define GPIO26_DIR       GPIO_DIR_IN
#define GPIO26_PULLEN    GPIO_PULL_ENABLE
#define GPIO26_PULL      GPIO_PULL_DOWN
#define GPIO26_DATAOUT   GPIO_OUT_ZERO
#define GPIO26_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 27
#define GPIO27_MODE      GPIO_MODE_00
#define GPIO27_DIR       GPIO_DIR_OUT
#define GPIO27_PULLEN    GPIO_PULL_DISABLE
#define GPIO27_PULL      GPIO_PULL_DOWN
#define GPIO27_DATAOUT   GPIO_OUT_ZERO
#define GPIO27_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 28
#define GPIO28_MODE      GPIO_MODE_02
#define GPIO28_DIR       GPIO_DIR_IN
#define GPIO28_PULLEN    GPIO_PULL_DISABLE
#define GPIO28_PULL      GPIO_PULL_DOWN
#define GPIO28_DATAOUT   GPIO_OUT_ZERO
#define GPIO28_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 29
#define GPIO29_MODE      GPIO_MODE_00
#define GPIO29_DIR       GPIO_DIR_IN
#define GPIO29_PULLEN    GPIO_PULL_ENABLE
#define GPIO29_PULL      GPIO_PULL_DOWN
#define GPIO29_DATAOUT   GPIO_OUT_ZERO
#define GPIO29_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 30
#define GPIO30_MODE      GPIO_MODE_00
#define GPIO30_DIR       GPIO_DIR_OUT
#define GPIO30_PULLEN    GPIO_PULL_DISABLE
#define GPIO30_PULL      GPIO_PULL_DOWN
#define GPIO30_DATAOUT   GPIO_OUT_ONE
#define GPIO30_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 31
#define GPIO31_MODE      GPIO_MODE_00
#define GPIO31_DIR       GPIO_DIR_OUT
#define GPIO31_PULLEN    GPIO_PULL_DISABLE
#define GPIO31_PULL      GPIO_PULL_DOWN
#define GPIO31_DATAOUT   GPIO_OUT_ZERO
#define GPIO31_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 32
#define GPIO32_MODE      GPIO_MODE_00
#define GPIO32_DIR       GPIO_DIR_IN
#define GPIO32_PULLEN    GPIO_PULL_ENABLE
#define GPIO32_PULL      GPIO_PULL_DOWN
#define GPIO32_DATAOUT   GPIO_OUT_ZERO
#define GPIO32_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 33
#define GPIO33_MODE      GPIO_MODE_00
#define GPIO33_DIR       GPIO_DIR_IN
#define GPIO33_PULLEN    GPIO_PULL_ENABLE
#define GPIO33_PULL      GPIO_PULL_DOWN
#define GPIO33_DATAOUT   GPIO_OUT_ZERO
#define GPIO33_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 34
#define GPIO34_MODE      GPIO_MODE_00
#define GPIO34_DIR       GPIO_DIR_IN
#define GPIO34_PULLEN    GPIO_PULL_ENABLE
#define GPIO34_PULL      GPIO_PULL_DOWN
#define GPIO34_DATAOUT   GPIO_OUT_ZERO
#define GPIO34_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 35
#define GPIO35_MODE      GPIO_MODE_06
#define GPIO35_DIR       GPIO_DIR_IN
#define GPIO35_PULLEN    GPIO_PULL_ENABLE
#define GPIO35_PULL      GPIO_PULL_UP
#define GPIO35_DATAOUT   GPIO_OUT_ZERO
#define GPIO35_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 36
#define GPIO36_MODE      GPIO_MODE_06
#define GPIO36_DIR       GPIO_DIR_IN
#define GPIO36_PULLEN    GPIO_PULL_ENABLE
#define GPIO36_PULL      GPIO_PULL_UP
#define GPIO36_DATAOUT   GPIO_OUT_ZERO
#define GPIO36_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 37
#define GPIO37_MODE      GPIO_MODE_01
#define GPIO37_DIR       GPIO_DIR_IN
#define GPIO37_PULLEN    GPIO_PULL_ENABLE
#define GPIO37_PULL      GPIO_PULL_DOWN
#define GPIO37_DATAOUT   GPIO_OUT_ZERO
#define GPIO37_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 38
#define GPIO38_MODE      GPIO_MODE_00
#define GPIO38_DIR       GPIO_DIR_IN
#define GPIO38_PULLEN    GPIO_PULL_ENABLE
#define GPIO38_PULL      GPIO_PULL_DOWN
#define GPIO38_DATAOUT   GPIO_OUT_ZERO
#define GPIO38_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 39
#define GPIO39_MODE      GPIO_MODE_01
#define GPIO39_DIR       GPIO_DIR_IN
#define GPIO39_PULLEN    GPIO_PULL_ENABLE
#define GPIO39_PULL      GPIO_PULL_DOWN
#define GPIO39_DATAOUT   GPIO_OUT_ZERO
#define GPIO39_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 40
#define GPIO40_MODE      GPIO_MODE_01
#define GPIO40_DIR       GPIO_DIR_IN
#define GPIO40_PULLEN    GPIO_PULL_ENABLE
#define GPIO40_PULL      GPIO_PULL_DOWN
#define GPIO40_DATAOUT   GPIO_OUT_ZERO
#define GPIO40_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 41
#define GPIO41_MODE      GPIO_MODE_01
#define GPIO41_DIR       GPIO_DIR_IN
#define GPIO41_PULLEN    GPIO_PULL_DISABLE
#define GPIO41_PULL      GPIO_PULL_DOWN
#define GPIO41_DATAOUT   GPIO_OUT_ONE
#define GPIO41_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 42
#define GPIO42_MODE      GPIO_MODE_01
#define GPIO42_DIR       GPIO_DIR_IN
#define GPIO42_PULLEN    GPIO_PULL_DISABLE
#define GPIO42_PULL      GPIO_PULL_DOWN
#define GPIO42_DATAOUT   GPIO_OUT_ZERO
#define GPIO42_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 43
#define GPIO43_MODE      GPIO_MODE_01
#define GPIO43_DIR       GPIO_DIR_IN
#define GPIO43_PULLEN    GPIO_PULL_ENABLE
#define GPIO43_PULL      GPIO_PULL_DOWN
#define GPIO43_DATAOUT   GPIO_OUT_ZERO
#define GPIO43_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 44
#define GPIO44_MODE      GPIO_MODE_01
#define GPIO44_DIR       GPIO_DIR_IN
#define GPIO44_PULLEN    GPIO_PULL_DISABLE
#define GPIO44_PULL      GPIO_PULL_DOWN
#define GPIO44_DATAOUT   GPIO_OUT_ZERO
#define GPIO44_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 45
#define GPIO45_MODE      GPIO_MODE_01
#define GPIO45_DIR       GPIO_DIR_IN
#define GPIO45_PULLEN    GPIO_PULL_DISABLE
#define GPIO45_PULL      GPIO_PULL_DOWN
#define GPIO45_DATAOUT   GPIO_OUT_ZERO
#define GPIO45_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 46
#define GPIO46_MODE      GPIO_MODE_01
#define GPIO46_DIR       GPIO_DIR_IN
#define GPIO46_PULLEN    GPIO_PULL_ENABLE
#define GPIO46_PULL      GPIO_PULL_UP
#define GPIO46_DATAOUT   GPIO_OUT_ZERO
#define GPIO46_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 47
#define GPIO47_MODE      GPIO_MODE_01
#define GPIO47_DIR       GPIO_DIR_IN
#define GPIO47_PULLEN    GPIO_PULL_DISABLE
#define GPIO47_PULL      GPIO_PULL_DOWN
#define GPIO47_DATAOUT   GPIO_OUT_ZERO
#define GPIO47_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 48
#define GPIO48_MODE      GPIO_MODE_01
#define GPIO48_DIR       GPIO_DIR_IN
#define GPIO48_PULLEN    GPIO_PULL_DISABLE
#define GPIO48_PULL      GPIO_PULL_DOWN
#define GPIO48_DATAOUT   GPIO_OUT_ZERO
#define GPIO48_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 49
#define GPIO49_MODE      GPIO_MODE_01
#define GPIO49_DIR       GPIO_DIR_IN
#define GPIO49_PULLEN    GPIO_PULL_ENABLE
#define GPIO49_PULL      GPIO_PULL_UP
#define GPIO49_DATAOUT   GPIO_OUT_ZERO
#define GPIO49_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 50
#define GPIO50_MODE      GPIO_MODE_01
#define GPIO50_DIR       GPIO_DIR_IN
#define GPIO50_PULLEN    GPIO_PULL_DISABLE
#define GPIO50_PULL      GPIO_PULL_DOWN
#define GPIO50_DATAOUT   GPIO_OUT_ZERO
#define GPIO50_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 51
#define GPIO51_MODE      GPIO_MODE_01
#define GPIO51_DIR       GPIO_DIR_IN
#define GPIO51_PULLEN    GPIO_PULL_DISABLE
#define GPIO51_PULL      GPIO_PULL_DOWN
#define GPIO51_DATAOUT   GPIO_OUT_ZERO
#define GPIO51_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 52
#define GPIO52_MODE      GPIO_MODE_01
#define GPIO52_DIR       GPIO_DIR_IN
#define GPIO52_PULLEN    GPIO_PULL_ENABLE
#define GPIO52_PULL      GPIO_PULL_DOWN
#define GPIO52_DATAOUT   GPIO_OUT_ZERO
#define GPIO52_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 53
#define GPIO53_MODE      GPIO_MODE_01
#define GPIO53_DIR       GPIO_DIR_IN
#define GPIO53_PULLEN    GPIO_PULL_DISABLE
#define GPIO53_PULL      GPIO_PULL_DOWN
#define GPIO53_DATAOUT   GPIO_OUT_ZERO
#define GPIO53_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 54
#define GPIO54_MODE      GPIO_MODE_01
#define GPIO54_DIR       GPIO_DIR_IN
#define GPIO54_PULLEN    GPIO_PULL_DISABLE
#define GPIO54_PULL      GPIO_PULL_DOWN
#define GPIO54_DATAOUT   GPIO_OUT_ZERO
#define GPIO54_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 55
#define GPIO55_MODE      GPIO_MODE_01
#define GPIO55_DIR       GPIO_DIR_IN
#define GPIO55_PULLEN    GPIO_PULL_DISABLE
#define GPIO55_PULL      GPIO_PULL_DOWN
#define GPIO55_DATAOUT   GPIO_OUT_ZERO
#define GPIO55_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 56
#define GPIO56_MODE      GPIO_MODE_01
#define GPIO56_DIR       GPIO_DIR_IN
#define GPIO56_PULLEN    GPIO_PULL_ENABLE
#define GPIO56_PULL      GPIO_PULL_DOWN
#define GPIO56_DATAOUT   GPIO_OUT_ZERO
#define GPIO56_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 57
#define GPIO57_MODE      GPIO_MODE_01
#define GPIO57_DIR       GPIO_DIR_IN
#define GPIO57_PULLEN    GPIO_PULL_ENABLE
#define GPIO57_PULL      GPIO_PULL_UP
#define GPIO57_DATAOUT   GPIO_OUT_ZERO
#define GPIO57_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 58
#define GPIO58_MODE      GPIO_MODE_01
#define GPIO58_DIR       GPIO_DIR_IN
#define GPIO58_PULLEN    GPIO_PULL_DISABLE
#define GPIO58_PULL      GPIO_PULL_DOWN
#define GPIO58_DATAOUT   GPIO_OUT_ZERO
#define GPIO58_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 59
#define GPIO59_MODE      GPIO_MODE_01
#define GPIO59_DIR       GPIO_DIR_IN
#define GPIO59_PULLEN    GPIO_PULL_DISABLE
#define GPIO59_PULL      GPIO_PULL_DOWN
#define GPIO59_DATAOUT   GPIO_OUT_ZERO
#define GPIO59_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 60
#define GPIO60_MODE      GPIO_MODE_01
#define GPIO60_DIR       GPIO_DIR_IN
#define GPIO60_PULLEN    GPIO_PULL_DISABLE
#define GPIO60_PULL      GPIO_PULL_DOWN
#define GPIO60_DATAOUT   GPIO_OUT_ZERO
#define GPIO60_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 61
#define GPIO61_MODE      GPIO_MODE_01
#define GPIO61_DIR       GPIO_DIR_IN
#define GPIO61_PULLEN    GPIO_PULL_ENABLE
#define GPIO61_PULL      GPIO_PULL_DOWN
#define GPIO61_DATAOUT   GPIO_OUT_ZERO
#define GPIO61_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 62
#define GPIO62_MODE      GPIO_MODE_01
#define GPIO62_DIR       GPIO_DIR_IN
#define GPIO62_PULLEN    GPIO_PULL_DISABLE
#define GPIO62_PULL      GPIO_PULL_DOWN
#define GPIO62_DATAOUT   GPIO_OUT_ZERO
#define GPIO62_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 63
#define GPIO63_MODE      GPIO_MODE_01
#define GPIO63_DIR       GPIO_DIR_IN
#define GPIO63_PULLEN    GPIO_PULL_ENABLE
#define GPIO63_PULL      GPIO_PULL_DOWN
#define GPIO63_DATAOUT   GPIO_OUT_ZERO
#define GPIO63_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 64
#define GPIO64_MODE      GPIO_MODE_01
#define GPIO64_DIR       GPIO_DIR_IN
#define GPIO64_PULLEN    GPIO_PULL_ENABLE
#define GPIO64_PULL      GPIO_PULL_UP
#define GPIO64_DATAOUT   GPIO_OUT_ZERO
#define GPIO64_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 65
#define GPIO65_MODE      GPIO_MODE_01
#define GPIO65_DIR       GPIO_DIR_IN
#define GPIO65_PULLEN    GPIO_PULL_DISABLE
#define GPIO65_PULL      GPIO_PULL_DOWN
#define GPIO65_DATAOUT   GPIO_OUT_ZERO
#define GPIO65_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 66
#define GPIO66_MODE      GPIO_MODE_01
#define GPIO66_DIR       GPIO_DIR_IN
#define GPIO66_PULLEN    GPIO_PULL_ENABLE
#define GPIO66_PULL      GPIO_PULL_UP
#define GPIO66_DATAOUT   GPIO_OUT_ZERO
#define GPIO66_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 67
#define GPIO67_MODE      GPIO_MODE_01
#define GPIO67_DIR       GPIO_DIR_IN
#define GPIO67_PULLEN    GPIO_PULL_ENABLE
#define GPIO67_PULL      GPIO_PULL_UP
#define GPIO67_DATAOUT   GPIO_OUT_ZERO
#define GPIO67_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 68
#define GPIO68_MODE      GPIO_MODE_01
#define GPIO68_DIR       GPIO_DIR_IN
#define GPIO68_PULLEN    GPIO_PULL_ENABLE
#define GPIO68_PULL      GPIO_PULL_UP
#define GPIO68_DATAOUT   GPIO_OUT_ZERO
#define GPIO68_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 69
#define GPIO69_MODE      GPIO_MODE_00
#define GPIO69_DIR       GPIO_DIR_IN
#define GPIO69_PULLEN    GPIO_PULL_ENABLE
#define GPIO69_PULL      GPIO_PULL_DOWN
#define GPIO69_DATAOUT   GPIO_OUT_ZERO
#define GPIO69_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 70
#define GPIO70_MODE      GPIO_MODE_00
#define GPIO70_DIR       GPIO_DIR_IN
#define GPIO70_PULLEN    GPIO_PULL_ENABLE
#define GPIO70_PULL      GPIO_PULL_DOWN
#define GPIO70_DATAOUT   GPIO_OUT_ZERO
#define GPIO70_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 71
#define GPIO71_MODE      GPIO_MODE_00
#define GPIO71_DIR       GPIO_DIR_IN
#define GPIO71_PULLEN    GPIO_PULL_ENABLE
#define GPIO71_PULL      GPIO_PULL_DOWN
#define GPIO71_DATAOUT   GPIO_OUT_ZERO
#define GPIO71_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 72
#define GPIO72_MODE      GPIO_MODE_00
#define GPIO72_DIR       GPIO_DIR_IN
#define GPIO72_PULLEN    GPIO_PULL_ENABLE
#define GPIO72_PULL      GPIO_PULL_DOWN
#define GPIO72_DATAOUT   GPIO_OUT_ZERO
#define GPIO72_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 73
#define GPIO73_MODE      GPIO_MODE_00
#define GPIO73_DIR       GPIO_DIR_IN
#define GPIO73_PULLEN    GPIO_PULL_ENABLE
#define GPIO73_PULL      GPIO_PULL_DOWN
#define GPIO73_DATAOUT   GPIO_OUT_ZERO
#define GPIO73_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 74
#define GPIO74_MODE      GPIO_MODE_00
#define GPIO74_DIR       GPIO_DIR_IN
#define GPIO74_PULLEN    GPIO_PULL_ENABLE
#define GPIO74_PULL      GPIO_PULL_DOWN
#define GPIO74_DATAOUT   GPIO_OUT_ZERO
#define GPIO74_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 75
#define GPIO75_MODE      GPIO_MODE_00
#define GPIO75_DIR       GPIO_DIR_IN
#define GPIO75_PULLEN    GPIO_PULL_ENABLE
#define GPIO75_PULL      GPIO_PULL_DOWN
#define GPIO75_DATAOUT   GPIO_OUT_ZERO
#define GPIO75_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 76
#define GPIO76_MODE      GPIO_MODE_00
#define GPIO76_DIR       GPIO_DIR_IN
#define GPIO76_PULLEN    GPIO_PULL_ENABLE
#define GPIO76_PULL      GPIO_PULL_DOWN
#define GPIO76_DATAOUT   GPIO_OUT_ZERO
#define GPIO76_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 77
#define GPIO77_MODE      GPIO_MODE_01
#define GPIO77_DIR       GPIO_DIR_IN
#define GPIO77_PULLEN    GPIO_PULL_ENABLE
#define GPIO77_PULL      GPIO_PULL_UP
#define GPIO77_DATAOUT   GPIO_OUT_ZERO
#define GPIO77_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 78
#define GPIO78_MODE      GPIO_MODE_01
#define GPIO78_DIR       GPIO_DIR_OUT
#define GPIO78_PULLEN    GPIO_PULL_DISABLE
#define GPIO78_PULL      GPIO_PULL_DOWN
#define GPIO78_DATAOUT   GPIO_OUT_ONE
#define GPIO78_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 79
#define GPIO79_MODE      GPIO_MODE_04
#define GPIO79_DIR       GPIO_DIR_IN
#define GPIO79_PULLEN    GPIO_PULL_DISABLE
#define GPIO79_PULL      GPIO_PULL_DOWN
#define GPIO79_DATAOUT   GPIO_OUT_ZERO
#define GPIO79_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 80
#define GPIO80_MODE      GPIO_MODE_04
#define GPIO80_DIR       GPIO_DIR_IN
#define GPIO80_PULLEN    GPIO_PULL_DISABLE
#define GPIO80_PULL      GPIO_PULL_DOWN
#define GPIO80_DATAOUT   GPIO_OUT_ZERO
#define GPIO80_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 81
#define GPIO81_MODE      GPIO_MODE_01
#define GPIO81_DIR       GPIO_DIR_IN
#define GPIO81_PULLEN    GPIO_PULL_ENABLE
#define GPIO81_PULL      GPIO_PULL_UP
#define GPIO81_DATAOUT   GPIO_OUT_ZERO
#define GPIO81_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 82
#define GPIO82_MODE      GPIO_MODE_01
#define GPIO82_DIR       GPIO_DIR_OUT
#define GPIO82_PULLEN    GPIO_PULL_DISABLE
#define GPIO82_PULL      GPIO_PULL_DOWN
#define GPIO82_DATAOUT   GPIO_OUT_ONE
#define GPIO82_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 83
#define GPIO83_MODE      GPIO_MODE_01
#define GPIO83_DIR       GPIO_DIR_OUT
#define GPIO83_PULLEN    GPIO_PULL_DISABLE
#define GPIO83_PULL      GPIO_PULL_DOWN
#define GPIO83_DATAOUT   GPIO_OUT_ZERO
#define GPIO83_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 84
#define GPIO84_MODE      GPIO_MODE_01
#define GPIO84_DIR       GPIO_DIR_OUT
#define GPIO84_PULLEN    GPIO_PULL_DISABLE
#define GPIO84_PULL      GPIO_PULL_DOWN
#define GPIO84_DATAOUT   GPIO_OUT_ZERO
#define GPIO84_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 85
#define GPIO85_MODE      GPIO_MODE_01
#define GPIO85_DIR       GPIO_DIR_OUT
#define GPIO85_PULLEN    GPIO_PULL_DISABLE
#define GPIO85_PULL      GPIO_PULL_DOWN
#define GPIO85_DATAOUT   GPIO_OUT_ZERO
#define GPIO85_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 86
#define GPIO86_MODE      GPIO_MODE_00
#define GPIO86_DIR       GPIO_DIR_IN
#define GPIO86_PULLEN    GPIO_PULL_ENABLE
#define GPIO86_PULL      GPIO_PULL_DOWN
#define GPIO86_DATAOUT   GPIO_OUT_ZERO
#define GPIO86_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 87
#define GPIO87_MODE      GPIO_MODE_01
#define GPIO87_DIR       GPIO_DIR_OUT
#define GPIO87_PULLEN    GPIO_PULL_DISABLE
#define GPIO87_PULL      GPIO_PULL_DOWN
#define GPIO87_DATAOUT   GPIO_OUT_ZERO
#define GPIO87_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 88
#define GPIO88_MODE      GPIO_MODE_00
#define GPIO88_DIR       GPIO_DIR_IN
#define GPIO88_PULLEN    GPIO_PULL_ENABLE
#define GPIO88_PULL      GPIO_PULL_DOWN
#define GPIO88_DATAOUT   GPIO_OUT_ZERO
#define GPIO88_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 89
#define GPIO89_MODE      GPIO_MODE_00
#define GPIO89_DIR       GPIO_DIR_IN
#define GPIO89_PULLEN    GPIO_PULL_ENABLE
#define GPIO89_PULL      GPIO_PULL_DOWN
#define GPIO89_DATAOUT   GPIO_OUT_ZERO
#define GPIO89_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 90
#define GPIO90_MODE      GPIO_MODE_01
#define GPIO90_DIR       GPIO_DIR_OUT
#define GPIO90_PULLEN    GPIO_PULL_DISABLE
#define GPIO90_PULL      GPIO_PULL_DOWN
#define GPIO90_DATAOUT   GPIO_OUT_ZERO
#define GPIO90_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 91
#define GPIO91_MODE      GPIO_MODE_00
#define GPIO91_DIR       GPIO_DIR_IN
#define GPIO91_PULLEN    GPIO_PULL_ENABLE
#define GPIO91_PULL      GPIO_PULL_DOWN
#define GPIO91_DATAOUT   GPIO_OUT_ZERO
#define GPIO91_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 92
#define GPIO92_MODE      GPIO_MODE_00
#define GPIO92_DIR       GPIO_DIR_IN
#define GPIO92_PULLEN    GPIO_PULL_ENABLE
#define GPIO92_PULL      GPIO_PULL_DOWN
#define GPIO92_DATAOUT   GPIO_OUT_ZERO
#define GPIO92_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 93
#define GPIO93_MODE      GPIO_MODE_01
#define GPIO93_DIR       GPIO_DIR_OUT
#define GPIO93_PULLEN    GPIO_PULL_DISABLE
#define GPIO93_PULL      GPIO_PULL_DOWN
#define GPIO93_DATAOUT   GPIO_OUT_ZERO
#define GPIO93_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 94
#define GPIO94_MODE      GPIO_MODE_00
#define GPIO94_DIR       GPIO_DIR_IN
#define GPIO94_PULLEN    GPIO_PULL_ENABLE
#define GPIO94_PULL      GPIO_PULL_DOWN
#define GPIO94_DATAOUT   GPIO_OUT_ZERO
#define GPIO94_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 95
#define GPIO95_MODE      GPIO_MODE_00
#define GPIO95_DIR       GPIO_DIR_IN
#define GPIO95_PULLEN    GPIO_PULL_ENABLE
#define GPIO95_PULL      GPIO_PULL_DOWN
#define GPIO95_DATAOUT   GPIO_OUT_ZERO
#define GPIO95_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 96
#define GPIO96_MODE      GPIO_MODE_00
#define GPIO96_DIR       GPIO_DIR_IN
#define GPIO96_PULLEN    GPIO_PULL_ENABLE
#define GPIO96_PULL      GPIO_PULL_DOWN
#define GPIO96_DATAOUT   GPIO_OUT_ZERO
#define GPIO96_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 97
#define GPIO97_MODE      GPIO_MODE_00
#define GPIO97_DIR       GPIO_DIR_IN
#define GPIO97_PULLEN    GPIO_PULL_ENABLE
#define GPIO97_PULL      GPIO_PULL_DOWN
#define GPIO97_DATAOUT   GPIO_OUT_ZERO
#define GPIO97_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 98
#define GPIO98_MODE      GPIO_MODE_00
#define GPIO98_DIR       GPIO_DIR_IN
#define GPIO98_PULLEN    GPIO_PULL_ENABLE
#define GPIO98_PULL      GPIO_PULL_DOWN
#define GPIO98_DATAOUT   GPIO_OUT_ZERO
#define GPIO98_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 99
#define GPIO99_MODE      GPIO_MODE_00
#define GPIO99_DIR       GPIO_DIR_IN
#define GPIO99_PULLEN    GPIO_PULL_ENABLE
#define GPIO99_PULL      GPIO_PULL_DOWN
#define GPIO99_DATAOUT   GPIO_OUT_ZERO
#define GPIO99_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 100
#define GPIO100_MODE      GPIO_MODE_01
#define GPIO100_DIR       GPIO_DIR_OUT
#define GPIO100_PULLEN    GPIO_PULL_DISABLE
#define GPIO100_PULL      GPIO_PULL_DOWN
#define GPIO100_DATAOUT   GPIO_OUT_ZERO
#define GPIO100_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 101
#define GPIO101_MODE      GPIO_MODE_01
#define GPIO101_DIR       GPIO_DIR_OUT
#define GPIO101_PULLEN    GPIO_PULL_DISABLE
#define GPIO101_PULL      GPIO_PULL_DOWN
#define GPIO101_DATAOUT   GPIO_OUT_ZERO
#define GPIO101_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 102
#define GPIO102_MODE      GPIO_MODE_00
#define GPIO102_DIR       GPIO_DIR_IN
#define GPIO102_PULLEN    GPIO_PULL_ENABLE
#define GPIO102_PULL      GPIO_PULL_DOWN
#define GPIO102_DATAOUT   GPIO_OUT_ZERO
#define GPIO102_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 103
#define GPIO103_MODE      GPIO_MODE_00
#define GPIO103_DIR       GPIO_DIR_OUT
#define GPIO103_PULLEN    GPIO_PULL_DISABLE
#define GPIO103_PULL      GPIO_PULL_DOWN
#define GPIO103_DATAOUT   GPIO_OUT_ZERO
#define GPIO103_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 104
#define GPIO104_MODE      GPIO_MODE_00
#define GPIO104_DIR       GPIO_DIR_IN
#define GPIO104_PULLEN    GPIO_PULL_ENABLE
#define GPIO104_PULL      GPIO_PULL_DOWN
#define GPIO104_DATAOUT   GPIO_OUT_ZERO
#define GPIO104_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 105
#define GPIO105_MODE      GPIO_MODE_01
#define GPIO105_DIR       GPIO_DIR_IN
#define GPIO105_PULLEN    GPIO_PULL_ENABLE
#define GPIO105_PULL      GPIO_PULL_DOWN
#define GPIO105_DATAOUT   GPIO_OUT_ZERO
#define GPIO105_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 106
#define GPIO106_MODE      GPIO_MODE_00
#define GPIO106_DIR       GPIO_DIR_IN
#define GPIO106_PULLEN    GPIO_PULL_ENABLE
#define GPIO106_PULL      GPIO_PULL_DOWN
#define GPIO106_DATAOUT   GPIO_OUT_ZERO
#define GPIO106_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 107
#define GPIO107_MODE      GPIO_MODE_01
#define GPIO107_DIR       GPIO_DIR_OUT
#define GPIO107_PULLEN    GPIO_PULL_DISABLE
#define GPIO107_PULL      GPIO_PULL_DOWN
#define GPIO107_DATAOUT   GPIO_OUT_ONE
#define GPIO107_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 108
#define GPIO108_MODE      GPIO_MODE_01
#define GPIO108_DIR       GPIO_DIR_OUT
#define GPIO108_PULLEN    GPIO_PULL_DISABLE
#define GPIO108_PULL      GPIO_PULL_DOWN
#define GPIO108_DATAOUT   GPIO_OUT_ZERO
#define GPIO108_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 109
#define GPIO109_MODE      GPIO_MODE_01
#define GPIO109_DIR       GPIO_DIR_IN
#define GPIO109_PULLEN    GPIO_PULL_ENABLE
#define GPIO109_PULL      GPIO_PULL_DOWN
#define GPIO109_DATAOUT   GPIO_OUT_ZERO
#define GPIO109_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 110
#define GPIO110_MODE      GPIO_MODE_01
#define GPIO110_DIR       GPIO_DIR_IN
#define GPIO110_PULLEN    GPIO_PULL_ENABLE
#define GPIO110_PULL      GPIO_PULL_DOWN
#define GPIO110_DATAOUT   GPIO_OUT_ZERO
#define GPIO110_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 111
#define GPIO111_MODE      GPIO_MODE_01
#define GPIO111_DIR       GPIO_DIR_IN
#define GPIO111_PULLEN    GPIO_PULL_ENABLE
#define GPIO111_PULL      GPIO_PULL_DOWN
#define GPIO111_DATAOUT   GPIO_OUT_ZERO
#define GPIO111_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 112
#define GPIO112_MODE      GPIO_MODE_01
#define GPIO112_DIR       GPIO_DIR_OUT
#define GPIO112_PULLEN    GPIO_PULL_DISABLE
#define GPIO112_PULL      GPIO_PULL_DOWN
#define GPIO112_DATAOUT   GPIO_OUT_ZERO
#define GPIO112_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 113
#define GPIO113_MODE      GPIO_MODE_00
#define GPIO113_DIR       GPIO_DIR_IN
#define GPIO113_PULLEN    GPIO_PULL_ENABLE
#define GPIO113_PULL      GPIO_PULL_DOWN
#define GPIO113_DATAOUT   GPIO_OUT_ZERO
#define GPIO113_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 114
#define GPIO114_MODE      GPIO_MODE_00
#define GPIO114_DIR       GPIO_DIR_IN
#define GPIO114_PULLEN    GPIO_PULL_ENABLE
#define GPIO114_PULL      GPIO_PULL_DOWN
#define GPIO114_DATAOUT   GPIO_OUT_ZERO
#define GPIO114_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 115
#define GPIO115_MODE      GPIO_MODE_01
#define GPIO115_DIR       GPIO_DIR_IN
#define GPIO115_PULLEN    GPIO_PULL_DISABLE
#define GPIO115_PULL      GPIO_PULL_DOWN
#define GPIO115_DATAOUT   GPIO_OUT_ZERO
#define GPIO115_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 116
#define GPIO116_MODE      GPIO_MODE_00
#define GPIO116_DIR       GPIO_DIR_IN
#define GPIO116_PULLEN    GPIO_PULL_ENABLE
#define GPIO116_PULL      GPIO_PULL_DOWN
#define GPIO116_DATAOUT   GPIO_OUT_ZERO
#define GPIO116_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 117
#define GPIO117_MODE      GPIO_MODE_01
#define GPIO117_DIR       GPIO_DIR_IN
#define GPIO117_PULLEN    GPIO_PULL_ENABLE
#define GPIO117_PULL      GPIO_PULL_UP
#define GPIO117_DATAOUT   GPIO_OUT_ZERO
#define GPIO117_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 118
#define GPIO118_MODE      GPIO_MODE_01
#define GPIO118_DIR       GPIO_DIR_IN
#define GPIO118_PULLEN    GPIO_PULL_ENABLE
#define GPIO118_PULL      GPIO_PULL_UP
#define GPIO118_DATAOUT   GPIO_OUT_ZERO
#define GPIO118_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 119
#define GPIO119_MODE      GPIO_MODE_01
#define GPIO119_DIR       GPIO_DIR_IN
#define GPIO119_PULLEN    GPIO_PULL_ENABLE
#define GPIO119_PULL      GPIO_PULL_UP
#define GPIO119_DATAOUT   GPIO_OUT_ZERO
#define GPIO119_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 120
#define GPIO120_MODE      GPIO_MODE_00
#define GPIO120_DIR       GPIO_DIR_IN
#define GPIO120_PULLEN    GPIO_PULL_ENABLE
#define GPIO120_PULL      GPIO_PULL_DOWN
#define GPIO120_DATAOUT   GPIO_OUT_ZERO
#define GPIO120_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 121
#define GPIO121_MODE      GPIO_MODE_00
#define GPIO121_DIR       GPIO_DIR_IN
#define GPIO121_PULLEN    GPIO_PULL_ENABLE
#define GPIO121_PULL      GPIO_PULL_DOWN
#define GPIO121_DATAOUT   GPIO_OUT_ZERO
#define GPIO121_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 122
#define GPIO122_MODE      GPIO_MODE_00
#define GPIO122_DIR       GPIO_DIR_IN
#define GPIO122_PULLEN    GPIO_PULL_ENABLE
#define GPIO122_PULL      GPIO_PULL_DOWN
#define GPIO122_DATAOUT   GPIO_OUT_ZERO
#define GPIO122_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 123
#define GPIO123_MODE      GPIO_MODE_00
#define GPIO123_DIR       GPIO_DIR_IN
#define GPIO123_PULLEN    GPIO_PULL_ENABLE
#define GPIO123_PULL      GPIO_PULL_DOWN
#define GPIO123_DATAOUT   GPIO_OUT_ZERO
#define GPIO123_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 124
#define GPIO124_MODE      GPIO_MODE_01
#define GPIO124_DIR       GPIO_DIR_IN
#define GPIO124_PULLEN    GPIO_PULL_ENABLE
#define GPIO124_PULL      GPIO_PULL_DOWN
#define GPIO124_DATAOUT   GPIO_OUT_ZERO
#define GPIO124_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 125
#define GPIO125_MODE      GPIO_MODE_01
#define GPIO125_DIR       GPIO_DIR_IN
#define GPIO125_PULLEN    GPIO_PULL_ENABLE
#define GPIO125_PULL      GPIO_PULL_DOWN
#define GPIO125_DATAOUT   GPIO_OUT_ZERO
#define GPIO125_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 126
#define GPIO126_MODE      GPIO_MODE_00
#define GPIO126_DIR       GPIO_DIR_IN
#define GPIO126_PULLEN    GPIO_PULL_ENABLE
#define GPIO126_PULL      GPIO_PULL_DOWN
#define GPIO126_DATAOUT   GPIO_OUT_ZERO
#define GPIO126_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 127
#define GPIO127_MODE      GPIO_MODE_00
#define GPIO127_DIR       GPIO_DIR_IN
#define GPIO127_PULLEN    GPIO_PULL_ENABLE
#define GPIO127_PULL      GPIO_PULL_DOWN
#define GPIO127_DATAOUT   GPIO_OUT_ZERO
#define GPIO127_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 128
#define GPIO128_MODE      GPIO_MODE_00
#define GPIO128_DIR       GPIO_DIR_IN
#define GPIO128_PULLEN    GPIO_PULL_ENABLE
#define GPIO128_PULL      GPIO_PULL_DOWN
#define GPIO128_DATAOUT   GPIO_OUT_ZERO
#define GPIO128_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 129
#define GPIO129_MODE      GPIO_MODE_00
#define GPIO129_DIR       GPIO_DIR_IN
#define GPIO129_PULLEN    GPIO_PULL_ENABLE
#define GPIO129_PULL      GPIO_PULL_DOWN
#define GPIO129_DATAOUT   GPIO_OUT_ZERO
#define GPIO129_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 130
#define GPIO130_MODE      GPIO_MODE_07
#define GPIO130_DIR       GPIO_DIR_IN
#define GPIO130_PULLEN    GPIO_PULL_ENABLE
#define GPIO130_PULL      GPIO_PULL_DOWN
#define GPIO130_DATAOUT   GPIO_OUT_ZERO
#define GPIO130_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 131
#define GPIO131_MODE      GPIO_MODE_07
#define GPIO131_DIR       GPIO_DIR_OUT
#define GPIO131_PULLEN    GPIO_PULL_DISABLE
#define GPIO131_PULL      GPIO_PULL_DOWN
#define GPIO131_DATAOUT   GPIO_OUT_ONE
#define GPIO131_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 132
#define GPIO132_MODE      GPIO_MODE_00
#define GPIO132_DIR       GPIO_DIR_IN
#define GPIO132_PULLEN    GPIO_PULL_ENABLE
#define GPIO132_PULL      GPIO_PULL_DOWN
#define GPIO132_DATAOUT   GPIO_OUT_ZERO
#define GPIO132_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 133
#define GPIO133_MODE      GPIO_MODE_00
#define GPIO133_DIR       GPIO_DIR_IN
#define GPIO133_PULLEN    GPIO_PULL_ENABLE
#define GPIO133_PULL      GPIO_PULL_DOWN
#define GPIO133_DATAOUT   GPIO_OUT_ZERO
#define GPIO133_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 134
#define GPIO134_MODE      GPIO_MODE_00
#define GPIO134_DIR       GPIO_DIR_IN
#define GPIO134_PULLEN    GPIO_PULL_ENABLE
#define GPIO134_PULL      GPIO_PULL_DOWN
#define GPIO134_DATAOUT   GPIO_OUT_ZERO
#define GPIO134_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 135
#define GPIO135_MODE      GPIO_MODE_00
#define GPIO135_DIR       GPIO_DIR_IN
#define GPIO135_PULLEN    GPIO_PULL_ENABLE
#define GPIO135_PULL      GPIO_PULL_DOWN
#define GPIO135_DATAOUT   GPIO_OUT_ZERO
#define GPIO135_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 136
#define GPIO136_MODE      GPIO_MODE_00
#define GPIO136_DIR       GPIO_DIR_IN
#define GPIO136_PULLEN    GPIO_PULL_ENABLE
#define GPIO136_PULL      GPIO_PULL_DOWN
#define GPIO136_DATAOUT   GPIO_OUT_ZERO
#define GPIO136_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 137
#define GPIO137_MODE      GPIO_MODE_00
#define GPIO137_DIR       GPIO_DIR_IN
#define GPIO137_PULLEN    GPIO_PULL_ENABLE
#define GPIO137_PULL      GPIO_PULL_DOWN
#define GPIO137_DATAOUT   GPIO_OUT_ZERO
#define GPIO137_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 138
#define GPIO138_MODE      GPIO_MODE_00
#define GPIO138_DIR       GPIO_DIR_IN
#define GPIO138_PULLEN    GPIO_PULL_ENABLE
#define GPIO138_PULL      GPIO_PULL_UP
#define GPIO138_DATAOUT   GPIO_OUT_ZERO
#define GPIO138_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 139
#define GPIO139_MODE      GPIO_MODE_00
#define GPIO139_DIR       GPIO_DIR_IN
#define GPIO139_PULLEN    GPIO_PULL_ENABLE
#define GPIO139_PULL      GPIO_PULL_DOWN
#define GPIO139_DATAOUT   GPIO_OUT_ZERO
#define GPIO139_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 140
#define GPIO140_MODE      GPIO_MODE_00
#define GPIO140_DIR       GPIO_DIR_IN
#define GPIO140_PULLEN    GPIO_PULL_ENABLE
#define GPIO140_PULL      GPIO_PULL_DOWN
#define GPIO140_DATAOUT   GPIO_OUT_ZERO
#define GPIO140_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 141
#define GPIO141_MODE      GPIO_MODE_04
#define GPIO141_DIR       GPIO_DIR_OUT
#define GPIO141_PULLEN    GPIO_PULL_DISABLE
#define GPIO141_PULL      GPIO_PULL_DOWN
#define GPIO141_DATAOUT   GPIO_OUT_ZERO
#define GPIO141_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 142
#define GPIO142_MODE      GPIO_MODE_00
#define GPIO142_DIR       GPIO_DIR_IN
#define GPIO142_PULLEN    GPIO_PULL_ENABLE
#define GPIO142_PULL      GPIO_PULL_DOWN
#define GPIO142_DATAOUT   GPIO_OUT_ZERO
#define GPIO142_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 143
#define GPIO143_MODE      GPIO_MODE_00
#define GPIO143_DIR       GPIO_DIR_IN
#define GPIO143_PULLEN    GPIO_PULL_ENABLE
#define GPIO143_PULL      GPIO_PULL_DOWN
#define GPIO143_DATAOUT   GPIO_OUT_ZERO
#define GPIO143_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 144
#define GPIO144_MODE      GPIO_MODE_00
#define GPIO144_DIR       GPIO_DIR_IN
#define GPIO144_PULLEN    GPIO_PULL_ENABLE
#define GPIO144_PULL      GPIO_PULL_DOWN
#define GPIO144_DATAOUT   GPIO_OUT_ZERO
#define GPIO144_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 145
#define GPIO145_MODE      GPIO_MODE_00
#define GPIO145_DIR       GPIO_DIR_IN
#define GPIO145_PULLEN    GPIO_PULL_ENABLE
#define GPIO145_PULL      GPIO_PULL_DOWN
#define GPIO145_DATAOUT   GPIO_OUT_ZERO
#define GPIO145_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 146
#define GPIO146_MODE      GPIO_MODE_00
#define GPIO146_DIR       GPIO_DIR_IN
#define GPIO146_PULLEN    GPIO_PULL_ENABLE
#define GPIO146_PULL      GPIO_PULL_DOWN
#define GPIO146_DATAOUT   GPIO_OUT_ZERO
#define GPIO146_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 147
#define GPIO147_MODE      GPIO_MODE_00
#define GPIO147_DIR       GPIO_DIR_IN
#define GPIO147_PULLEN    GPIO_PULL_ENABLE
#define GPIO147_PULL      GPIO_PULL_DOWN
#define GPIO147_DATAOUT   GPIO_OUT_ZERO
#define GPIO147_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 148
#define GPIO148_MODE      GPIO_MODE_00
#define GPIO148_DIR       GPIO_DIR_IN
#define GPIO148_PULLEN    GPIO_PULL_ENABLE
#define GPIO148_PULL      GPIO_PULL_DOWN
#define GPIO148_DATAOUT   GPIO_OUT_ZERO
#define GPIO148_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 149
#define GPIO149_MODE      GPIO_MODE_00
#define GPIO149_DIR       GPIO_DIR_IN
#define GPIO149_PULLEN    GPIO_PULL_ENABLE
#define GPIO149_PULL      GPIO_PULL_DOWN
#define GPIO149_DATAOUT   GPIO_OUT_ZERO
#define GPIO149_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 150
#define GPIO150_MODE      GPIO_MODE_00
#define GPIO150_DIR       GPIO_DIR_IN
#define GPIO150_PULLEN    GPIO_PULL_ENABLE
#define GPIO150_PULL      GPIO_PULL_DOWN
#define GPIO150_DATAOUT   GPIO_OUT_ZERO
#define GPIO150_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 151
#define GPIO151_MODE      GPIO_MODE_00
#define GPIO151_DIR       GPIO_DIR_IN
#define GPIO151_PULLEN    GPIO_PULL_ENABLE
#define GPIO151_PULL      GPIO_PULL_DOWN
#define GPIO151_DATAOUT   GPIO_OUT_ZERO
#define GPIO151_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 152
#define GPIO152_MODE      GPIO_MODE_00
#define GPIO152_DIR       GPIO_DIR_IN
#define GPIO152_PULLEN    GPIO_PULL_ENABLE
#define GPIO152_PULL      GPIO_PULL_DOWN
#define GPIO152_DATAOUT   GPIO_OUT_ZERO
#define GPIO152_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 153
#define GPIO153_MODE      GPIO_MODE_00
#define GPIO153_DIR       GPIO_DIR_IN
#define GPIO153_PULLEN    GPIO_PULL_ENABLE
#define GPIO153_PULL      GPIO_PULL_DOWN
#define GPIO153_DATAOUT   GPIO_OUT_ZERO
#define GPIO153_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 154
#define GPIO154_MODE      GPIO_MODE_00
#define GPIO154_DIR       GPIO_DIR_IN
#define GPIO154_PULLEN    GPIO_PULL_ENABLE
#define GPIO154_PULL      GPIO_PULL_DOWN
#define GPIO154_DATAOUT   GPIO_OUT_ZERO
#define GPIO154_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 155
#define GPIO155_MODE      GPIO_MODE_00
#define GPIO155_DIR       GPIO_DIR_IN
#define GPIO155_PULLEN    GPIO_PULL_ENABLE
#define GPIO155_PULL      GPIO_PULL_DOWN
#define GPIO155_DATAOUT   GPIO_OUT_ZERO
#define GPIO155_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 156
#define GPIO156_MODE      GPIO_MODE_00
#define GPIO156_DIR       GPIO_DIR_IN
#define GPIO156_PULLEN    GPIO_PULL_ENABLE
#define GPIO156_PULL      GPIO_PULL_DOWN
#define GPIO156_DATAOUT   GPIO_OUT_ZERO
#define GPIO156_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 157
#define GPIO157_MODE      GPIO_MODE_00
#define GPIO157_DIR       GPIO_DIR_IN
#define GPIO157_PULLEN    GPIO_PULL_ENABLE
#define GPIO157_PULL      GPIO_PULL_DOWN
#define GPIO157_DATAOUT   GPIO_OUT_ZERO
#define GPIO157_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 158
#define GPIO158_MODE      GPIO_MODE_00
#define GPIO158_DIR       GPIO_DIR_IN
#define GPIO158_PULLEN    GPIO_PULL_ENABLE
#define GPIO158_PULL      GPIO_PULL_DOWN
#define GPIO158_DATAOUT   GPIO_OUT_ZERO
#define GPIO158_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 159
#define GPIO159_MODE      GPIO_MODE_00
#define GPIO159_DIR       GPIO_DIR_IN
#define GPIO159_PULLEN    GPIO_PULL_ENABLE
#define GPIO159_PULL      GPIO_PULL_DOWN
#define GPIO159_DATAOUT   GPIO_OUT_ZERO
#define GPIO159_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 160
#define GPIO160_MODE      GPIO_MODE_00
#define GPIO160_DIR       GPIO_DIR_IN
#define GPIO160_PULLEN    GPIO_PULL_ENABLE
#define GPIO160_PULL      GPIO_PULL_DOWN
#define GPIO160_DATAOUT   GPIO_OUT_ZERO
#define GPIO160_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 161
#define GPIO161_MODE      GPIO_MODE_00
#define GPIO161_DIR       GPIO_DIR_IN
#define GPIO161_PULLEN    GPIO_PULL_ENABLE
#define GPIO161_PULL      GPIO_PULL_DOWN
#define GPIO161_DATAOUT   GPIO_OUT_ZERO
#define GPIO161_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 162
#define GPIO162_MODE      GPIO_MODE_00
#define GPIO162_DIR       GPIO_DIR_IN
#define GPIO162_PULLEN    GPIO_PULL_ENABLE
#define GPIO162_PULL      GPIO_PULL_DOWN
#define GPIO162_DATAOUT   GPIO_OUT_ZERO
#define GPIO162_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 163
#define GPIO163_MODE      GPIO_MODE_00
#define GPIO163_DIR       GPIO_DIR_IN
#define GPIO163_PULLEN    GPIO_PULL_ENABLE
#define GPIO163_PULL      GPIO_PULL_DOWN
#define GPIO163_DATAOUT   GPIO_OUT_ZERO
#define GPIO163_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 164
#define GPIO164_MODE      GPIO_MODE_00
#define GPIO164_DIR       GPIO_DIR_IN
#define GPIO164_PULLEN    GPIO_PULL_ENABLE
#define GPIO164_PULL      GPIO_PULL_DOWN
#define GPIO164_DATAOUT   GPIO_OUT_ZERO
#define GPIO164_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 165
#define GPIO165_MODE      GPIO_MODE_00
#define GPIO165_DIR       GPIO_DIR_IN
#define GPIO165_PULLEN    GPIO_PULL_ENABLE
#define GPIO165_PULL      GPIO_PULL_DOWN
#define GPIO165_DATAOUT   GPIO_OUT_ZERO
#define GPIO165_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 166
#define GPIO166_MODE      GPIO_MODE_00
#define GPIO166_DIR       GPIO_DIR_IN
#define GPIO166_PULLEN    GPIO_PULL_ENABLE
#define GPIO166_PULL      GPIO_PULL_DOWN
#define GPIO166_DATAOUT   GPIO_OUT_ZERO
#define GPIO166_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 167
#define GPIO167_MODE      GPIO_MODE_00
#define GPIO167_DIR       GPIO_DIR_IN
#define GPIO167_PULLEN    GPIO_PULL_ENABLE
#define GPIO167_PULL      GPIO_PULL_DOWN
#define GPIO167_DATAOUT   GPIO_OUT_ZERO
#define GPIO167_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 168
#define GPIO168_MODE      GPIO_MODE_00
#define GPIO168_DIR       GPIO_DIR_IN
#define GPIO168_PULLEN    GPIO_PULL_ENABLE
#define GPIO168_PULL      GPIO_PULL_DOWN
#define GPIO168_DATAOUT   GPIO_OUT_ZERO
#define GPIO168_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 169
#define GPIO169_MODE      GPIO_MODE_00
#define GPIO169_DIR       GPIO_DIR_IN
#define GPIO169_PULLEN    GPIO_PULL_ENABLE
#define GPIO169_PULL      GPIO_PULL_DOWN
#define GPIO169_DATAOUT   GPIO_OUT_ZERO
#define GPIO169_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 170
#define GPIO170_MODE      GPIO_MODE_00
#define GPIO170_DIR       GPIO_DIR_IN
#define GPIO170_PULLEN    GPIO_PULL_ENABLE
#define GPIO170_PULL      GPIO_PULL_DOWN
#define GPIO170_DATAOUT   GPIO_OUT_ZERO
#define GPIO170_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 171
#define GPIO171_MODE      GPIO_MODE_01
#define GPIO171_DIR       GPIO_DIR_IN
#define GPIO171_PULLEN    GPIO_PULL_DISABLE
#define GPIO171_PULL      GPIO_PULL_DOWN
#define GPIO171_DATAOUT   GPIO_OUT_ZERO
#define GPIO171_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 172
#define GPIO172_MODE      GPIO_MODE_00
#define GPIO172_DIR       GPIO_DIR_IN
#define GPIO172_PULLEN    GPIO_PULL_ENABLE
#define GPIO172_PULL      GPIO_PULL_DOWN
#define GPIO172_DATAOUT   GPIO_OUT_ZERO
#define GPIO172_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 173
#define GPIO173_MODE      GPIO_MODE_00
#define GPIO173_DIR       GPIO_DIR_IN
#define GPIO173_PULLEN    GPIO_PULL_ENABLE
#define GPIO173_PULL      GPIO_PULL_DOWN
#define GPIO173_DATAOUT   GPIO_OUT_ZERO
#define GPIO173_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 174
#define GPIO174_MODE      GPIO_MODE_00
#define GPIO174_DIR       GPIO_DIR_IN
#define GPIO174_PULLEN    GPIO_PULL_ENABLE
#define GPIO174_PULL      GPIO_PULL_DOWN
#define GPIO174_DATAOUT   GPIO_OUT_ZERO
#define GPIO174_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 175
#define GPIO175_MODE      GPIO_MODE_00
#define GPIO175_DIR       GPIO_DIR_IN
#define GPIO175_PULLEN    GPIO_PULL_ENABLE
#define GPIO175_PULL      GPIO_PULL_DOWN
#define GPIO175_DATAOUT   GPIO_OUT_ZERO
#define GPIO175_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 176
#define GPIO176_MODE      GPIO_MODE_00
#define GPIO176_DIR       GPIO_DIR_IN
#define GPIO176_PULLEN    GPIO_PULL_ENABLE
#define GPIO176_PULL      GPIO_PULL_DOWN
#define GPIO176_DATAOUT   GPIO_OUT_ZERO
#define GPIO176_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 177
#define GPIO177_MODE      GPIO_MODE_00
#define GPIO177_DIR       GPIO_DIR_IN
#define GPIO177_PULLEN    GPIO_PULL_ENABLE
#define GPIO177_PULL      GPIO_PULL_DOWN
#define GPIO177_DATAOUT   GPIO_OUT_ZERO
#define GPIO177_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 178
#define GPIO178_MODE      GPIO_MODE_00
#define GPIO178_DIR       GPIO_DIR_IN
#define GPIO178_PULLEN    GPIO_PULL_ENABLE
#define GPIO178_PULL      GPIO_PULL_DOWN
#define GPIO178_DATAOUT   GPIO_OUT_ZERO
#define GPIO178_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 179
#define GPIO179_MODE      GPIO_MODE_00
#define GPIO179_DIR       GPIO_DIR_IN
#define GPIO179_PULLEN    GPIO_PULL_ENABLE
#define GPIO179_PULL      GPIO_PULL_DOWN
#define GPIO179_DATAOUT   GPIO_OUT_ZERO
#define GPIO179_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 180
#define GPIO180_MODE      GPIO_MODE_01
#define GPIO180_DIR       GPIO_DIR_IN
#define GPIO180_PULLEN    GPIO_PULL_ENABLE
#define GPIO180_PULL      GPIO_PULL_UP
#define GPIO180_DATAOUT   GPIO_OUT_ZERO
#define GPIO180_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 181
#define GPIO181_MODE      GPIO_MODE_01
#define GPIO181_DIR       GPIO_DIR_IN
#define GPIO181_PULLEN    GPIO_PULL_ENABLE
#define GPIO181_PULL      GPIO_PULL_UP
#define GPIO181_DATAOUT   GPIO_OUT_ZERO
#define GPIO181_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 182
#define GPIO182_MODE      GPIO_MODE_00
#define GPIO182_DIR       GPIO_DIR_IN
#define GPIO182_PULLEN    GPIO_PULL_ENABLE
#define GPIO182_PULL      GPIO_PULL_DOWN
#define GPIO182_DATAOUT   GPIO_OUT_ZERO
#define GPIO182_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 183
#define GPIO183_MODE      GPIO_MODE_01
#define GPIO183_DIR       GPIO_DIR_IN
#define GPIO183_PULLEN    GPIO_PULL_ENABLE
#define GPIO183_PULL      GPIO_PULL_UP
#define GPIO183_DATAOUT   GPIO_OUT_ZERO
#define GPIO183_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 184
#define GPIO184_MODE      GPIO_MODE_01
#define GPIO184_DIR       GPIO_DIR_OUT
#define GPIO184_PULLEN    GPIO_PULL_DISABLE
#define GPIO184_PULL      GPIO_PULL_DOWN
#define GPIO184_DATAOUT   GPIO_OUT_ZERO
#define GPIO184_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 185
#define GPIO185_MODE      GPIO_MODE_01
#define GPIO185_DIR       GPIO_DIR_IN
#define GPIO185_PULLEN    GPIO_PULL_ENABLE
#define GPIO185_PULL      GPIO_PULL_UP
#define GPIO185_DATAOUT   GPIO_OUT_ZERO
#define GPIO185_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 186
#define GPIO186_MODE      GPIO_MODE_01
#define GPIO186_DIR       GPIO_DIR_IN
#define GPIO186_PULLEN    GPIO_PULL_ENABLE
#define GPIO186_PULL      GPIO_PULL_UP
#define GPIO186_DATAOUT   GPIO_OUT_ZERO
#define GPIO186_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 187
#define GPIO187_MODE      GPIO_MODE_00
#define GPIO187_DIR       GPIO_DIR_IN
#define GPIO187_PULLEN    GPIO_PULL_ENABLE
#define GPIO187_PULL      GPIO_PULL_DOWN
#define GPIO187_DATAOUT   GPIO_OUT_ZERO
#define GPIO187_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 188
#define GPIO188_MODE      GPIO_MODE_00
#define GPIO188_DIR       GPIO_DIR_IN
#define GPIO188_PULLEN    GPIO_PULL_ENABLE
#define GPIO188_PULL      GPIO_PULL_DOWN
#define GPIO188_DATAOUT   GPIO_OUT_ZERO
#define GPIO188_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 189
#define GPIO189_MODE      GPIO_MODE_00
#define GPIO189_DIR       GPIO_DIR_IN
#define GPIO189_PULLEN    GPIO_PULL_ENABLE
#define GPIO189_PULL      GPIO_PULL_DOWN
#define GPIO189_DATAOUT   GPIO_OUT_ZERO
#define GPIO189_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 190
#define GPIO190_MODE      GPIO_MODE_00
#define GPIO190_DIR       GPIO_DIR_IN
#define GPIO190_PULLEN    GPIO_PULL_ENABLE
#define GPIO190_PULL      GPIO_PULL_DOWN
#define GPIO190_DATAOUT   GPIO_OUT_ZERO
#define GPIO190_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 191
#define GPIO191_MODE      GPIO_MODE_00
#define GPIO191_DIR       GPIO_DIR_IN
#define GPIO191_PULLEN    GPIO_PULL_ENABLE
#define GPIO191_PULL      GPIO_PULL_DOWN
#define GPIO191_DATAOUT   GPIO_OUT_ZERO
#define GPIO191_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 192
#define GPIO192_MODE      GPIO_MODE_00
#define GPIO192_DIR       GPIO_DIR_IN
#define GPIO192_PULLEN    GPIO_PULL_ENABLE
#define GPIO192_PULL      GPIO_PULL_DOWN
#define GPIO192_DATAOUT   GPIO_OUT_ZERO
#define GPIO192_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 193
#define GPIO193_MODE      GPIO_MODE_00
#define GPIO193_DIR       GPIO_DIR_IN
#define GPIO193_PULLEN    GPIO_PULL_ENABLE
#define GPIO193_PULL      GPIO_PULL_DOWN
#define GPIO193_DATAOUT   GPIO_OUT_ZERO
#define GPIO193_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 194
#define GPIO194_MODE      GPIO_MODE_00
#define GPIO194_DIR       GPIO_DIR_IN
#define GPIO194_PULLEN    GPIO_PULL_ENABLE
#define GPIO194_PULL      GPIO_PULL_DOWN
#define GPIO194_DATAOUT   GPIO_OUT_ZERO
#define GPIO194_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 195
#define GPIO195_MODE      GPIO_MODE_00
#define GPIO195_DIR       GPIO_DIR_IN
#define GPIO195_PULLEN    GPIO_PULL_ENABLE
#define GPIO195_PULL      GPIO_PULL_DOWN
#define GPIO195_DATAOUT   GPIO_OUT_ZERO
#define GPIO195_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 196
#define GPIO196_MODE      GPIO_MODE_00
#define GPIO196_DIR       GPIO_DIR_IN
#define GPIO196_PULLEN    GPIO_PULL_ENABLE
#define GPIO196_PULL      GPIO_PULL_DOWN
#define GPIO196_DATAOUT   GPIO_OUT_ZERO
#define GPIO196_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 197
#define GPIO197_MODE      GPIO_MODE_00
#define GPIO197_DIR       GPIO_DIR_IN
#define GPIO197_PULLEN    GPIO_PULL_ENABLE
#define GPIO197_PULL      GPIO_PULL_DOWN
#define GPIO197_DATAOUT   GPIO_OUT_ZERO
#define GPIO197_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 198
#define GPIO198_MODE      GPIO_MODE_00
#define GPIO198_DIR       GPIO_DIR_IN
#define GPIO198_PULLEN    GPIO_PULL_ENABLE
#define GPIO198_PULL      GPIO_PULL_DOWN
#define GPIO198_DATAOUT   GPIO_OUT_ZERO
#define GPIO198_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 199
#define GPIO199_MODE      GPIO_MODE_00
#define GPIO199_DIR       GPIO_DIR_IN
#define GPIO199_PULLEN    GPIO_PULL_ENABLE
#define GPIO199_PULL      GPIO_PULL_DOWN
#define GPIO199_DATAOUT   GPIO_OUT_ZERO
#define GPIO199_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 200
#define GPIO200_MODE      GPIO_MODE_00
#define GPIO200_DIR       GPIO_DIR_IN
#define GPIO200_PULLEN    GPIO_PULL_ENABLE
#define GPIO200_PULL      GPIO_PULL_DOWN
#define GPIO200_DATAOUT   GPIO_OUT_ZERO
#define GPIO200_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 201
#define GPIO201_MODE      GPIO_MODE_00
#define GPIO201_DIR       GPIO_DIR_IN
#define GPIO201_PULLEN    GPIO_PULL_ENABLE
#define GPIO201_PULL      GPIO_PULL_DOWN
#define GPIO201_DATAOUT   GPIO_OUT_ZERO
#define GPIO201_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 202
#define GPIO202_MODE      GPIO_MODE_00
#define GPIO202_DIR       GPIO_DIR_IN
#define GPIO202_PULLEN    GPIO_PULL_ENABLE
#define GPIO202_PULL      GPIO_PULL_DOWN
#define GPIO202_DATAOUT   GPIO_OUT_ZERO
#define GPIO202_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 203
#define GPIO203_MODE      GPIO_MODE_00
#define GPIO203_DIR       GPIO_DIR_IN
#define GPIO203_PULLEN    GPIO_PULL_ENABLE
#define GPIO203_PULL      GPIO_PULL_DOWN
#define GPIO203_DATAOUT   GPIO_OUT_ZERO
#define GPIO203_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 204
#define GPIO204_MODE      GPIO_MODE_00
#define GPIO204_DIR       GPIO_DIR_IN
#define GPIO204_PULLEN    GPIO_PULL_ENABLE
#define GPIO204_PULL      GPIO_PULL_DOWN
#define GPIO204_DATAOUT   GPIO_OUT_ZERO
#define GPIO204_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 205
#define GPIO205_MODE      GPIO_MODE_00
#define GPIO205_DIR       GPIO_DIR_IN
#define GPIO205_PULLEN    GPIO_PULL_ENABLE
#define GPIO205_PULL      GPIO_PULL_DOWN
#define GPIO205_DATAOUT   GPIO_OUT_ZERO
#define GPIO205_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 206
#define GPIO206_MODE      GPIO_MODE_00
#define GPIO206_DIR       GPIO_DIR_IN
#define GPIO206_PULLEN    GPIO_PULL_ENABLE
#define GPIO206_PULL      GPIO_PULL_DOWN
#define GPIO206_DATAOUT   GPIO_OUT_ZERO
#define GPIO206_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 207
#define GPIO207_MODE      GPIO_MODE_00
#define GPIO207_DIR       GPIO_DIR_IN
#define GPIO207_PULLEN    GPIO_PULL_ENABLE
#define GPIO207_PULL      GPIO_PULL_DOWN
#define GPIO207_DATAOUT   GPIO_OUT_ZERO
#define GPIO207_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 208
#define GPIO208_MODE      GPIO_MODE_00
#define GPIO208_DIR       GPIO_DIR_IN
#define GPIO208_PULLEN    GPIO_PULL_ENABLE
#define GPIO208_PULL      GPIO_PULL_DOWN
#define GPIO208_DATAOUT   GPIO_OUT_ZERO
#define GPIO208_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 209
#define GPIO209_MODE      GPIO_MODE_00
#define GPIO209_DIR       GPIO_DIR_OUT
#define GPIO209_PULLEN    GPIO_PULL_DISABLE
#define GPIO209_PULL      GPIO_PULL_DOWN
#define GPIO209_DATAOUT   GPIO_OUT_ZERO
#define GPIO209_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 210
#define GPIO210_MODE      GPIO_MODE_01
#define GPIO210_DIR       GPIO_DIR_IN
#define GPIO210_PULLEN    GPIO_PULL_ENABLE
#define GPIO210_PULL      GPIO_PULL_DOWN
#define GPIO210_DATAOUT   GPIO_OUT_ZERO
#define GPIO210_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 211
#define GPIO211_MODE      GPIO_MODE_01
#define GPIO211_DIR       GPIO_DIR_IN
#define GPIO211_PULLEN    GPIO_PULL_ENABLE
#define GPIO211_PULL      GPIO_PULL_DOWN
#define GPIO211_DATAOUT   GPIO_OUT_ZERO
#define GPIO211_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 212
#define GPIO212_MODE      GPIO_MODE_01
#define GPIO212_DIR       GPIO_DIR_IN
#define GPIO212_PULLEN    GPIO_PULL_ENABLE
#define GPIO212_PULL      GPIO_PULL_DOWN
#define GPIO212_DATAOUT   GPIO_OUT_ZERO
#define GPIO212_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 213
#define GPIO213_MODE      GPIO_MODE_00
#define GPIO213_DIR       GPIO_DIR_OUT
#define GPIO213_PULLEN    GPIO_PULL_DISABLE
#define GPIO213_PULL      GPIO_PULL_DOWN
#define GPIO213_DATAOUT   GPIO_OUT_ZERO
#define GPIO213_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 214
#define GPIO214_MODE      GPIO_MODE_01
#define GPIO214_DIR       GPIO_DIR_IN
#define GPIO214_PULLEN    GPIO_PULL_ENABLE
#define GPIO214_PULL      GPIO_PULL_UP
#define GPIO214_DATAOUT   GPIO_OUT_ZERO
#define GPIO214_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 215
#define GPIO215_MODE      GPIO_MODE_01
#define GPIO215_DIR       GPIO_DIR_IN
#define GPIO215_PULLEN    GPIO_PULL_ENABLE
#define GPIO215_PULL      GPIO_PULL_UP
#define GPIO215_DATAOUT   GPIO_OUT_ZERO
#define GPIO215_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 216
#define GPIO216_MODE      GPIO_MODE_01
#define GPIO216_DIR       GPIO_DIR_OUT
#define GPIO216_PULLEN    GPIO_PULL_ENABLE
#define GPIO216_PULL      GPIO_PULL_UP
#define GPIO216_DATAOUT   GPIO_OUT_ZERO
#define GPIO216_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 217
#define GPIO217_MODE      GPIO_MODE_01
#define GPIO217_DIR       GPIO_DIR_OUT
#define GPIO217_PULLEN    GPIO_PULL_ENABLE
#define GPIO217_PULL      GPIO_PULL_UP
#define GPIO217_DATAOUT   GPIO_OUT_ZERO
#define GPIO217_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 218
#define GPIO218_MODE      GPIO_MODE_01
#define GPIO218_DIR       GPIO_DIR_IN
#define GPIO218_PULLEN    GPIO_PULL_ENABLE
#define GPIO218_PULL      GPIO_PULL_DOWN
#define GPIO218_DATAOUT   GPIO_OUT_ZERO
#define GPIO218_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 219
#define GPIO219_MODE      GPIO_MODE_01
#define GPIO219_DIR       GPIO_DIR_IN
#define GPIO219_PULLEN    GPIO_PULL_ENABLE
#define GPIO219_PULL      GPIO_PULL_UP
#define GPIO219_DATAOUT   GPIO_OUT_ZERO
#define GPIO219_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 220
#define GPIO220_MODE      GPIO_MODE_01
#define GPIO220_DIR       GPIO_DIR_OUT
#define GPIO220_PULLEN    GPIO_PULL_DISABLE
#define GPIO220_PULL      GPIO_PULL_DOWN
#define GPIO220_DATAOUT   GPIO_OUT_ONE
#define GPIO220_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 221
#define GPIO221_MODE      GPIO_MODE_01
#define GPIO221_DIR       GPIO_DIR_OUT
#define GPIO221_PULLEN    GPIO_PULL_DISABLE
#define GPIO221_PULL      GPIO_PULL_DOWN
#define GPIO221_DATAOUT   GPIO_OUT_ZERO
#define GPIO221_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 222
#define GPIO222_MODE      GPIO_MODE_01
#define GPIO222_DIR       GPIO_DIR_OUT
#define GPIO222_PULLEN    GPIO_PULL_DISABLE
#define GPIO222_PULL      GPIO_PULL_DOWN
#define GPIO222_DATAOUT   GPIO_OUT_ZERO
#define GPIO222_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 223
#define GPIO223_MODE      GPIO_MODE_01
#define GPIO223_DIR       GPIO_DIR_IN
#define GPIO223_PULLEN    GPIO_PULL_ENABLE
#define GPIO223_PULL      GPIO_PULL_DOWN
#define GPIO223_DATAOUT   GPIO_OUT_ZERO
#define GPIO223_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 224
#define GPIO224_MODE      GPIO_MODE_01
#define GPIO224_DIR       GPIO_DIR_OUT
#define GPIO224_PULLEN    GPIO_PULL_DISABLE
#define GPIO224_PULL      GPIO_PULL_DOWN
#define GPIO224_DATAOUT   GPIO_OUT_ZERO
#define GPIO224_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 225
#define GPIO225_MODE      GPIO_MODE_00
#define GPIO225_DIR       GPIO_DIR_OUT
#define GPIO225_PULLEN    GPIO_PULL_DISABLE
#define GPIO225_PULL      GPIO_PULL_DOWN
#define GPIO225_DATAOUT   GPIO_OUT_ZERO
#define GPIO225_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 226
#define GPIO226_MODE      GPIO_MODE_01
#define GPIO226_DIR       GPIO_DIR_IN
#define GPIO226_PULLEN    GPIO_PULL_ENABLE
#define GPIO226_PULL      GPIO_PULL_UP
#define GPIO226_DATAOUT   GPIO_OUT_ZERO
#define GPIO226_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 227
#define GPIO227_MODE      GPIO_MODE_01
#define GPIO227_DIR       GPIO_DIR_IN
#define GPIO227_PULLEN    GPIO_PULL_ENABLE
#define GPIO227_PULL      GPIO_PULL_UP
#define GPIO227_DATAOUT   GPIO_OUT_ZERO
#define GPIO227_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 228
#define GPIO228_MODE      GPIO_MODE_01
#define GPIO228_DIR       GPIO_DIR_IN
#define GPIO228_PULLEN    GPIO_PULL_ENABLE
#define GPIO228_PULL      GPIO_PULL_UP
#define GPIO228_DATAOUT   GPIO_OUT_ZERO
#define GPIO228_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 229
#define GPIO229_MODE      GPIO_MODE_01
#define GPIO229_DIR       GPIO_DIR_IN
#define GPIO229_PULLEN    GPIO_PULL_ENABLE
#define GPIO229_PULL      GPIO_PULL_DOWN
#define GPIO229_DATAOUT   GPIO_OUT_ZERO
#define GPIO229_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 230
#define GPIO230_MODE      GPIO_MODE_01
#define GPIO230_DIR       GPIO_DIR_IN
#define GPIO230_PULLEN    GPIO_PULL_ENABLE
#define GPIO230_PULL      GPIO_PULL_UP
#define GPIO230_DATAOUT   GPIO_OUT_ZERO
#define GPIO230_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 231
#define GPIO231_MODE      GPIO_MODE_01
#define GPIO231_DIR       GPIO_DIR_IN
#define GPIO231_PULLEN    GPIO_PULL_ENABLE
#define GPIO231_PULL      GPIO_PULL_UP
#define GPIO231_DATAOUT   GPIO_OUT_ZERO
#define GPIO231_DATAINV   GPIO_DATA_UNINV

//Configureation for pmic gpio 

//Configureation for Pin 0
#define GPIOEXT0_MODE      GPIO_MODE_01
#define GPIOEXT0_DIR       GPIO_DIR_IN
#define GPIOEXT0_PULLEN    GPIO_PULL_DISABLE
#define GPIOEXT0_PULL      GPIO_PULL_DOWN
#define GPIOEXT0_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT0_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 1
#define GPIOEXT1_MODE      GPIO_MODE_01
#define GPIOEXT1_DIR       GPIO_DIR_IN
#define GPIOEXT1_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT1_PULL      GPIO_PULL_UP
#define GPIOEXT1_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT1_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 2
#define GPIOEXT2_MODE      GPIO_MODE_01
#define GPIOEXT2_DIR       GPIO_DIR_IN
#define GPIOEXT2_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT2_PULL      GPIO_PULL_UP
#define GPIOEXT2_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT2_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 3
#define GPIOEXT3_MODE      GPIO_MODE_01
#define GPIOEXT3_DIR       GPIO_DIR_IN
#define GPIOEXT3_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT3_PULL      GPIO_PULL_DOWN
#define GPIOEXT3_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT3_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 4
#define GPIOEXT4_MODE      GPIO_MODE_01
#define GPIOEXT4_DIR       GPIO_DIR_IN
#define GPIOEXT4_PULLEN    GPIO_PULL_DISABLE
#define GPIOEXT4_PULL      GPIO_PULL_DOWN
#define GPIOEXT4_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT4_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 5
#define GPIOEXT5_MODE      GPIO_MODE_01
#define GPIOEXT5_DIR       GPIO_DIR_IN
#define GPIOEXT5_PULLEN    GPIO_PULL_DISABLE
#define GPIOEXT5_PULL      GPIO_PULL_DOWN
#define GPIOEXT5_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT5_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 6
#define GPIOEXT6_MODE      GPIO_MODE_01
#define GPIOEXT6_DIR       GPIO_DIR_IN
#define GPIOEXT6_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT6_PULL      GPIO_PULL_DOWN
#define GPIOEXT6_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT6_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 7
#define GPIOEXT7_MODE      GPIO_MODE_01
#define GPIOEXT7_DIR       GPIO_DIR_IN
#define GPIOEXT7_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT7_PULL      GPIO_PULL_UP
#define GPIOEXT7_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT7_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 8
#define GPIOEXT8_MODE      GPIO_MODE_01
#define GPIOEXT8_DIR       GPIO_DIR_IN
#define GPIOEXT8_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT8_PULL      GPIO_PULL_DOWN
#define GPIOEXT8_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT8_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 9
#define GPIOEXT9_MODE      GPIO_MODE_01
#define GPIOEXT9_DIR       GPIO_DIR_IN
#define GPIOEXT9_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT9_PULL      GPIO_PULL_DOWN
#define GPIOEXT9_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT9_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 10
#define GPIOEXT10_MODE      GPIO_MODE_01
#define GPIOEXT10_DIR       GPIO_DIR_IN
#define GPIOEXT10_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT10_PULL      GPIO_PULL_DOWN
#define GPIOEXT10_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT10_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 11
#define GPIOEXT11_MODE      GPIO_MODE_01
#define GPIOEXT11_DIR       GPIO_DIR_IN
#define GPIOEXT11_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT11_PULL      GPIO_PULL_DOWN
#define GPIOEXT11_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT11_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 12
#define GPIOEXT12_MODE      GPIO_MODE_01
#define GPIOEXT12_DIR       GPIO_DIR_IN
#define GPIOEXT12_PULLEN    GPIO_PULL_DISABLE
#define GPIOEXT12_PULL      GPIO_PULL_DOWN
#define GPIOEXT12_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT12_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 13
#define GPIOEXT13_MODE      GPIO_MODE_01
#define GPIOEXT13_DIR       GPIO_DIR_IN
#define GPIOEXT13_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT13_PULL      GPIO_PULL_DOWN
#define GPIOEXT13_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT13_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 14
#define GPIOEXT14_MODE      GPIO_MODE_01
#define GPIOEXT14_DIR       GPIO_DIR_IN
#define GPIOEXT14_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT14_PULL      GPIO_PULL_DOWN
#define GPIOEXT14_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT14_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 15
#define GPIOEXT15_MODE      GPIO_MODE_01
#define GPIOEXT15_DIR       GPIO_DIR_IN
#define GPIOEXT15_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT15_PULL      GPIO_PULL_DOWN
#define GPIOEXT15_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT15_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 16
#define GPIOEXT16_MODE      GPIO_MODE_01
#define GPIOEXT16_DIR       GPIO_DIR_OUT
#define GPIOEXT16_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT16_PULL      GPIO_PULL_UP
#define GPIOEXT16_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT16_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 17
#define GPIOEXT17_MODE      GPIO_MODE_01
#define GPIOEXT17_DIR       GPIO_DIR_OUT
#define GPIOEXT17_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT17_PULL      GPIO_PULL_UP
#define GPIOEXT17_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT17_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 18
#define GPIOEXT18_MODE      GPIO_MODE_01
#define GPIOEXT18_DIR       GPIO_DIR_IN
#define GPIOEXT18_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT18_PULL      GPIO_PULL_UP
#define GPIOEXT18_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT18_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 19
#define GPIOEXT19_MODE      GPIO_MODE_01
#define GPIOEXT19_DIR       GPIO_DIR_IN
#define GPIOEXT19_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT19_PULL      GPIO_PULL_UP
#define GPIOEXT19_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT19_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 20
#define GPIOEXT20_MODE      GPIO_MODE_01
#define GPIOEXT20_DIR       GPIO_DIR_IN
#define GPIOEXT20_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT20_PULL      GPIO_PULL_UP
#define GPIOEXT20_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT20_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 21
#define GPIOEXT21_MODE      GPIO_MODE_00
#define GPIOEXT21_DIR       GPIO_DIR_IN
#define GPIOEXT21_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT21_PULL      GPIO_PULL_DOWN
#define GPIOEXT21_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT21_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 22
#define GPIOEXT22_MODE      GPIO_MODE_00
#define GPIOEXT22_DIR       GPIO_DIR_IN
#define GPIOEXT22_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT22_PULL      GPIO_PULL_DOWN
#define GPIOEXT22_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT22_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 23
#define GPIOEXT23_MODE      GPIO_MODE_00
#define GPIOEXT23_DIR       GPIO_DIR_IN
#define GPIOEXT23_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT23_PULL      GPIO_PULL_DOWN
#define GPIOEXT23_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT23_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 24
#define GPIOEXT24_MODE      GPIO_MODE_00
#define GPIOEXT24_DIR       GPIO_DIR_IN
#define GPIOEXT24_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT24_PULL      GPIO_PULL_DOWN
#define GPIOEXT24_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT24_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 25
#define GPIOEXT25_MODE      GPIO_MODE_00
#define GPIOEXT25_DIR       GPIO_DIR_IN
#define GPIOEXT25_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT25_PULL      GPIO_PULL_DOWN
#define GPIOEXT25_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT25_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 26
#define GPIOEXT26_MODE      GPIO_MODE_02
#define GPIOEXT26_DIR       GPIO_DIR_IN
#define GPIOEXT26_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT26_PULL      GPIO_PULL_DOWN
#define GPIOEXT26_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT26_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 27
#define GPIOEXT27_MODE      GPIO_MODE_00
#define GPIOEXT27_DIR       GPIO_DIR_IN
#define GPIOEXT27_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT27_PULL      GPIO_PULL_DOWN
#define GPIOEXT27_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT27_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 28
#define GPIOEXT28_MODE      GPIO_MODE_00
#define GPIOEXT28_DIR       GPIO_DIR_OUT
#define GPIOEXT28_PULLEN    GPIO_PULL_DISABLE
#define GPIOEXT28_PULL      GPIO_PULL_DOWN
#define GPIOEXT28_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT28_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 29
#define GPIOEXT29_MODE      GPIO_MODE_00
#define GPIOEXT29_DIR       GPIO_DIR_OUT
#define GPIOEXT29_PULLEN    GPIO_PULL_DISABLE
#define GPIOEXT29_PULL      GPIO_PULL_DOWN
#define GPIOEXT29_DATAOUT   GPIO_OUT_ONE
#define GPIOEXT29_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 30
#define GPIOEXT30_MODE      GPIO_MODE_00
#define GPIOEXT30_DIR       GPIO_DIR_IN
#define GPIOEXT30_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT30_PULL      GPIO_PULL_DOWN
#define GPIOEXT30_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT30_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 31
#define GPIOEXT31_MODE      GPIO_MODE_02
#define GPIOEXT31_DIR       GPIO_DIR_OUT
#define GPIOEXT31_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT31_PULL      GPIO_PULL_DOWN
#define GPIOEXT31_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT31_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 32
#define GPIOEXT32_MODE      GPIO_MODE_00
#define GPIOEXT32_DIR       GPIO_DIR_IN
#define GPIOEXT32_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT32_PULL      GPIO_PULL_DOWN
#define GPIOEXT32_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT32_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 33
#define GPIOEXT33_MODE      GPIO_MODE_00
#define GPIOEXT33_DIR       GPIO_DIR_IN
#define GPIOEXT33_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT33_PULL      GPIO_PULL_DOWN
#define GPIOEXT33_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT33_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 34
#define GPIOEXT34_MODE      GPIO_MODE_00
#define GPIOEXT34_DIR       GPIO_DIR_IN
#define GPIOEXT34_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT34_PULL      GPIO_PULL_DOWN
#define GPIOEXT34_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT34_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 35
#define GPIOEXT35_MODE      GPIO_MODE_01
#define GPIOEXT35_DIR       GPIO_DIR_IN
#define GPIOEXT35_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT35_PULL      GPIO_PULL_UP
#define GPIOEXT35_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT35_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 36
#define GPIOEXT36_MODE      GPIO_MODE_01
#define GPIOEXT36_DIR       GPIO_DIR_IN
#define GPIOEXT36_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT36_PULL      GPIO_PULL_UP
#define GPIOEXT36_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT36_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 37
#define GPIOEXT37_MODE      GPIO_MODE_01
#define GPIOEXT37_DIR       GPIO_DIR_IN
#define GPIOEXT37_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT37_PULL      GPIO_PULL_UP
#define GPIOEXT37_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT37_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 38
#define GPIOEXT38_MODE      GPIO_MODE_01
#define GPIOEXT38_DIR       GPIO_DIR_IN
#define GPIOEXT38_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT38_PULL      GPIO_PULL_UP
#define GPIOEXT38_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT38_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 39
#define GPIOEXT39_MODE      GPIO_MODE_01
#define GPIOEXT39_DIR       GPIO_DIR_IN
#define GPIOEXT39_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT39_PULL      GPIO_PULL_UP
#define GPIOEXT39_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT39_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 40
#define GPIOEXT40_MODE      GPIO_MODE_01
#define GPIOEXT40_DIR       GPIO_DIR_IN
#define GPIOEXT40_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT40_PULL      GPIO_PULL_UP
#define GPIOEXT40_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT40_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 41
#define GPIOEXT41_MODE      GPIO_MODE_01
#define GPIOEXT41_DIR       GPIO_DIR_IN
#define GPIOEXT41_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT41_PULL      GPIO_PULL_DOWN
#define GPIOEXT41_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT41_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 42
#define GPIOEXT42_MODE      GPIO_MODE_01
#define GPIOEXT42_DIR       GPIO_DIR_IN
#define GPIOEXT42_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT42_PULL      GPIO_PULL_DOWN
#define GPIOEXT42_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT42_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 43
#define GPIOEXT43_MODE      GPIO_MODE_01
#define GPIOEXT43_DIR       GPIO_DIR_IN
#define GPIOEXT43_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT43_PULL      GPIO_PULL_DOWN
#define GPIOEXT43_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT43_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 44
#define GPIOEXT44_MODE      GPIO_MODE_01
#define GPIOEXT44_DIR       GPIO_DIR_IN
#define GPIOEXT44_PULLEN    GPIO_PULL_ENABLE
#define GPIOEXT44_PULL      GPIO_PULL_DOWN
#define GPIOEXT44_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT44_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 45
#define GPIOEXT45_MODE      GPIO_MODE_01
#define GPIOEXT45_DIR       GPIO_DIR_OUT
#define GPIOEXT45_PULLEN    GPIO_PULL_DISABLE
#define GPIOEXT45_PULL      GPIO_PULL_DOWN
#define GPIOEXT45_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT45_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 46
#define GPIOEXT46_MODE      GPIO_MODE_01
#define GPIOEXT46_DIR       GPIO_DIR_OUT
#define GPIOEXT46_PULLEN    GPIO_PULL_DISABLE
#define GPIOEXT46_PULL      GPIO_PULL_DOWN
#define GPIOEXT46_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT46_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 47
#define GPIOEXT47_MODE      GPIO_MODE_01
#define GPIOEXT47_DIR       GPIO_DIR_OUT
#define GPIOEXT47_PULLEN    GPIO_PULL_DISABLE
#define GPIOEXT47_PULL      GPIO_PULL_DOWN
#define GPIOEXT47_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT47_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 48
#define GPIOEXT48_MODE      GPIO_MODE_01
#define GPIOEXT48_DIR       GPIO_DIR_OUT
#define GPIOEXT48_PULLEN    GPIO_PULL_DISABLE
#define GPIOEXT48_PULL      GPIO_PULL_DOWN
#define GPIOEXT48_DATAOUT   GPIO_OUT_ZERO
#define GPIOEXT48_DATAINV   GPIO_DATA_UNINV



#endif /* __CUST_GPIO_BOOT_H__ */


