
#ifndef __CUST_GPIO_USAGE_H__
#define __CUST_GPIO_USAGE_H__


#define GPIO_GPS_LNA_PIN         GPIO13
#define GPIO_GPS_LNA_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_GPS_LNA_PIN_M_EINT  GPIO_MODE_02

#define GPIO_CTP_RST_PIN         GPIO18
#define GPIO_CTP_RST_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CTP_RST_PIN_M_EINT  GPIO_MODE_02

#define GPIO_BL_EN_PIN         GPIO24
#define GPIO_BL_EN_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_BL_EN_PIN_M_EINT  GPIO_MODE_02

#define GPIO_CAMERA_CMRST1_PIN         GPIO25
#define GPIO_CAMERA_CMRST1_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CAMERA_CMRST1_PIN_M_EINT  GPIO_MODE_02

#define GPIO_COMBO_BGF_EINT_PIN         GPIO26
#define GPIO_COMBO_BGF_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_BGF_EINT_PIN_M_EINT  GPIO_MODE_02

#define GPIO_SWCHARGER_EN_PIN         GPIO27
#define GPIO_SWCHARGER_EN_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_SWCHARGER_EN_PIN_M_EINT  GPIO_MODE_02
#define GPIO_SWCHARGER_EN_PIN_M_PWM  GPIO_MODE_05

#define GPIO_CHARGER_IC_STATUS_PIN         GPIO28
#define GPIO_CHARGER_IC_STATUS_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CHARGER_IC_STATUS_PIN_M_EINT  GPIO_MODE_02
#define GPIO_CHARGER_IC_STATUS_PIN_M_PWM  GPIO_MODE_05

#define GPIO_CAMERA_CMPDN1_PIN         GPIO31
#define GPIO_CAMERA_CMPDN1_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CAMERA_CMPDN1_PIN_M_EINT  GPIO_MODE_02

#define GPIO_PMIC_EINT_PIN         GPIO37
#define GPIO_PMIC_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_PMIC_EINT_PIN_M_EINT  GPIO_MODE_01

#define GPIO_UART_URXD1_PIN         GPIO77
#define GPIO_UART_URXD1_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_UART_URXD1_PIN_M_EINT  GPIO_MODE_02
#define GPIO_UART_URXD1_PIN_M_URXD   GPIO_MODE_01
#define GPIO_UART_URXD1_PIN_M_MD2_URXD   GPIO_MODE_05

#define GPIO_UART_UTXD1_PIN         GPIO78
#define GPIO_UART_UTXD1_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_UART_UTXD1_PIN_M_EINT  GPIO_MODE_02
#define GPIO_UART_UTXD1_PIN_M_UTXD   GPIO_MODE_01
#define GPIO_UART_UTXD1_PIN_M_MD2_UTXD   GPIO_MODE_05

#define GPIO_COMBO_PMU_EN_PIN         GPIO103
#define GPIO_COMBO_PMU_EN_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_PMU_EN_PIN_M_EINT  GPIO_MODE_02

#define GPIO_CHARGER_OVP_EINT_PIN         GPIO115
#define GPIO_CHARGER_OVP_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CHARGER_OVP_EINT_PIN_M_EINT  GPIO_MODE_01

#define GPIO_ACCDET_EINT_PIN         GPIO117
#define GPIO_ACCDET_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_ACCDET_EINT_PIN_M_EINT  GPIO_MODE_01

#define GPIO_I2C0_SDA_PIN         GPIO118
#define GPIO_I2C0_SDA_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_I2C0_SDA_PIN_M_CLK  GPIO_MODE_03
#define GPIO_I2C0_SDA_PIN_M_EINT  GPIO_MODE_02
#define GPIO_I2C0_SDA_PIN_M_PWM  GPIO_MODE_04
#define GPIO_I2C0_SDA_PIN_M_SDA   GPIO_MODE_01
#define GPIO_I2C0_SDA_PIN_CLK     CLK_OUT1
#define GPIO_I2C0_SDA_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_I2C0_SCA_PIN         GPIO119
#define GPIO_I2C0_SCA_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_I2C0_SCA_PIN_M_CLK  GPIO_MODE_03
#define GPIO_I2C0_SCA_PIN_M_EINT  GPIO_MODE_02
#define GPIO_I2C0_SCA_PIN_M_PWM  GPIO_MODE_04
#define GPIO_I2C0_SCA_PIN_M_SCL   GPIO_MODE_01
#define GPIO_I2C0_SCA_PIN_CLK     CLK_OUT0
#define GPIO_I2C0_SCA_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_CTP_EINT_PIN         GPIO124
#define GPIO_CTP_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CTP_EINT_PIN_M_CLK  GPIO_MODE_03
#define GPIO_CTP_EINT_PIN_M_EINT  GPIO_MODE_01
#define GPIO_CTP_EINT_PIN_M_PWM  GPIO_MODE_02
#define GPIO_CTP_EINT_PIN_CLK     CLK_OUT3
#define GPIO_CTP_EINT_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_ALS_EINT_PIN         GPIO125
#define GPIO_ALS_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_ALS_EINT_PIN_M_CLK  GPIO_MODE_03
#define GPIO_ALS_EINT_PIN_M_EINT  GPIO_MODE_01
#define GPIO_ALS_EINT_PIN_M_PWM  GPIO_MODE_02
#define GPIO_ALS_EINT_PIN_CLK     CLK_OUT4
#define GPIO_ALS_EINT_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_WIFI_EINT_PIN         GPIO128
#define GPIO_WIFI_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_WIFI_EINT_PIN_M_EINT  GPIO_MODE_01

#define GPIO_LCM_ID_PIN         GPIO132
#define GPIO_LCM_ID_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_LCM_ID_PIN_M_EINT  GPIO_MODE_02
#define GPIO_LCM_ID_PIN_M_PWM  GPIO_MODE_05
#define GPIO_LCM_ID_PIN_LPCE     1

#define GPIO_SIM_COVER_INT         GPIO138
#define GPIO_SIM_COVER_INT_M_GPIO  GPIO_MODE_00
#define GPIO_SIM_COVER_INT_M_EINT  GPIO_MODE_02

#define GPIO_FDD_BAND_SUPPORT_DETECT_1ST_PIN         GPIO140
#define GPIO_FDD_BAND_SUPPORT_DETECT_1ST_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_FDD_BAND_SUPPORT_DETECT_1ST_PIN_M_EINT  GPIO_MODE_02

#define GPIO_GPS_SYNC_PIN         GPIO141
#define GPIO_GPS_SYNC_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_GPS_SYNC_PIN_M_EINT  GPIO_MODE_02
#define GPIO_GPS_SYNC_PIN_M_PWM  GPIO_MODE_05
#define GPIO_GPS_SYNC_PIN_M_MD1_GPS_SYNC   GPIO_MODE_04

#define GPIO_CAMERA_CMRST_PIN         GPIO211
#define GPIO_CAMERA_CMRST_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CAMERA_CMRST_PIN_M_EINT  GPIO_MODE_02
#define GPIO_CAMERA_CMRST_PIN_M_CMRST   GPIO_MODE_01

#define GPIO_CAMERA_CMPDN_PIN         GPIO212
#define GPIO_CAMERA_CMPDN_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CAMERA_CMPDN_PIN_M_EINT  GPIO_MODE_02
#define GPIO_CAMERA_CMPDN_PIN_M_CMPDN   GPIO_MODE_01

#define GPIO_I2C1_SDA_PIN         GPIO214
#define GPIO_I2C1_SDA_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_I2C1_SDA_PIN_M_CLK  GPIO_MODE_03
#define GPIO_I2C1_SDA_PIN_M_EINT  GPIO_MODE_02
#define GPIO_I2C1_SDA_PIN_M_PWM  GPIO_MODE_04
#define GPIO_I2C1_SDA_PIN_M_SDA   GPIO_MODE_01
#define GPIO_I2C1_SDA_PIN_CLK     CLK_OUT3
#define GPIO_I2C1_SDA_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_I2C1_SCA_PIN         GPIO215
#define GPIO_I2C1_SCA_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_I2C1_SCA_PIN_M_CLK  GPIO_MODE_03
#define GPIO_I2C1_SCA_PIN_M_EINT  GPIO_MODE_02
#define GPIO_I2C1_SCA_PIN_M_PWM  GPIO_MODE_04
#define GPIO_I2C1_SCA_PIN_M_SCL   GPIO_MODE_01
#define GPIO_I2C1_SCA_PIN_CLK     CLK_OUT2
#define GPIO_I2C1_SCA_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_UART_URXD3_PIN         GPIO219
#define GPIO_UART_URXD3_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_UART_URXD3_PIN_M_EINT  GPIO_MODE_02
#define GPIO_UART_URXD3_PIN_M_PWM  GPIO_MODE_06
#define GPIO_UART_URXD3_PIN_M_URXD   GPIO_MODE_01

#define GPIO_COMBO_URXD_PIN         GPIO219
#define GPIO_COMBO_URXD_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_URXD_PIN_M_EINT  GPIO_MODE_02
#define GPIO_COMBO_URXD_PIN_M_PWM  GPIO_MODE_06
#define GPIO_COMBO_URXD_PIN_M_URXD   GPIO_MODE_01

#define GPIO_UART_UTXD3_PIN         GPIO220
#define GPIO_UART_UTXD3_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_UART_UTXD3_PIN_M_EINT  GPIO_MODE_02
#define GPIO_UART_UTXD3_PIN_M_PWM  GPIO_MODE_06
#define GPIO_UART_UTXD3_PIN_M_UTXD   GPIO_MODE_01

#define GPIO_COMBO_UTXD_PIN         GPIO220
#define GPIO_COMBO_UTXD_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_UTXD_PIN_M_EINT  GPIO_MODE_02
#define GPIO_COMBO_UTXD_PIN_M_PWM  GPIO_MODE_06
#define GPIO_COMBO_UTXD_PIN_M_UTXD   GPIO_MODE_01

#define GPIO_PCM_DAICLK_PIN         GPIO221
#define GPIO_PCM_DAICLK_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_PCM_DAICLK_PIN_M_CLK  GPIO_MODE_01
#define GPIO_PCM_DAICLK_PIN_M_I2SIN_CK   GPIO_MODE_03
#define GPIO_PCM_DAICLK_PIN_M_PCM0_CK   GPIO_MODE_04

#define GPIO_COMBO_I2S_CK_PIN         GPIO221
#define GPIO_COMBO_I2S_CK_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_I2S_CK_PIN_M_CLK  GPIO_MODE_01
#define GPIO_COMBO_I2S_CK_PIN_M_I2SIN_CK   GPIO_MODE_03
#define GPIO_COMBO_I2S_CK_PIN_M_PCM0_CK   GPIO_MODE_04

#define GPIO_PCM_DAISYNC_PIN         GPIO222
#define GPIO_PCM_DAISYNC_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_PCM_DAISYNC_PIN_M_EINT  GPIO_MODE_02
#define GPIO_PCM_DAISYNC_PIN_M_MRG_I2S_PCM_SYNC   GPIO_MODE_01
#define GPIO_PCM_DAISYNC_PIN_M_I2SIN_WS   GPIO_MODE_03
#define GPIO_PCM_DAISYNC_PIN_M_PCM0_WS   GPIO_MODE_04

#define GPIO_COMBO_I2S_WS_PIN         GPIO222
#define GPIO_COMBO_I2S_WS_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_I2S_WS_PIN_M_EINT  GPIO_MODE_02
#define GPIO_COMBO_I2S_WS_PIN_M_MRG_I2S_PCM_SYNC   GPIO_MODE_01
#define GPIO_COMBO_I2S_WS_PIN_M_I2SIN_WS   GPIO_MODE_03
#define GPIO_COMBO_I2S_WS_PIN_M_PCM0_WS   GPIO_MODE_04

#define GPIO_PCM_DAIPCMIN_PIN         GPIO223
#define GPIO_PCM_DAIPCMIN_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_PCM_DAIPCMIN_PIN_M_MRG_I2S_PCM_RX   GPIO_MODE_01
#define GPIO_PCM_DAIPCMIN_PIN_M_I2SIN_DAT   GPIO_MODE_03
#define GPIO_PCM_DAIPCMIN_PIN_M_PCM0_DI   GPIO_MODE_04

#define GPIO_COMBO_I2S_DAT_PIN         GPIO223
#define GPIO_COMBO_I2S_DAT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_I2S_DAT_PIN_M_MRG_I2S_PCM_RX   GPIO_MODE_01
#define GPIO_COMBO_I2S_DAT_PIN_M_I2SIN_DAT   GPIO_MODE_03
#define GPIO_COMBO_I2S_DAT_PIN_M_PCM0_DI   GPIO_MODE_04

#define GPIO_PCM_DAIPCMOUT_PIN         GPIO224
#define GPIO_PCM_DAIPCMOUT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_PCM_DAIPCMOUT_PIN_M_EINT  GPIO_MODE_02
#define GPIO_PCM_DAIPCMOUT_PIN_M_MRG_I2S_PCM_TX   GPIO_MODE_01
#define GPIO_PCM_DAIPCMOUT_PIN_M_I2SOUT_DAT   GPIO_MODE_03
#define GPIO_PCM_DAIPCMOUT_PIN_M_PCM0_DO   GPIO_MODE_04

#define GPIO_COMBO_RST_PIN         GPIO225
#define GPIO_COMBO_RST_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_RST_PIN_M_EINT  GPIO_MODE_02
#define GPIO_COMBO_RST_PIN_M_MD1_DAI_RX_GPIO   GPIO_MODE_01


/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */



#define GPIO_KPD_KCOL0_PIN         GPIOEXT16
#define GPIO_KPD_KCOL0_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_KPD_KCOL0_PIN_M_EINT  GPIO_MODE_02
#define GPIO_KPD_KCOL0_PIN_M_PWM  GPIO_MODE_03
#define GPIO_KPD_KCOL0_PIN_M_COL0_USBDL   GPIO_MODE_01

#define GPIO_EINI_CHG_STAT         GPIOEXT26
#define GPIO_EINI_CHG_STAT_M_GPIO  GPIO_MODE_00
#define GPIO_EINI_CHG_STAT_M_EINT  GPIO_MODE_02

#define GPIO_IRQ_NFC         GPIOEXT27
#define GPIO_IRQ_NFC_M_GPIO  GPIO_MODE_00
#define GPIO_IRQ_NFC_M_EINT  GPIO_MODE_02

#define GPIO_NFC_RST         GPIOEXT28
#define GPIO_NFC_RST_M_GPIO  GPIO_MODE_00
#define GPIO_NFC_RST_M_EINT  GPIO_MODE_02

#define GPIO_NFC_VEN_PIN         GPIOEXT29
#define GPIO_NFC_VEN_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_NFC_VEN_PIN_M_EINT  GPIO_MODE_02

#define GPIO_LCD_ID1         GPIOEXT30
#define GPIO_LCD_ID1_M_GPIO  GPIO_MODE_00
#define GPIO_LCD_ID1_M_EINT  GPIO_MODE_02
#define GPIO_LCD_ID1_M_PWM  GPIO_MODE_03

#define GPIO_NFC_EINT_PIN         GPIOEXT31
#define GPIO_NFC_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_NFC_EINT_PIN_M_EINT  GPIO_MODE_02


/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */



#endif /* __CUST_GPIO_USAGE_H__ */



