#ifndef _MT6320_PMIC_COMMON_H_
#define _MT6320_PMIC_COMMON_H_

#include <mach/mt_typedefs.h>

extern U32 upmu_get_rgs_vcdt_hv_det(void);
extern U32 upmu_get_rgs_vcdt_lv_det(void);
extern U32 upmu_get_rgs_chrdet(void);
extern void upmu_set_rg_chr_en(U32 val);
extern void upmu_set_rg_csdac_en(U32 val);
extern void upmu_set_rg_pchr_automode(U32 val);
extern U32 upmu_get_rgs_chr_ldo_det(void);
extern void upmu_set_rg_vcdt_hv_en(U32 val);
extern void upmu_set_rg_vcdt_hv_vth(U32 val);
extern void upmu_set_rg_vcdt_lv_vth(U32 val);
extern U32 upmu_get_rgs_vbat_cc_det(void);
extern U32 upmu_get_rgs_vbat_cv_det(void);
extern U32 upmu_get_rgs_cs_det(void);
extern void upmu_set_rg_cs_en(U32 val);
extern void upmu_set_rg_vbat_cc_en(U32 val);
extern void upmu_set_rg_vbat_cv_en(U32 val);
extern void upmu_set_rg_vbat_cc_vth(U32 val);
extern void upmu_set_rg_vbat_cv_vth(U32 val);
extern void upmu_set_rg_cs_vth(U32 val);
extern void upmu_set_rg_pchr_toltc(U32 val);
extern void upmu_set_rg_pchr_tohtc(U32 val);
extern U32 upmu_get_rgs_vbat_ov_det(void);
extern void upmu_set_rg_vbat_ov_deg(U32 val);
extern void upmu_set_rg_vbat_ov_vth(U32 val);
extern void upmu_set_rg_vbat_ov_en(U32 val);
extern U32 upmu_get_rgs_baton_undet(void);
extern void upmu_set_rg_baton_ht_trim_set(U32 val);
extern void upmu_set_rg_baton_ht_trim(U32 val);
extern void upmu_set_baton_tdet_en(U32 val);
extern void upmu_set_rg_baton_ht_en(U32 val);
extern void upmu_set_rg_baton_en(U32 val);
extern void upmu_set_rg_csdac_data(U32 val);
extern void upmu_set_rg_frc_csvth_usbdl(U32 val);
extern U32 upmu_get_rgs_otg_bvalid_det(void);
extern void upmu_set_rg_otg_bvalid_en(U32 val);
extern void upmu_set_rg_pchr_flag_en(U32 val);
extern U32 upmu_get_rgs_pchr_flag_out(void);
extern void upmu_set_rg_pchr_flag_sel(U32 val);
extern void upmu_set_rg_pchr_ft_ctrl(U32 val);
extern void upmu_set_rg_pchr_rst(U32 val);
extern void upmu_set_rg_csdac_testmode(U32 val);
extern void upmu_set_rg_pchr_testmode(U32 val);
extern void upmu_set_rg_chrwdt_wr(U32 val);
extern void upmu_set_rg_chrwdt_en(U32 val);
extern void upmu_set_rg_chrwdt_td(U32 val);
extern void upmu_set_rg_pchr_rv(U32 val);
extern U32 upmu_get_rgs_chrwdt_out(void);
extern void upmu_set_rg_chrwdt_flag_wr(U32 val);
extern void upmu_set_rg_chrwdt_int_en(U32 val);
extern void upmu_set_adcin_vchr_en(U32 val);
extern void upmu_set_adcin_vsen_en(U32 val);
extern void upmu_set_adcin_vbat_en(U32 val);
extern void upmu_set_rg_adcin_vsen_ext_baton_en(U32 val);
extern void upmu_set_adcin_vsen_mux_en(U32 val);
extern void upmu_set_rg_usbdl_set(U32 val);
extern void upmu_set_rg_usbdl_rst(U32 val);
extern void upmu_set_rg_uvlo_vthl(U32 val);
extern void upmu_set_rg_bgr_unchop(U32 val);
extern void upmu_set_rg_bgr_unchop_ph(U32 val);
extern void upmu_set_rg_bgr_rsel(U32 val);
extern U32 upmu_get_rgs_bc11_cmp_out(void);
extern void upmu_set_rg_bc11_vsrc_en(U32 val);
extern void upmu_set_rg_bc11_rst(U32 val);
extern void upmu_set_rg_bc11_bb_ctrl(U32 val);
extern void upmu_set_rg_bc11_bias_en(U32 val);
extern void upmu_set_rg_bc11_ipu_en(U32 val);
extern void upmu_set_rg_bc11_ipd_en(U32 val);
extern void upmu_set_rg_bc11_cmp_en(U32 val);
extern void upmu_set_rg_bc11_vref_vth(U32 val);
extern void upmu_set_rg_csdac_stp_dec(U32 val);
extern void upmu_set_rg_csdac_stp_inc(U32 val);
extern void upmu_set_rg_csdac_stp(U32 val);
extern void upmu_set_rg_csdac_dly(U32 val);
extern void upmu_set_rg_chrind_dimming(U32 val);
extern void upmu_set_rg_chrind_on(U32 val);
extern void upmu_set_rg_low_ich_db(U32 val);
extern void upmu_set_rg_ulc_det_en(U32 val);
extern void upmu_set_rg_hwcv_en(U32 val);
extern void upmu_set_rg_tracking_en(U32 val);
extern void upmu_set_rg_csdac_mode(U32 val);
extern void upmu_set_rg_vcdt_mode(U32 val);
extern void upmu_set_rg_cv_mode(U32 val);
extern void upmu_set_rg_ichrg_trim(U32 val);
extern void upmu_set_rg_bgr_trim_en(U32 val);
extern void upmu_set_rg_bgr_trim(U32 val);
extern void upmu_set_rg_ovp_trim(U32 val);
extern void upmu_set_rg_bgr_test_rstb(U32 val);
extern void upmu_set_rg_bgr_test_en(U32 val);
extern void upmu_set_qi_bgr_ext_buf_en(U32 val);
extern void upmu_set_chr_osc_trim(U32 val);
extern void upmu_set_rg_dac_usbdl_max(U32 val);
extern void upmu_set_rg_pchr_rsv(U32 val);
extern U32 upmu_get_cid(void);
extern void upmu_set_rg_strup_6m_pdn(U32 val);
extern void upmu_set_rg_accdet_ck_pdn(U32 val);
extern void upmu_set_rg_auxadc_ck_pdn(U32 val);
extern void upmu_set_rg_smps_ck_div_pdn(U32 val);
extern void upmu_set_rg_smps_ck_div2_pdn(U32 val);
extern void upmu_set_rg_spk_div_pdn(U32 val);
extern void upmu_set_rg_spk_pwm_div_pdn(U32 val);
extern void upmu_set_rg_rtc_mclk_pdn(U32 val);
extern void upmu_set_rg_bst_drv_1m_ck_pdn(U32 val);
extern void upmu_set_rg_fgadc_ana_ck_pdn(U32 val);
extern void upmu_set_rg_fgadc_ck_pdn(U32 val);
extern void upmu_set_rg_efuse_ck_pdn(U32 val);
extern void upmu_set_rg_pwmoc_ck_pdn(U32 val);
extern void upmu_set_rg_spk_ck_pdn(U32 val);
extern void upmu_set_rg_aud_13m_pdn(U32 val);
extern void upmu_set_rg_aud_26m_pdn(U32 val);
extern void upmu_set_rg_top_ckpdn2_rsv_15(U32 val);
extern void upmu_set_rg_rtc_75k_ck_pdn(U32 val);
extern void upmu_set_rg_strup_32k_ck_pdn(U32 val);
extern void upmu_set_rg_buck_1m_ck_pdn(U32 val);
extern void upmu_set_rg_buck32k_pdn(U32 val);
extern void upmu_set_rg_buck_ana_ck_pdn(U32 val);
extern void upmu_set_rg_buck_ck_pdn(U32 val);
extern void upmu_set_rg_chr1m_ck_pdn(U32 val);
extern void upmu_set_rg_drv_32k_ck_pdn(U32 val);
extern void upmu_set_rg_intrp_ck_pdn(U32 val);
extern void upmu_set_rg_ldostb_1m_ck_pdn(U32 val);
extern void upmu_set_rg_pchr_32k_ck_pdn(U32 val);
extern void upmu_set_rg_rtc_32k_ck_pdn(U32 val);
extern void upmu_set_rg_strup_75k_ck_pdn(U32 val);
extern void upmu_set_rg_fqmtr_pdn(U32 val);
extern void upmu_set_rg_rtc32k_1v8_pdn(U32 val);
extern void upmu_set_rg_top_gpio_ckpdn_rsv_15_14(U32 val);
extern void upmu_set_rg_gpio32k_pdn(U32 val);
extern void upmu_set_rg_gpio26m_pdn(U32 val);
extern void upmu_set_rg_top_rst_con_rsv_15_9(U32 val);
extern void upmu_set_rg_fqmtr_rst(U32 val);
extern void upmu_set_rg_rtc_rst(U32 val);
extern void upmu_set_rg_driver_rst(U32 val);
extern void upmu_set_rg_spk_rst(U32 val);
extern void upmu_set_rg_accdet_rst(U32 val);
extern void upmu_set_rg_fgadc_rst(U32 val);
extern void upmu_set_rg_audio_rst(U32 val);
extern void upmu_set_rg_auxadc_rst(U32 val);
extern void upmu_set_rg_efuse_man_rst(U32 val);
extern void upmu_set_rg_wrp_pdn(U32 val);
extern void upmu_set_rg_wrp_32k_pdn(U32 val);
extern void upmu_set_rg_wrp_eint_pdn(U32 val);
extern void upmu_set_rg_wrp_kp_pdn(U32 val);
extern void upmu_set_rg_wrp_pwm_pdn(U32 val);
extern void upmu_set_rg_wrp_i2c2_pdn(U32 val);
extern void upmu_set_rg_wrp_i2c1_pdn(U32 val);
extern void upmu_set_rg_wrp_i2c0_pdn(U32 val);
extern void upmu_set_rg_wrp_rst(U32 val);
extern void upmu_set_rg_eint_rst(U32 val);
extern void upmu_set_rg_kp_rst(U32 val);
extern void upmu_set_rg_pwm_rst(U32 val);
extern void upmu_set_rg_i2c2_rst(U32 val);
extern void upmu_set_rg_i2c1_rst(U32 val);
extern void upmu_set_rg_i2c0_rst(U32 val);
extern void upmu_set_rg_pwrkey_rst_td(U32 val);
extern void upmu_set_rg_pwrrst_tmr_dis(U32 val);
extern void upmu_set_rg_pwrkey_rst_en(U32 val);
extern void upmu_set_rg_homekey_rst_en(U32 val);
extern void upmu_set_rg_rst_part_sel(U32 val);
extern void upmu_set_rg_top_rst_misc_rsv_3(U32 val);
extern void upmu_set_rg_strup_man_rst_en(U32 val);
extern void upmu_set_rg_sysrstb_en(U32 val);
extern void upmu_set_rg_ap_rst_dis(U32 val);
extern void upmu_set_rg_osc_sel_align_dis(U32 val);
extern void upmu_set_rg_spitxck_inv_sel(U32 val);
extern void upmu_set_rg_osc_hw_sel(U32 val);
extern void upmu_set_rg_clksq_hw_auto_en(U32 val);
extern void upmu_set_rg_srclkperi_hw_auto_en(U32 val);
extern void upmu_set_rg_srclkmd2_hw_auto_en(U32 val);
extern void upmu_set_rg_srcvolt_hw_auto_en(U32 val);
extern void upmu_set_rg_osc_sel_auto(U32 val);
extern void upmu_set_rg_top_ckcon1_rsv_07(U32 val);
extern void upmu_set_rg_smps_div2_src_autoff_dis(U32 val);
extern void upmu_set_rg_smps_autoff_dis(U32 val);
extern void upmu_set_rg_clksq_en(U32 val);
extern void upmu_set_rg_srclkperi_en(U32 val);
extern void upmu_set_rg_srclkmd2_en(U32 val);
extern void upmu_set_rg_srcvolt_en(U32 val);
extern void upmu_set_rg_osc_sel(U32 val);
extern void upmu_set_rg_fqmtr_cksel(U32 val);
extern void upmu_set_rg_accdet_cksel(U32 val);
extern void upmu_set_rg_fg_ana_cksel(U32 val);
extern void upmu_set_rg_regck_sel(U32 val);
extern void upmu_set_rg_buck_2m_sel_en(U32 val);
extern void upmu_set_vproc_6m_sel(U32 val);
extern void upmu_set_vcore_6m_sel(U32 val);
extern void upmu_set_rg_spk_div_sel(U32 val);
extern void upmu_set_rg_spk_pwm_div_sel(U32 val);
extern void upmu_set_rg_auxadc_div_sel(U32 val);
extern void upmu_set_auxadc_tstsel(U32 val);
extern void upmu_set_pmu75k_tst_dis(U32 val);
extern void upmu_set_smps_tst_dis(U32 val);
extern void upmu_set_chr1m_tst_dis(U32 val);
extern void upmu_set_aud26m_tst_dis(U32 val);
extern void upmu_set_rtc32k_tst_dis(U32 val);
extern void upmu_set_fg_tst_dis(U32 val);
extern void upmu_set_spk_tst_dis(U32 val);
extern void upmu_set_chr1m_tstsel(U32 val);
extern void upmu_set_smps_tstsel(U32 val);
extern void upmu_set_pmu75k_tstsel(U32 val);
extern void upmu_set_aud26m_tstsel(U32 val);
extern void upmu_set_rtc32k_tstsel(U32 val);
extern void upmu_set_fg_tstsel(U32 val);
extern void upmu_set_spk_tstsel(U32 val);
extern void upmu_set_rg_top_cktst2_rsv_15_8(U32 val);
extern void upmu_set_osc32_cksel(U32 val);
extern void upmu_set_xosc32_tstsel(U32 val);
extern void upmu_set_xosc32_tst_dis(U32 val);
extern void upmu_set_rg_pchr_test_ck_sel(U32 val);
extern void upmu_set_rg_strup_75k_26m_sel(U32 val);
extern void upmu_set_accdet_tstsel(U32 val);
extern void upmu_set_ck1m2m_tstsel(U32 val);
extern void upmu_set_bgr_test_ck_en(U32 val);
extern void upmu_set_vrf18_2_deg_en(U32 val);
extern void upmu_set_vrf18_deg_en(U32 val);
extern void upmu_set_vpa_deg_en(U32 val);
extern void upmu_set_vio18_deg_en(U32 val);
extern void upmu_set_vm_deg_en(U32 val);
extern void upmu_set_vcore_deg_en(U32 val);
extern void upmu_set_vsram_deg_en(U32 val);
extern void upmu_set_vproc_deg_en(U32 val);
extern void upmu_set_oc_gear_bvalid_det(U32 val);
extern void upmu_set_oc_gear_vbaton_undet(U32 val);
extern void upmu_set_oc_gear_ldo(U32 val);
extern void upmu_set_vm_oc_wnd(U32 val);
extern void upmu_set_vm_oc_thd(U32 val);
extern void upmu_set_vcore_oc_wnd(U32 val);
extern void upmu_set_vcore_oc_thd(U32 val);
extern void upmu_set_vsram_oc_wnd(U32 val);
extern void upmu_set_vsram_oc_thd(U32 val);
extern void upmu_set_vproc_oc_wnd(U32 val);
extern void upmu_set_vproc_oc_thd(U32 val);
extern void upmu_set_vrf18_2_oc_wnd(U32 val);
extern void upmu_set_vrf18_2_oc_thd(U32 val);
extern void upmu_set_vrf18_oc_wnd(U32 val);
extern void upmu_set_vrf18_oc_thd(U32 val);
extern void upmu_set_vpa_oc_wnd(U32 val);
extern void upmu_set_vpa_oc_thd(U32 val);
extern void upmu_set_vio18_oc_wnd(U32 val);
extern void upmu_set_vio18_oc_thd(U32 val);
extern void upmu_set_int_rsv_15_8(U32 val);
extern void upmu_set_ivgen_ext_en(U32 val);
extern void upmu_set_rg_pwrkey_int_sel(U32 val);
extern void upmu_set_rg_homekey_int_sel(U32 val);
extern void upmu_set_polarity_bvalid_det(U32 val);
extern void upmu_set_polarity_vbaton_undet(U32 val);
extern void upmu_set_polarity(U32 val);
extern void upmu_set_rg_mon_grp_sel(U32 val);
extern void upmu_set_rg_mon_flag_sel(U32 val);
extern void upmu_set_rg_test_spk_pwm(U32 val);
extern void upmu_set_rg_test_spk(U32 val);
extern void upmu_set_rg_test_strup(U32 val);
extern void upmu_set_rg_efuse_mode(U32 val);
extern void upmu_set_rg_nandtree_mode(U32 val);
extern void upmu_set_rg_test_auxadc(U32 val);
extern void upmu_set_rg_test_fgpll(U32 val);
extern void upmu_set_rg_test_fg(U32 val);
extern void upmu_set_rg_test_aud(U32 val);
extern void upmu_set_rg_test_wrap(U32 val);
extern void upmu_set_rg_test_io_fg_sel(U32 val);
extern void upmu_set_rg_test_classd(U32 val);
extern void upmu_set_rg_test_driver(U32 val);
extern void upmu_set_rg_test_boost(U32 val);
extern U32 upmu_get_vrtc_status(void);
extern U32 upmu_get_status_vrf28_2_en(void);
extern U32 upmu_get_status_vrf28_en(void);
extern U32 upmu_get_status_vsim1_en(void);
extern U32 upmu_get_status_vsim2_en(void);
extern U32 upmu_get_status_vtcxo_2_en(void);
extern U32 upmu_get_status_vtcxo_en(void);
extern U32 upmu_get_status_vusb_en(void);
extern U32 upmu_get_status_vrf18_2_en(void);
extern U32 upmu_get_status_vrf18_en(void);
extern U32 upmu_get_status_vpa_en(void);
extern U32 upmu_get_status_vio18_en(void);
extern U32 upmu_get_status_vm_en(void);
extern U32 upmu_get_status_vcore_en(void);
extern U32 upmu_get_status_vsram_en(void);
extern U32 upmu_get_status_vproc_en(void);
extern U32 upmu_get_status_va28_en(void);
extern U32 upmu_get_status_vast_en(void);
extern U32 upmu_get_status_va_en(void);
extern U32 upmu_get_status_vcama_en(void);
extern U32 upmu_get_status_vemc_1v8_en(void);
extern U32 upmu_get_status_vemc_3v3_en(void);
extern U32 upmu_get_status_vgp1_en(void);
extern U32 upmu_get_status_vgp2_en(void);
extern U32 upmu_get_status_vgp3_en(void);
extern U32 upmu_get_status_vgp4_en(void);
extern U32 upmu_get_status_vgp5_en(void);
extern U32 upmu_get_status_vgp6_en(void);
extern U32 upmu_get_status_vibr_en(void);
extern U32 upmu_get_status_vio28_en(void);
extern U32 upmu_get_status_vmc1_en(void);
extern U32 upmu_get_status_vmch1_en(void);
extern U32 upmu_get_vio28_pg_deb(void);
extern U32 upmu_get_va28_pg_deb(void);
extern U32 upmu_get_va_pg_deb(void);
extern U32 upmu_get_vtcxo_pg_deb(void);
extern U32 upmu_get_vio18_pg_deb(void);
extern U32 upmu_get_vm_pg_deb(void);
extern U32 upmu_get_vcore_pg_deb(void);
extern U32 upmu_get_vsram_pg_deb(void);
extern U32 upmu_get_vproc_pg_deb(void);
extern void upmu_set_rtc_xtal_det_rsv(U32 val);
extern U32 upmu_get_rtc_xtal_det_done(void);
extern U32 upmu_get_ro_baton_undet(void);
extern U32 upmu_get_pchr_chrdet(void);
extern U32 upmu_get_vbat_ov(void);
extern U32 upmu_get_pwrkey_deb(void);
extern U32 upmu_get_usbdl(void);
extern U32 upmu_get_pmu_test_mode_scan(void);
extern U32 upmu_get_oc_status_vrf28_2(void);
extern U32 upmu_get_oc_status_vrf28(void);
extern U32 upmu_get_oc_status_vsim1(void);
extern U32 upmu_get_oc_status_vsim2(void);
extern U32 upmu_get_oc_status_vtcxo_2(void);
extern U32 upmu_get_oc_status_vtcxo(void);
extern U32 upmu_get_oc_status_vusb(void);
extern U32 upmu_get_oc_status_vrf18_2(void);
extern U32 upmu_get_oc_status_vrf18(void);
extern U32 upmu_get_oc_status_vpa(void);
extern U32 upmu_get_oc_status_vio18(void);
extern U32 upmu_get_oc_status_vm(void);
extern U32 upmu_get_oc_status_vcore(void);
extern U32 upmu_get_oc_status_vsram(void);
extern U32 upmu_get_oc_status_vproc(void);
extern U32 upmu_get_oc_status_va28(void);
extern U32 upmu_get_oc_status_vast(void);
extern U32 upmu_get_oc_status_va(void);
extern U32 upmu_get_oc_status_vcama(void);
extern U32 upmu_get_oc_status_vemc_1v8(void);
extern U32 upmu_get_oc_status_vemc_3v3(void);
extern U32 upmu_get_oc_status_vgp1(void);
extern U32 upmu_get_oc_status_vgp2(void);
extern U32 upmu_get_oc_status_vgp3(void);
extern U32 upmu_get_oc_status_vgp4(void);
extern U32 upmu_get_oc_status_vgp5(void);
extern U32 upmu_get_oc_status_vgp6(void);
extern U32 upmu_get_oc_status_vibr(void);
extern U32 upmu_get_oc_status_vio28(void);
extern U32 upmu_get_oc_status_vmc1(void);
extern U32 upmu_get_oc_status_vmch1(void);
extern U32 upmu_get_homekey_deb(void);
extern U32 upmu_get_ni_spk_oc_det_d_r(void);
extern U32 upmu_get_ni_spk_oc_det_d_l(void);
extern U32 upmu_get_ni_spk_oc_det_ab_r(void);
extern U32 upmu_get_ni_spk_oc_det_ab_l(void);
extern void upmu_set_rg_simls2_srst_conf(U32 val);
extern void upmu_set_rg_simls2_sclk_conf(U32 val);
extern void upmu_set_rg_simls1_srst_conf(U32 val);
extern void upmu_set_rg_simls1_sclk_conf(U32 val);
extern U32 upmu_get_test_out_l(void);
extern U32 upmu_get_test_out_h(void);
extern void upmu_set_rg_simls_tdsel(U32 val);
extern void upmu_set_rg_pmu_tdsel(U32 val);
extern void upmu_set_rg_spi_tdsel(U32 val);
extern void upmu_set_rg_i2s_tdsel(U32 val);
extern void upmu_set_rg_kp_tdsel(U32 val);
extern void upmu_set_rg_pwm_tdsel(U32 val);
extern void upmu_set_rg_i2c_tdsel(U32 val);
extern void upmu_set_rg_simap_tdsel(U32 val);
extern void upmu_set_rg_simls_rdsel(U32 val);
extern void upmu_set_rg_pmu_rdsel(U32 val);
extern void upmu_set_rg_spi_rdsel(U32 val);
extern void upmu_set_rg_i2s_rdsel(U32 val);
extern void upmu_set_rg_kp_rdsel(U32 val);
extern void upmu_set_rg_pwm_rdsel(U32 val);
extern void upmu_set_rg_i2c_rdsel(U32 val);
extern void upmu_set_rg_simap_rdsel(U32 val);
extern void upmu_set_rg_smt15(U32 val);
extern void upmu_set_rg_smt14(U32 val);
extern void upmu_set_rg_smt13(U32 val);
extern void upmu_set_rg_smt12(U32 val);
extern void upmu_set_rg_smt11(U32 val);
extern void upmu_set_rg_smt10(U32 val);
extern void upmu_set_rg_smt9(U32 val);
extern void upmu_set_rg_smt8(U32 val);
extern void upmu_set_rg_smt7(U32 val);
extern void upmu_set_rg_smt6(U32 val);
extern void upmu_set_rg_smt5(U32 val);
extern void upmu_set_rg_smt4(U32 val);
extern void upmu_set_rg_smt3(U32 val);
extern void upmu_set_rg_smt2(U32 val);
extern void upmu_set_rg_smt1(U32 val);
extern void upmu_set_rg_smt0(U32 val);
extern void upmu_set_rg_smt31(U32 val);
extern void upmu_set_rg_smt30(U32 val);
extern void upmu_set_rg_smt29(U32 val);
extern void upmu_set_rg_smt28(U32 val);
extern void upmu_set_rg_smt27(U32 val);
extern void upmu_set_rg_smt26(U32 val);
extern void upmu_set_rg_smt25(U32 val);
extern void upmu_set_rg_smt24(U32 val);
extern void upmu_set_rg_smt23(U32 val);
extern void upmu_set_rg_smt22(U32 val);
extern void upmu_set_rg_smt21(U32 val);
extern void upmu_set_rg_smt20(U32 val);
extern void upmu_set_rg_smt19(U32 val);
extern void upmu_set_rg_smt18(U32 val);
extern void upmu_set_rg_smt17(U32 val);
extern void upmu_set_rg_smt16(U32 val);
extern void upmu_set_rg_smt47(U32 val);
extern void upmu_set_rg_smt46(U32 val);
extern void upmu_set_rg_smt45(U32 val);
extern void upmu_set_rg_smt44(U32 val);
extern void upmu_set_rg_smt43(U32 val);
extern void upmu_set_rg_smt42(U32 val);
extern void upmu_set_rg_smt41(U32 val);
extern void upmu_set_rg_smt40(U32 val);
extern void upmu_set_rg_smt39(U32 val);
extern void upmu_set_rg_smt38(U32 val);
extern void upmu_set_rg_smt37(U32 val);
extern void upmu_set_rg_smt36(U32 val);
extern void upmu_set_rg_smt35(U32 val);
extern void upmu_set_rg_smt34(U32 val);
extern void upmu_set_rg_smt33(U32 val);
extern void upmu_set_rg_smt32(U32 val);
extern void upmu_set_rg_homekey_pden(U32 val);
extern void upmu_set_rg_homekey_puen(U32 val);
extern void upmu_set_rg_smt50(U32 val);
extern void upmu_set_rg_smt49(U32 val);
extern void upmu_set_rg_smt48(U32 val);
extern void upmu_set_rg_octl_srclken_peri(U32 val);
extern void upmu_set_rg_octl_srcvolten(U32 val);
extern void upmu_set_rg_octl_int(U32 val);
extern void upmu_set_rg_octl_homekey(U32 val);
extern void upmu_set_rg_octl_spi_clk(U32 val);
extern void upmu_set_rg_octl_wrap_event(U32 val);
extern void upmu_set_rg_octl_rtc_32k1v8(U32 val);
extern void upmu_set_rg_octl_srclken_md2(U32 val);
extern void upmu_set_rg_octl_adc_ck(U32 val);
extern void upmu_set_rg_octl_spi_miso(U32 val);
extern void upmu_set_rg_octl_spi_mosi(U32 val);
extern void upmu_set_rg_octl_spi_csn(U32 val);
extern void upmu_set_rg_octl_dac_ws(U32 val);
extern void upmu_set_rg_octl_dac_ck(U32 val);
extern void upmu_set_rg_octl_adc_dat(U32 val);
extern void upmu_set_rg_octl_adc_ws(U32 val);
extern void upmu_set_rg_octl_col2(U32 val);
extern void upmu_set_rg_octl_col1(U32 val);
extern void upmu_set_rg_octl_col0(U32 val);
extern void upmu_set_rg_octl_dac_dat(U32 val);
extern void upmu_set_rg_octl_col6(U32 val);
extern void upmu_set_rg_octl_col5(U32 val);
extern void upmu_set_rg_octl_col4(U32 val);
extern void upmu_set_rg_octl_col3(U32 val);
extern void upmu_set_rg_octl_row2(U32 val);
extern void upmu_set_rg_octl_row1(U32 val);
extern void upmu_set_rg_octl_row0(U32 val);
extern void upmu_set_rg_octl_col7(U32 val);
extern void upmu_set_rg_octl_row6(U32 val);
extern void upmu_set_rg_octl_row5(U32 val);
extern void upmu_set_rg_octl_row4(U32 val);
extern void upmu_set_rg_octl_row3(U32 val);
extern void upmu_set_rg_octl_pwm(U32 val);
extern void upmu_set_rg_octl_vmsel2(U32 val);
extern void upmu_set_rg_octl_vmsel1(U32 val);
extern void upmu_set_rg_octl_row7(U32 val);
extern void upmu_set_rg_octl_sda1(U32 val);
extern void upmu_set_rg_octl_scl1(U32 val);
extern void upmu_set_rg_octl_sda0(U32 val);
extern void upmu_set_rg_octl_scl0(U32 val);
extern void upmu_set_rg_octl_sim1_ap_srst(U32 val);
extern void upmu_set_rg_octl_sim1_ap_sclk(U32 val);
extern void upmu_set_rg_octl_sda2(U32 val);
extern void upmu_set_rg_octl_scl2(U32 val);
extern void upmu_set_rg_octl_simls1_srst(U32 val);
extern void upmu_set_rg_octl_simls1_sclk(U32 val);
extern void upmu_set_rg_octl_sim2_ap_srst(U32 val);
extern void upmu_set_rg_octl_sim2_ap_sclk(U32 val);
extern void upmu_set_rg_octl_simls2_srst(U32 val);
extern void upmu_set_rg_octl_simls2_sclk(U32 val);
extern void upmu_set_rg_int_en_ov(U32 val);
extern void upmu_set_rg_int_en_chrdet(U32 val);
extern void upmu_set_rg_int_en_bvalid_det(U32 val);
extern void upmu_set_rg_int_en_vbaton_undet(U32 val);
extern void upmu_set_rg_int_en_thr_h(U32 val);
extern void upmu_set_rg_int_en_thr_l(U32 val);
extern void upmu_set_rg_int_en_pwrkey(U32 val);
extern void upmu_set_rg_int_en_watchdog(U32 val);
extern void upmu_set_rg_int_en_fg_bat_h(U32 val);
extern void upmu_set_rg_int_en_fg_bat_l(U32 val);
extern void upmu_set_rg_int_en_bat_h(U32 val);
extern void upmu_set_rg_int_en_bat_l(U32 val);
extern void upmu_set_rg_int_en_spkr(U32 val);
extern void upmu_set_rg_int_en_spkl(U32 val);
extern void upmu_set_rg_int_en_spkr_ab(U32 val);
extern void upmu_set_rg_int_en_spkl_ab(U32 val);
extern void upmu_set_rg_int_en_vrf18_2(U32 val);
extern void upmu_set_rg_int_en_vrf18(U32 val);
extern void upmu_set_rg_int_en_vpa(U32 val);
extern void upmu_set_rg_int_en_vio18(U32 val);
extern void upmu_set_rg_int_en_vm(U32 val);
extern void upmu_set_rg_int_en_vcore(U32 val);
extern void upmu_set_rg_int_en_vsram(U32 val);
extern void upmu_set_rg_int_en_vproc(U32 val);
extern void upmu_set_rg_int_en_rtc(U32 val);
extern void upmu_set_rg_int_en_audio(U32 val);
extern void upmu_set_rg_int_en_accdet(U32 val);
extern void upmu_set_rg_int_en_homekey(U32 val);
extern void upmu_set_rg_int_en_ldo(U32 val);
extern U32 upmu_get_rg_int_status_ov(void);
extern U32 upmu_get_rg_int_status_chrdet(void);
extern U32 upmu_get_rg_int_status_bvalid_det(void);
extern U32 upmu_get_rg_int_status_vbaton_undet(void);
extern U32 upmu_get_rg_int_status_thr_h(void);
extern U32 upmu_get_rg_int_status_thr_l(void);
extern U32 upmu_get_rg_int_status_pwrkey(void);
extern U32 upmu_get_rg_int_status_watchdog(void);
extern U32 upmu_get_rg_int_status_fg_bat_h(void);
extern U32 upmu_get_rg_int_status_fg_bat_l(void);
extern U32 upmu_get_rg_int_status_bat_h(void);
extern U32 upmu_get_rg_int_status_bat_l(void);
extern U32 upmu_get_rg_int_status_spkr(void);
extern U32 upmu_get_rg_int_status_spkl(void);
extern U32 upmu_get_rg_int_status_spkr_ab(void);
extern U32 upmu_get_rg_int_status_spkl_ab(void);
extern U32 upmu_get_rg_int_status_vrf18_2(void);
extern U32 upmu_get_rg_int_status_vrf18(void);
extern U32 upmu_get_rg_int_status_vpa(void);
extern U32 upmu_get_rg_int_status_vio18(void);
extern U32 upmu_get_rg_int_status_vm(void);
extern U32 upmu_get_rg_int_status_vcore(void);
extern U32 upmu_get_rg_int_status_vsram(void);
extern U32 upmu_get_rg_int_status_vproc(void);
extern U32 upmu_get_rg_int_status_rtc(void);
extern U32 upmu_get_rg_int_status_audio(void);
extern U32 upmu_get_rg_int_status_accdet(void);
extern U32 upmu_get_rg_int_status_homekey(void);
extern U32 upmu_get_rg_int_status_ldo(void);
extern void upmu_set_fqmtr_en(U32 val);
extern void upmu_set_fqmtr_rst(U32 val);
extern U32 upmu_get_fqmtr_busy(void);
extern void upmu_set_fqmtr_tcksel(U32 val);
extern void upmu_set_fqmtr_winset(U32 val);
extern U32 upmu_get_fqmtr_data(void);
extern void upmu_set_rg_efuse_addr(U32 val);
extern void upmu_set_rg_efuse_prog(U32 val);
extern void upmu_set_rg_efuse_en(U32 val);
extern void upmu_set_rg_efuse_pkey(U32 val);
extern void upmu_set_rg_efuse_rd_trig(U32 val);
extern void upmu_set_rg_rd_rdy_bypass(U32 val);
extern void upmu_set_rg_skip_efuse_out(U32 val);
extern void upmu_set_rg_efuse_prog_src(U32 val);
extern U32 upmu_get_rg_efuse_busy(void);
extern U32 upmu_get_rg_efuse_rd_ack(void);
extern void upmu_set_rg_efuse_val_0_15(U32 val);
extern void upmu_set_rg_efuse_val_16_31(U32 val);
extern void upmu_set_rg_efuse_val_32_47(U32 val);
extern void upmu_set_rg_efuse_val_48_63(U32 val);
extern void upmu_set_rg_efuse_val_64_79(U32 val);
extern void upmu_set_rg_efuse_val_80_95(U32 val);
extern void upmu_set_rg_efuse_val_96_111(U32 val);
extern void upmu_set_rg_efuse_val_112_127(U32 val);
extern void upmu_set_rg_efuse_val_128_143(U32 val);
extern void upmu_set_rg_efuse_val_144_159(U32 val);
extern void upmu_set_rg_efuse_val_160_175(U32 val);
extern void upmu_set_rg_efuse_val_176_191(U32 val);
extern U32 upmu_get_rg_efuse_dout_0_15(void);
extern U32 upmu_get_rg_efuse_dout_16_31(void);
extern U32 upmu_get_rg_efuse_dout_32_47(void);
extern U32 upmu_get_rg_efuse_dout_48_63(void);
extern U32 upmu_get_rg_efuse_dout_64_79(void);
extern U32 upmu_get_rg_efuse_dout_80_95(void);
extern U32 upmu_get_rg_efuse_dout_96_111(void);
extern U32 upmu_get_rg_efuse_dout_112_127(void);
extern U32 upmu_get_rg_efuse_dout_128_143(void);
extern U32 upmu_get_rg_efuse_dout_144_159(void);
extern U32 upmu_get_rg_efuse_dout_160_175(void);
extern U32 upmu_get_rg_efuse_dout_176_191(void);
extern void upmu_set_spi_con(U32 val);
extern void upmu_set_rg_smps_testmode_b(U32 val);
extern void upmu_set_rg_smps_testmode_a(U32 val);
extern U32 upmu_get_qi_vm_dig_mon(void);
extern U32 upmu_get_qi_vcore_dig_mon(void);
extern U32 upmu_get_qi_vsram_dig_mon(void);
extern U32 upmu_get_qi_vproc_dig_mon(void);
extern void upmu_set_buck_rsv(U32 val);
extern void upmu_set_vcore_pg_h2l_en(U32 val);
extern void upmu_set_vsram_pg_h2l_en(U32 val);
extern void upmu_set_vproc_pg_h2l_en(U32 val);
extern void upmu_set_rg_vproc_trimh(U32 val);
extern void upmu_set_rg_vproc_triml(U32 val);
extern void upmu_set_rg_vproc_zx_os(U32 val);
extern void upmu_set_rg_vproc_csl(U32 val);
extern void upmu_set_rg_vproc_csr(U32 val);
extern void upmu_set_rg_vproc_cc(U32 val);
extern void upmu_set_rg_vproc_rzsel(U32 val);
extern void upmu_set_rg_vproc_ndis_en(U32 val);
extern void upmu_set_rg_vproc_modeset(U32 val);
extern void upmu_set_rg_vproc_csm(U32 val);
extern void upmu_set_rg_vproc_avp_en(U32 val);
extern void upmu_set_rg_vproc_avp_os(U32 val);
extern void upmu_set_qi_vproc_vsleep(U32 val);
extern void upmu_set_rg_vproc_slp(U32 val);
extern void upmu_set_rg_vproc_rsv(U32 val);
extern void upmu_set_vproc_track_on_ctrl(U32 val);
extern void upmu_set_vproc_burst_ctrl(U32 val);
extern void upmu_set_vproc_dlc_ctrl(U32 val);
extern void upmu_set_vproc_vosel_ctrl(U32 val);
extern void upmu_set_vproc_en_ctrl(U32 val);
extern void upmu_set_vproc_burst_sel(U32 val);
extern void upmu_set_vproc_dlc_sel(U32 val);
extern void upmu_set_vproc_vosel_sel(U32 val);
extern void upmu_set_vproc_en_sel(U32 val);
extern U32 upmu_get_qi_vproc_oc_status(void);
extern U32 upmu_get_qi_vproc_mode(void);
extern U32 upmu_get_qi_vproc_en(void);
extern U32 upmu_get_qi_vproc_stb(void);
extern void upmu_set_vproc_en(U32 val);
extern void upmu_set_vproc_sfchg_ren(U32 val);
extern void upmu_set_vproc_sfchg_rrate(U32 val);
extern void upmu_set_vproc_sfchg_fen(U32 val);
extern void upmu_set_vproc_sfchg_frate(U32 val);
extern void upmu_set_vproc_vosel(U32 val);
extern void upmu_set_vproc_vosel_on(U32 val);
extern void upmu_set_vproc_vosel_sleep(U32 val);
extern U32 upmu_get_ni_vproc_vosel(void);
extern U32 upmu_get_qi_vproc_burst(void);
extern void upmu_set_vproc_burst_sleep(U32 val);
extern void upmu_set_vproc_burst_on(U32 val);
extern void upmu_set_vproc_burst(U32 val);
extern U32 upmu_get_qi_vproc_dlc(void);
extern void upmu_set_vproc_dlc_sleep(U32 val);
extern void upmu_set_vproc_dlc_on(U32 val);
extern void upmu_set_vproc_dlc(U32 val);
extern U32 upmu_get_qi_vproc_dlc_n(void);
extern void upmu_set_vproc_dlc_n_sleep(U32 val);
extern void upmu_set_vproc_dlc_n_on(U32 val);
extern void upmu_set_vproc_dlc_n(U32 val);
extern U32 upmu_get_qi_vproc_bursth(void);
extern U32 upmu_get_qi_vproc_burstl(void);
extern U32 upmu_get_ni_vproc_vsleep_sel(void);
extern U32 upmu_get_ni_vproc_r2r_pdn(void);
extern void upmu_set_vproc_vsleep_sel(U32 val);
extern void upmu_set_vproc_r2r_pdn(U32 val);
extern void upmu_set_vproc_vsleep_en(U32 val);
extern U32 upmu_get_ni_vproc_vosel_trans(void);
extern void upmu_set_vproc_vosel_trans_once(U32 val);
extern void upmu_set_vproc_vosel_trans_en(U32 val);
extern void upmu_set_vproc_transtd(U32 val);
extern void upmu_set_rg_vsram_trimh(U32 val);
extern void upmu_set_rg_vsram_triml(U32 val);
extern void upmu_set_rg_vsram_zx_os(U32 val);
extern void upmu_set_rg_vsram_csl(U32 val);
extern void upmu_set_rg_vsram_csr(U32 val);
extern void upmu_set_rg_vsram_cc(U32 val);
extern void upmu_set_rg_vsram_rzsel(U32 val);
extern void upmu_set_rg_vsram_ndis_en(U32 val);
extern void upmu_set_rg_vsram_modeset(U32 val);
extern void upmu_set_rg_vsram_csm(U32 val);
extern void upmu_set_qi_vsram_vsleep(U32 val);
extern void upmu_set_rg_vsram_slp(U32 val);
extern void upmu_set_rg_vsram_rsv(U32 val);
extern void upmu_set_vsram_track_sleep_ctrl(U32 val);
extern void upmu_set_vsram_track_on_ctrl(U32 val);
extern void upmu_set_vsram_burst_ctrl(U32 val);
extern void upmu_set_vsram_dlc_ctrl(U32 val);
extern void upmu_set_vsram_vosel_ctrl(U32 val);
extern void upmu_set_vsram_en_ctrl(U32 val);
extern void upmu_set_vsram_burst_sel(U32 val);
extern void upmu_set_vsram_dlc_sel(U32 val);
extern void upmu_set_vsram_vosel_sel(U32 val);
extern void upmu_set_vsram_en_sel(U32 val);
extern U32 upmu_get_qi_vsram_oc_status(void);
extern U32 upmu_get_qi_vsram_mode(void);
extern U32 upmu_get_qi_vsram_en(void);
extern U32 upmu_get_qi_vsram_stb(void);
extern void upmu_set_vsram_en(U32 val);
extern void upmu_set_vsram_sfchg_ren(U32 val);
extern void upmu_set_vsram_sfchg_rrate(U32 val);
extern void upmu_set_vsram_sfchg_fen(U32 val);
extern void upmu_set_vsram_sfchg_frate(U32 val);
extern void upmu_set_vsram_vosel(U32 val);
extern void upmu_set_vsram_vosel_on(U32 val);
extern void upmu_set_vsram_vosel_sleep(U32 val);
extern U32 upmu_get_ni_vsram_vosel(void);
extern U32 upmu_get_qi_vsram_burst(void);
extern void upmu_set_vsram_burst_sleep(U32 val);
extern void upmu_set_vsram_burst_on(U32 val);
extern void upmu_set_vsram_burst(U32 val);
extern U32 upmu_get_qi_vsram_dlc(void);
extern void upmu_set_vsram_dlc_sleep(U32 val);
extern void upmu_set_vsram_dlc_on(U32 val);
extern void upmu_set_vsram_dlc(U32 val);
extern U32 upmu_get_qi_vsram_dlc_n(void);
extern void upmu_set_vsram_dlc_n_sleep(U32 val);
extern void upmu_set_vsram_dlc_n_on(U32 val);
extern void upmu_set_vsram_dlc_n(U32 val);
extern U32 upmu_get_qi_vsram_bursth(void);
extern U32 upmu_get_qi_vsram_burstl(void);
extern U32 upmu_get_ni_vsram_vsleep_sel(void);
extern U32 upmu_get_ni_vsram_r2r_pdn(void);
extern void upmu_set_vsram_vsleep_sel(U32 val);
extern void upmu_set_vsram_r2r_pdn(U32 val);
extern void upmu_set_vsram_vsleep_en(U32 val);
extern U32 upmu_get_ni_vsram_vosel_trans(void);
extern void upmu_set_vsram_vosel_trans_once(U32 val);
extern void upmu_set_vsram_vosel_trans_en(U32 val);
extern void upmu_set_vsram_transtd(U32 val);
extern void upmu_set_vsram_vosel_offset(U32 val);
extern void upmu_set_vsram_vosel_delta(U32 val);
extern void upmu_set_vsram_vosel_on_hb(U32 val);
extern void upmu_set_vsram_vosel_on_lb(U32 val);
extern void upmu_set_vsram_vosel_sleep_lb(U32 val);
extern void upmu_set_rg_vcore_trimh(U32 val);
extern void upmu_set_rg_vcore_triml(U32 val);
extern void upmu_set_rg_vcore_zx_os(U32 val);
extern void upmu_set_rg_vcore_csl(U32 val);
extern void upmu_set_rg_vcore_csr(U32 val);
extern void upmu_set_rg_vcore_cc(U32 val);
extern void upmu_set_rg_vcore_rzsel(U32 val);
extern void upmu_set_rg_vcore_ndis_en(U32 val);
extern void upmu_set_rg_vcore_modeset(U32 val);
extern void upmu_set_rg_vcore_csm(U32 val);
extern void upmu_set_rg_vcore_avp_en(U32 val);
extern void upmu_set_rg_vcore_avp_os(U32 val);
extern void upmu_set_qi_vcore_vsleep(U32 val);
extern void upmu_set_rg_vcore_slp(U32 val);
extern void upmu_set_rg_vcore_rsv(U32 val);
extern void upmu_set_vcore_burst_ctrl(U32 val);
extern void upmu_set_vcore_dlc_ctrl(U32 val);
extern void upmu_set_vcore_vosel_ctrl(U32 val);
extern void upmu_set_vcore_en_ctrl(U32 val);
extern void upmu_set_vcore_burst_sel(U32 val);
extern void upmu_set_vcore_dlc_sel(U32 val);
extern void upmu_set_vcore_vosel_sel(U32 val);
extern void upmu_set_vcore_en_sel(U32 val);
extern U32 upmu_get_qi_vcore_oc_status(void);
extern U32 upmu_get_qi_vcore_mode(void);
extern U32 upmu_get_qi_vcore_en(void);
extern U32 upmu_get_qi_vcore_stb(void);
extern void upmu_set_vcore_en(U32 val);
extern void upmu_set_vcore_sfchg_ren(U32 val);
extern void upmu_set_vcore_sfchg_rrate(U32 val);
extern void upmu_set_vcore_sfchg_fen(U32 val);
extern void upmu_set_vcore_sfchg_frate(U32 val);
extern void upmu_set_vcore_vosel(U32 val);
extern void upmu_set_vcore_vosel_on(U32 val);
extern void upmu_set_vcore_vosel_sleep(U32 val);
extern U32 upmu_get_ni_vcore_vosel(void);
extern U32 upmu_get_qi_vcore_burst(void);
extern void upmu_set_vcore_burst_sleep(U32 val);
extern void upmu_set_vcore_burst_on(U32 val);
extern void upmu_set_vcore_burst(U32 val);
extern U32 upmu_get_qi_vcore_dlc(void);
extern void upmu_set_vcore_dlc_sleep(U32 val);
extern void upmu_set_vcore_dlc_on(U32 val);
extern void upmu_set_vcore_dlc(U32 val);
extern U32 upmu_get_qi_vcore_dlc_n(void);
extern void upmu_set_vcore_dlc_n_sleep(U32 val);
extern void upmu_set_vcore_dlc_n_on(U32 val);
extern void upmu_set_vcore_dlc_n(U32 val);
extern U32 upmu_get_qi_vcore_bursth(void);
extern U32 upmu_get_qi_vcore_burstl(void);
extern U32 upmu_get_ni_vcore_vsleep_sel(void);
extern U32 upmu_get_ni_vcore_r2r_pdn(void);
extern void upmu_set_vcore_vsleep_sel(U32 val);
extern void upmu_set_vcore_r2r_pdn(U32 val);
extern void upmu_set_vcore_vsleep_en(U32 val);
extern U32 upmu_get_ni_vcore_vosel_trans(void);
extern void upmu_set_vcore_vosel_trans_once(U32 val);
extern void upmu_set_vcore_vosel_trans_en(U32 val);
extern void upmu_set_vcore_transtd(U32 val);
extern void upmu_set_rg_vm_trimh(U32 val);
extern void upmu_set_rg_vm_triml(U32 val);
extern void upmu_set_rg_vm_zx_os(U32 val);
extern void upmu_set_rg_vm_csl(U32 val);
extern void upmu_set_rg_vm_csr(U32 val);
extern void upmu_set_rg_vm_cc(U32 val);
extern void upmu_set_rg_vm_rzsel(U32 val);
extern void upmu_set_rg_vm_ndis_en(U32 val);
extern void upmu_set_rg_vm_modeset(U32 val);
extern void upmu_set_rg_vm_csm(U32 val);
extern void upmu_set_rg_vm_avp_en(U32 val);
extern void upmu_set_rg_vm_avp_os(U32 val);
extern void upmu_set_qi_vm_vsleep(U32 val);
extern void upmu_set_rg_vm_slp(U32 val);
extern void upmu_set_rg_vm_rsv(U32 val);
extern void upmu_set_vm_burst_ctrl(U32 val);
extern void upmu_set_vm_dlc_ctrl(U32 val);
extern void upmu_set_vm_vosel_ctrl(U32 val);
extern void upmu_set_vm_en_ctrl(U32 val);
extern void upmu_set_vm_burst_sel(U32 val);
extern void upmu_set_vm_dlc_sel(U32 val);
extern void upmu_set_vm_vosel_sel(U32 val);
extern void upmu_set_vm_en_sel(U32 val);
extern U32 upmu_get_qi_vm_oc_status(void);
extern U32 upmu_get_qi_vm_mode(void);
extern U32 upmu_get_qi_vm_en(void);
extern U32 upmu_get_qi_vm_stb(void);
extern void upmu_set_vm_en(U32 val);
extern void upmu_set_vm_sfchg_ren(U32 val);
extern void upmu_set_vm_sfchg_rrate(U32 val);
extern void upmu_set_vm_sfchg_fen(U32 val);
extern void upmu_set_vm_sfchg_frate(U32 val);
extern void upmu_set_vm_vosel(U32 val);
extern void upmu_set_vm_vosel_on(U32 val);
extern void upmu_set_vm_vosel_sleep(U32 val);
extern U32 upmu_get_ni_vm_vosel(void);
extern U32 upmu_get_qi_vm_burst(void);
extern void upmu_set_vm_burst_sleep(U32 val);
extern void upmu_set_vm_burst_on(U32 val);
extern void upmu_set_vm_burst(U32 val);
extern U32 upmu_get_qi_vm_dlc(void);
extern void upmu_set_vm_dlc_sleep(U32 val);
extern void upmu_set_vm_dlc_on(U32 val);
extern void upmu_set_vm_dlc(U32 val);
extern U32 upmu_get_qi_vm_dlc_n(void);
extern void upmu_set_vm_dlc_n_sleep(U32 val);
extern void upmu_set_vm_dlc_n_on(U32 val);
extern void upmu_set_vm_dlc_n(U32 val);
extern U32 upmu_get_qi_vm_bursth(void);
extern U32 upmu_get_qi_vm_burstl(void);
extern U32 upmu_get_ni_vm_vsleep_sel(void);
extern U32 upmu_get_ni_vm_r2r_pdn(void);
extern void upmu_set_vm_vsleep_sel(U32 val);
extern void upmu_set_vm_r2r_pdn(U32 val);
extern void upmu_set_vm_vsleep_en(U32 val);
extern U32 upmu_get_ni_vm_vosel_trans(void);
extern void upmu_set_vm_vosel_trans_once(U32 val);
extern void upmu_set_vm_vosel_trans_en(U32 val);
extern void upmu_set_vm_transtd(U32 val);
extern void upmu_set_rg_vio18_trim(U32 val);
extern void upmu_set_rg_vio18_zx_os(U32 val);
extern void upmu_set_rg_vio18_slew(U32 val);
extern void upmu_set_rg_vio18_slew_nmos(U32 val);
extern void upmu_set_rg_vio18_csl(U32 val);
extern void upmu_set_rg_vio18_csr(U32 val);
extern void upmu_set_rg_vio18_cc(U32 val);
extern void upmu_set_rg_vio18_rzsel(U32 val);
extern void upmu_set_rg_vio18_csmir(U32 val);
extern void upmu_set_rg_vio18_ndis_en(U32 val);
extern void upmu_set_rg_vio18_modeset(U32 val);
extern void upmu_set_rg_vio18_slp(U32 val);
extern void upmu_set_rg_vio18_rsv(U32 val);
extern void upmu_set_vio18_burst_ctrl(U32 val);
extern void upmu_set_vio18_dlc_ctrl(U32 val);
extern void upmu_set_vio18_vosel_ctrl(U32 val);
extern void upmu_set_vio18_en_ctrl(U32 val);
extern void upmu_set_vio18_burst_sel(U32 val);
extern void upmu_set_vio18_dlc_sel(U32 val);
extern void upmu_set_vio18_vosel_sel(U32 val);
extern void upmu_set_vio18_en_sel(U32 val);
extern U32 upmu_get_qi_vio18_oc_status(void);
extern U32 upmu_get_qi_vio18_mode(void);
extern U32 upmu_get_qi_vio18_en(void);
extern U32 upmu_get_qi_vio18_stb(void);
extern void upmu_set_vio18_en(U32 val);
extern void upmu_set_vio18_sfchg_ren(U32 val);
extern void upmu_set_vio18_sfchg_rrate(U32 val);
extern void upmu_set_vio18_sfchg_fen(U32 val);
extern void upmu_set_vio18_sfchg_frate(U32 val);
extern void upmu_set_vio18_vosel(U32 val);
extern void upmu_set_vio18_vosel_on(U32 val);
extern void upmu_set_vio18_vosel_sleep(U32 val);
extern U32 upmu_get_ni_vio18_vosel(void);
extern U32 upmu_get_qi_vio18_burst(void);
extern U32 upmu_get_qi_vio18_dlc(void);
extern void upmu_set_vio18_dlc_sleep(U32 val);
extern void upmu_set_vio18_dlc_on(U32 val);
extern void upmu_set_vio18_dlc(U32 val);
extern U32 upmu_get_qi_vio18_dlc_n(void);
extern void upmu_set_vio18_dlc_n_sleep(U32 val);
extern void upmu_set_vio18_dlc_n_on(U32 val);
extern void upmu_set_vio18_dlc_n(U32 val);
extern U32 upmu_get_qi_vio18_bursth(void);
extern void upmu_set_vio18_bursth_sleep(U32 val);
extern void upmu_set_vio18_bursth_on(U32 val);
extern void upmu_set_vio18_bursth(U32 val);
extern U32 upmu_get_qi_vio18_burstl(void);
extern void upmu_set_vio18_burstl_sleep(U32 val);
extern void upmu_set_vio18_burstl_on(U32 val);
extern void upmu_set_vio18_burstl(U32 val);
extern U32 upmu_get_ni_vio18_vsleep_sel(void);
extern U32 upmu_get_qi_vio18_sleep_pdn(void);
extern void upmu_set_vio18_vsleep_sel(U32 val);
extern void upmu_set_vio18_sleep_pdn(U32 val);
extern void upmu_set_vio18_vsleep_en(U32 val);
extern U32 upmu_get_ni_vio18_vosel_trans(void);
extern void upmu_set_vio18_vosel_trans_once(U32 val);
extern void upmu_set_vio18_vosel_trans_en(U32 val);
extern void upmu_set_vio18_transtd(U32 val);
extern void upmu_set_rg_vpa_trimh(U32 val);
extern void upmu_set_rg_vpa_triml(U32 val);
extern void upmu_set_rg_vpa_zx_os(U32 val);
extern void upmu_set_rg_vpa_slew(U32 val);
extern void upmu_set_rg_vpa_slew_nmos(U32 val);
extern void upmu_set_rg_vpa_csl(U32 val);
extern void upmu_set_rg_vpa_csr(U32 val);
extern void upmu_set_rg_vpa_cc(U32 val);
extern void upmu_set_rg_vpa_rzsel(U32 val);
extern void upmu_set_rg_vpa_vbat_del(U32 val);
extern void upmu_set_rg_vpa_csmir(U32 val);
extern void upmu_set_rg_vpa_ndis_en(U32 val);
extern void upmu_set_rg_vpa_modeset(U32 val);
extern void upmu_set_rg_vpa_gpu_en(U32 val);
extern void upmu_set_rg_vpa_slp(U32 val);
extern void upmu_set_rg_vpa_rsv(U32 val);
extern void upmu_set_vpa_burst_ctrl(U32 val);
extern void upmu_set_vpa_dlc_ctrl(U32 val);
extern void upmu_set_vpa_vosel_ctrl(U32 val);
extern void upmu_set_vpa_en_ctrl(U32 val);
extern void upmu_set_vpa_burst_sel(U32 val);
extern void upmu_set_vpa_dlc_sel(U32 val);
extern void upmu_set_vpa_vosel_sel(U32 val);
extern void upmu_set_vpa_en_sel(U32 val);
extern U32 upmu_get_qi_vpa_oc_status(void);
extern U32 upmu_get_qi_vpa_mode(void);
extern U32 upmu_get_qi_vpa_en(void);
extern U32 upmu_get_qi_vpa_stb(void);
extern void upmu_set_vpa_en(U32 val);
extern void upmu_set_vpa_sfchg_ren(U32 val);
extern void upmu_set_vpa_sfchg_rrate(U32 val);
extern void upmu_set_vpa_sfchg_fen(U32 val);
extern void upmu_set_vpa_sfchg_frate(U32 val);
extern void upmu_set_vpa_vosel(U32 val);
extern void upmu_set_vpa_vosel_on(U32 val);
extern void upmu_set_vpa_vosel_sleep(U32 val);
extern U32 upmu_get_ni_vpa_vosel(void);
extern U32 upmu_get_qi_vpa_burst(void);
extern U32 upmu_get_qi_vpa_dlc(void);
extern void upmu_set_vpa_dlc_sleep(U32 val);
extern void upmu_set_vpa_dlc_on(U32 val);
extern void upmu_set_vpa_dlc(U32 val);
extern U32 upmu_get_qi_vpa_dlc_n(void);
extern U32 upmu_get_qi_vpa_bursth(void);
extern void upmu_set_vpa_bursth_sleep(U32 val);
extern void upmu_set_vpa_bursth_on(U32 val);
extern void upmu_set_vpa_bursth(U32 val);
extern U32 upmu_get_qi_vpa_burstl(void);
extern void upmu_set_vpa_burstl_sleep(U32 val);
extern void upmu_set_vpa_burstl_on(U32 val);
extern void upmu_set_vpa_burstl(U32 val);
extern U32 upmu_get_ni_vpa_vsleep_sel(void);
extern U32 upmu_get_ni_vpa_r2r_pdn(void);
extern void upmu_set_vpa_vsleep_sel(U32 val);
extern void upmu_set_vpa_r2r_pdn(U32 val);
extern void upmu_set_vpa_vsleep_en(U32 val);
extern U32 upmu_get_ni_vpa_dvs_bw(void);
extern void upmu_set_vpa_vosel_trans_once(U32 val);
extern void upmu_set_vpa_vosel_trans_en(U32 val);
extern void upmu_set_vpa_transtd(U32 val);
extern void upmu_set_vpa_vosel_dlc001(U32 val);
extern void upmu_set_vpa_dlc_map_en(U32 val);
extern void upmu_set_vpa_vosel_dlc111(U32 val);
extern void upmu_set_vpa_vosel_dlc011(U32 val);
extern void upmu_set_rg_vrf18_trim(U32 val);
extern void upmu_set_rg_vrf18_zx_os(U32 val);
extern void upmu_set_rg_vrf18_slew(U32 val);
extern void upmu_set_rg_vrf18_slew_nmos(U32 val);
extern void upmu_set_rg_vrf18_csl(U32 val);
extern void upmu_set_rg_vrf18_csr(U32 val);
extern void upmu_set_rg_vrf18_cc(U32 val);
extern void upmu_set_rg_vrf18_rzsel(U32 val);
extern void upmu_set_rg_vrf18_gmsel(U32 val);
extern void upmu_set_rg_vrf18_ocfb_en(U32 val);
extern void upmu_set_rg_vrf18_ndis_en(U32 val);
extern void upmu_set_rg_vrf18_modeset(U32 val);
extern void upmu_set_rg_vrf18_avp_en(U32 val);
extern void upmu_set_rg_vrf18_slp(U32 val);
extern void upmu_set_rg_vrf18_rsv_7_2(U32 val);
extern void upmu_set_rg_vrf18_bk_ldo(U32 val);
extern void upmu_set_rg_vrf18_rsv_0(U32 val);
extern void upmu_set_vrf18_burst_ctrl(U32 val);
extern void upmu_set_vrf18_dlc_ctrl(U32 val);
extern void upmu_set_vrf18_vosel_ctrl(U32 val);
extern void upmu_set_vrf18_en_ctrl(U32 val);
extern void upmu_set_vrf18_burst_sel(U32 val);
extern void upmu_set_vrf18_dlc_sel(U32 val);
extern void upmu_set_vrf18_vosel_sel(U32 val);
extern void upmu_set_vrf18_en_sel(U32 val);
extern U32 upmu_get_qi_vrf18_oc_status(void);
extern U32 upmu_get_qi_vrf18_mode(void);
extern U32 upmu_get_qi_vrf18_en(void);
extern U32 upmu_get_qi_vrf18_stb(void);
extern void upmu_set_vrf18_stbtd(U32 val);
extern void upmu_set_vrf18_en(U32 val);
extern void upmu_set_vrf18_sfchg_ren(U32 val);
extern void upmu_set_vrf18_sfchg_rrate(U32 val);
extern void upmu_set_vrf18_sfchg_fen(U32 val);
extern void upmu_set_vrf18_sfchg_frate(U32 val);
extern void upmu_set_vrf18_vosel(U32 val);
extern void upmu_set_vrf18_vosel_on(U32 val);
extern void upmu_set_vrf18_vosel_sleep(U32 val);
extern U32 upmu_get_ni_vrf18_vosel(void);
extern U32 upmu_get_qi_vrf18_burst(void);
extern U32 upmu_get_qi_vrf18_dlc(void);
extern void upmu_set_vrf18_dlc_sleep(U32 val);
extern void upmu_set_vrf18_dlc_on(U32 val);
extern void upmu_set_vrf18_dlc(U32 val);
extern U32 upmu_get_qi_vrf18_dlc_n(void);
extern void upmu_set_vrf18_dlc_n_sleep(U32 val);
extern void upmu_set_vrf18_dlc_n_on(U32 val);
extern void upmu_set_vrf18_dlc_n(U32 val);
extern U32 upmu_get_qi_vrf18_bursth(void);
extern void upmu_set_vrf18_bursth_sleep(U32 val);
extern void upmu_set_vrf18_bursth_on(U32 val);
extern void upmu_set_vrf18_bursth(U32 val);
extern U32 upmu_get_qi_vrf18_burstl(void);
extern void upmu_set_vrf18_burstl_sleep(U32 val);
extern void upmu_set_vrf18_burstl_on(U32 val);
extern void upmu_set_vrf18_burstl(U32 val);
extern U32 upmu_get_ni_vrf18_vsleep_sel(void);
extern U32 upmu_get_ni_vrf18_r2r_pdn(void);
extern void upmu_set_vrf18_vsleep_sel(U32 val);
extern void upmu_set_vrf18_r2r_pdn(U32 val);
extern void upmu_set_vrf18_vsleep_en(U32 val);
extern U32 upmu_get_ni_vrf18_vosel_trans(void);
extern void upmu_set_vrf18_vosel_trans_once(U32 val);
extern void upmu_set_vrf18_vosel_trans_en(U32 val);
extern void upmu_set_vrf18_transtd(U32 val);
extern void upmu_set_vrf18_md2_en_sel(U32 val);
extern void upmu_set_vrf18_md2_en(U32 val);
extern void upmu_set_vrf18_md1_en_sel(U32 val);
extern void upmu_set_rg_vrf18_2_trim(U32 val);
extern void upmu_set_rg_vrf18_2_zx_os(U32 val);
extern void upmu_set_rg_vrf18_2_slew(U32 val);
extern void upmu_set_rg_vrf18_2_slew_nmos(U32 val);
extern void upmu_set_rg_vrf18_2_csl(U32 val);
extern void upmu_set_rg_vrf18_2_csr(U32 val);
extern void upmu_set_rg_vrf18_2_cc(U32 val);
extern void upmu_set_rg_vrf18_2_rzsel(U32 val);
extern void upmu_set_rg_vrf18_2_gmsel(U32 val);
extern void upmu_set_rg_vrf18_2_ocfb_en(U32 val);
extern void upmu_set_rg_vrf18_2_ndis_en(U32 val);
extern void upmu_set_rg_vrf18_2_modeset(U32 val);
extern void upmu_set_rg_vrf18_2_avp_en(U32 val);
extern void upmu_set_rg_vrf18_2_slp(U32 val);
extern void upmu_set_rg_vrf18_2_rsv_7_2(U32 val);
extern void upmu_set_rg_vrf18_2_bk_ldo(U32 val);
extern void upmu_set_rg_vrf18_2_rsv_0(U32 val);
extern void upmu_set_vrf18_2_burst_ctrl(U32 val);
extern void upmu_set_vrf18_2_dlc_ctrl(U32 val);
extern void upmu_set_vrf18_2_vosel_ctrl(U32 val);
extern void upmu_set_vrf18_2_en_ctrl(U32 val);
extern void upmu_set_vrf18_2_burst_sel(U32 val);
extern void upmu_set_vrf18_2_dlc_sel(U32 val);
extern void upmu_set_vrf18_2_vosel_sel(U32 val);
extern void upmu_set_vrf18_2_en_sel(U32 val);
extern U32 upmu_get_qi_vrf18_2_oc_status(void);
extern U32 upmu_get_qi_vrf18_2_mode(void);
extern U32 upmu_get_qi_vrf18_2_en(void);
extern U32 upmu_get_qi_vrf18_2_stb(void);
extern void upmu_set_vrf18_2_stbtd(U32 val);
extern void upmu_set_vrf18_2_en(U32 val);
extern void upmu_set_vrf18_2_sfchg_ren(U32 val);
extern void upmu_set_vrf18_2_sfchg_rrate(U32 val);
extern void upmu_set_vrf18_2_sfchg_fen(U32 val);
extern void upmu_set_vrf18_2_sfchg_frate(U32 val);
extern void upmu_set_vrf18_2_vosel(U32 val);
extern void upmu_set_vrf18_2_vosel_on(U32 val);
extern void upmu_set_vrf18_2_vosel_sleep(U32 val);
extern U32 upmu_get_ni_vrf18_2_vosel(void);
extern U32 upmu_get_qi_vrf18_2_burst(void);
extern U32 upmu_get_qi_vrf18_2_dlc(void);
extern void upmu_set_vrf18_2_dlc_sleep(U32 val);
extern void upmu_set_vrf18_2_dlc_on(U32 val);
extern void upmu_set_vrf18_2_dlc(U32 val);
extern U32 upmu_get_qi_vrf18_2_dlc_n(void);
extern void upmu_set_vrf18_2_dlc_n_sleep(U32 val);
extern void upmu_set_vrf18_2_dlc_n_on(U32 val);
extern void upmu_set_vrf18_2_dlc_n(U32 val);
extern U32 upmu_get_qi_vrf18_2_bursth(void);
extern void upmu_set_vrf18_2_bursth_sleep(U32 val);
extern void upmu_set_vrf18_2_bursth_on(U32 val);
extern void upmu_set_vrf18_2_bursth(U32 val);
extern U32 upmu_get_qi_vrf18_2_burstl(void);
extern void upmu_set_vrf18_2_burstl_sleep(U32 val);
extern void upmu_set_vrf18_2_burstl_on(U32 val);
extern void upmu_set_vrf18_2_burstl(U32 val);
extern U32 upmu_get_ni_vrf18_2_vsleep_sel(void);
extern U32 upmu_get_ni_vrf18_2_r2r_pdn(void);
extern void upmu_set_vrf18_2_vsleep_sel(U32 val);
extern void upmu_set_vrf18_2_r2r_pdn(U32 val);
extern void upmu_set_vrf18_2_vsleep_en(U32 val);
extern U32 upmu_get_ni_vrf18_2_vosel_trans(void);
extern void upmu_set_vrf18_2_vosel_trans_once(U32 val);
extern void upmu_set_vrf18_2_vosel_trans_en(U32 val);
extern void upmu_set_vrf18_2_transtd(U32 val);
extern void upmu_set_k_control_smps(U32 val);
extern void upmu_set_k_auto_en(U32 val);
extern void upmu_set_k_src_sel(U32 val);
extern void upmu_set_k_start_manual(U32 val);
extern void upmu_set_k_once(U32 val);
extern void upmu_set_k_once_en(U32 val);
extern void upmu_set_k_map_sel(U32 val);
extern void upmu_set_k_rst_done(U32 val);
extern U32 upmu_get_qi_smps_osc_cal(void);
extern U32 upmu_get_k_control(void);
extern U32 upmu_get_k_done(void);
extern U32 upmu_get_k_result(void);
extern U32 upmu_get_qi_vrf28_en(void);
extern void upmu_set_vrf28_on_ctrl(U32 val);
extern void upmu_set_rg_vrf28_en(U32 val);
extern void upmu_set_rg_vrf28_stbtd(U32 val);
extern void upmu_set_vrf28_srclk_en_sel(U32 val);
extern U32 upmu_get_qi_vtcxo_en(void);
extern void upmu_set_vtcxo_srclk_en_sel(U32 val);
extern void upmu_set_vtcxo_on_ctrl(U32 val);
extern void upmu_set_rg_vtcxo_en(U32 val);
extern void upmu_set_rg_vtcxo_stbtd(U32 val);
extern U32 upmu_get_qi_vtcxo_mode(void);
extern void upmu_set_vtcxo_srclk_mode_sel(U32 val);
extern void upmu_set_vtcxo_lp_set(U32 val);
extern void upmu_set_vtcxo_lp_sel(U32 val);
extern U32 upmu_get_qi_va_en(void);
extern void upmu_set_rg_va_en(U32 val);
extern void upmu_set_rg_va_stbtd(U32 val);
extern U32 upmu_get_qi_va_mode(void);
extern void upmu_set_va_srclk_mode_sel(U32 val);
extern void upmu_set_va_lp_set(U32 val);
extern void upmu_set_va_lp_sel(U32 val);
extern U32 upmu_get_qi_va28_en(void);
extern void upmu_set_rg_va28_en(U32 val);
extern void upmu_set_rg_va28_stbtd(U32 val);
extern U32 upmu_get_qi_va28_mode(void);
extern void upmu_set_va28_srclk_mode_sel(U32 val);
extern void upmu_set_va28_lp_set(U32 val);
extern void upmu_set_va28_lp_sel(U32 val);
extern void upmu_set_rg_vcama_en(U32 val);
extern void upmu_set_rg_vcama_stbtd(U32 val);
extern U32 upmu_get_qi_vrf28_oc_status(void);
extern U32 upmu_get_qi_vtcxo_oc_status(void);
extern U32 upmu_get_qi_va_oc_status(void);
extern U32 upmu_get_qi_va28_oc_status(void);
extern U32 upmu_get_qi_vcama_oc_status(void);
extern void upmu_set_rg_vrf28_bist_en(U32 val);
extern void upmu_set_rg_vrf28_2_bist_en(U32 val);
extern void upmu_set_rg_vtcxo_bist_en(U32 val);
extern void upmu_set_rg_vtcxo_2_bist_en(U32 val);
extern void upmu_set_rg_va_bist_en(U32 val);
extern void upmu_set_rg_va28_bist_en(U32 val);
extern void upmu_set_rg_vcama_bist_en(U32 val);
extern void upmu_set_rg_vrf28_cal(U32 val);
extern void upmu_set_rg_vrf28_ocfb(U32 val);
extern void upmu_set_rg_vrf28_ndis_en(U32 val);
extern void upmu_set_rg_vtcxo_cal(U32 val);
extern void upmu_set_rg_vtcxo_ocfb(U32 val);
extern void upmu_set_rg_vtcxo_ndis_en(U32 val);
extern void upmu_set_rg_va_cal(U32 val);
extern void upmu_set_rg_va_vosel(U32 val);
extern void upmu_set_rg_va_ocfb(U32 val);
extern void upmu_set_rg_va_ndis_en(U32 val);
extern void upmu_set_rg_va28_cal(U32 val);
extern void upmu_set_rg_va28_ocfb_en(U32 val);
extern void upmu_set_rg_va28_ndis_en(U32 val);
extern void upmu_set_rg_vrf28_vosel(U32 val);
extern void upmu_set_rg_vcama_cal(U32 val);
extern void upmu_set_rg_vcama_vosel(U32 val);
extern void upmu_set_rg_vcama_ocfb(U32 val);
extern void upmu_set_rg_vcama_ndis_en(U32 val);
extern void upmu_set_rg_vcama_fbsel(U32 val);
extern void upmu_set_rg_vtcxo_2_cal(U32 val);
extern void upmu_set_rg_vtcxo_2_ocfb(U32 val);
extern void upmu_set_rg_vtcxo_2_ndis_en(U32 val);
extern void upmu_set_rg_vtcxo_2_vosel(U32 val);
extern void upmu_set_rg_vrf28_2_cal(U32 val);
extern void upmu_set_rg_vrf28_2_ocfb(U32 val);
extern void upmu_set_rg_vrf28_2_ndis_en(U32 val);
extern void upmu_set_rg_vrf28_2_vosel(U32 val);
extern U32 upmu_get_qi_vrf28_2_en(void);
extern void upmu_set_vrf28_on_2_ctrl(U32 val);
extern void upmu_set_rg_vrf28_2_en(U32 val);
extern void upmu_set_rg_vrf28_2_stbtd(U32 val);
extern void upmu_set_vrf28_2_srclk_en_sel(U32 val);
extern U32 upmu_get_qi_vtcxo_2_en(void);
extern void upmu_set_vtcxo_2_srclk_en_sel(U32 val);
extern void upmu_set_vtcxo_2_on_ctrl(U32 val);
extern void upmu_set_rg_vtcxo_2_en(U32 val);
extern void upmu_set_rg_vtcxo_2_stbtd(U32 val);
extern U32 upmu_get_qi_vtcxo_2_mode(void);
extern void upmu_set_vtcxo_2_srclk_mode_sel(U32 val);
extern void upmu_set_vtcxo_2_lp_set(U32 val);
extern void upmu_set_vtcxo_2_lp_sel(U32 val);
extern void upmu_set_rg_aldo_reserve_1(U32 val);
extern void upmu_set_rg_aldo_reserve_2(U32 val);
extern void upmu_set_analdo_rsv0(U32 val);
extern void upmu_set_analdo_rsv1(U32 val);
extern U32 upmu_get_qi_vio28_en(void);
extern void upmu_set_vio28_en(U32 val);
extern void upmu_set_rg_vio28_stbtd(U32 val);
extern U32 upmu_get_qi_vio28_mode(void);
extern void upmu_set_vio28_srclk_mode_sel(U32 val);
extern void upmu_set_vio28_lp_mode_set(U32 val);
extern void upmu_set_vio28_lp_sel(U32 val);
extern U32 upmu_get_qi_vusb_en(void);
extern void upmu_set_rg_vusb_en(U32 val);
extern void upmu_set_rg_vusb_stbtd(U32 val);
extern U32 upmu_get_qi_vusb_mode(void);
extern void upmu_set_vusb_srclk_mode_sel(U32 val);
extern void upmu_set_vusb_lp_mode_set(U32 val);
extern void upmu_set_vusb_lp_sel(U32 val);
extern U32 upmu_get_qi_vmc1_en(void);
extern void upmu_set_rg_vmc1_int_dis_sel(U32 val);
extern void upmu_set_rg_vmc1_en(U32 val);
extern void upmu_set_rg_vmc1_stbtd(U32 val);
extern U32 upmu_get_qi_vmc1_mode(void);
extern void upmu_set_vmc1_srclk_mode_sel(U32 val);
extern void upmu_set_vmc1_lp_mode_set(U32 val);
extern void upmu_set_vmc1_lp_sel(U32 val);
extern U32 upmu_get_qi_vmch1_en(void);
extern void upmu_set_rg_vmch1_en(U32 val);
extern void upmu_set_rg_vmch1_stbtd(U32 val);
extern U32 upmu_get_qi_vmch1_mode(void);
extern void upmu_set_vmch1_srclk_mode_sel(U32 val);
extern void upmu_set_vmch1_lp_mode_set(U32 val);
extern void upmu_set_vmch1_lp_sel(U32 val);
extern U32 upmu_get_qi_vemc_3v3_en(void);
extern void upmu_set_rg_vemc_3v3_en(U32 val);
extern void upmu_set_rg_vemc_3v3_stbtd(U32 val);
extern U32 upmu_get_qi_vemc_3v3_mode(void);
extern void upmu_set_vemc_3v3_srclk_mode_sel(U32 val);
extern void upmu_set_vemc_3v3_lp_mode_set(U32 val);
extern void upmu_set_vemc_3v3_lp_sel(U32 val);
extern void upmu_set_rg_vgp1_en(U32 val);
extern void upmu_set_rg_vgp1_stbtd(U32 val);
extern U32 upmu_get_qi_vgp1_mode(void);
extern void upmu_set_vgp1_srclk_mode_sel(U32 val);
extern void upmu_set_vgp1_lp_mode_set(U32 val);
extern void upmu_set_vgp1_lp_sel(U32 val);
extern void upmu_set_rg_vgp2_en(U32 val);
extern void upmu_set_rg_vgp2_stbtd(U32 val);
extern U32 upmu_get_qi_vgp2_mode(void);
extern void upmu_set_vgp2_srclk_mode_sel(U32 val);
extern void upmu_set_vgp2_lp_mode_set(U32 val);
extern void upmu_set_vgp2_lp_sel(U32 val);
extern void upmu_set_rg_vgp3_en(U32 val);
extern void upmu_set_rg_vgp3_stbtd(U32 val);
extern U32 upmu_get_qi_vgp3_mode(void);
extern void upmu_set_vgp3_srclk_mode_sel(U32 val);
extern void upmu_set_vgp3_lp_mode_set(U32 val);
extern void upmu_set_vgp3_lp_sel(U32 val);
extern void upmu_set_rg_vgp4_en(U32 val);
extern void upmu_set_rg_vgp4_stbtd(U32 val);
extern U32 upmu_get_qi_vgp4_mode(void);
extern void upmu_set_vgp4_srclk_mode_sel(U32 val);
extern void upmu_set_vgp4_lp_mode_set(U32 val);
extern void upmu_set_vgp4_lp_sel(U32 val);
extern void upmu_set_rg_vgp5_en(U32 val);
extern void upmu_set_rg_vgp5_stbtd(U32 val);
extern U32 upmu_get_qi_vgp5_mode(void);
extern void upmu_set_vgp5_srclk_mode_sel(U32 val);
extern void upmu_set_vgp5_lp_mode_set(U32 val);
extern void upmu_set_vgp5_lp_sel(U32 val);
extern void upmu_set_rg_vgp6_en(U32 val);
extern void upmu_set_rg_vgp6_stbtd(U32 val);
extern U32 upmu_get_qi_vgp6_mode(void);
extern void upmu_set_vgp6_srclk_mode_sel(U32 val);
extern void upmu_set_vgp6_lp_mode_set(U32 val);
extern void upmu_set_vgp6_lp_sel(U32 val);
extern void upmu_set_rg_vsim1_en(U32 val);
extern void upmu_set_rg_vsim1_stbtd(U32 val);
extern U32 upmu_get_qi_vsim1_mode(void);
extern void upmu_set_vsim1_srclk_mode_sel(U32 val);
extern void upmu_set_vsim1_lp_mode_set(U32 val);
extern void upmu_set_vsim1_lp_sel(U32 val);
extern void upmu_set_rg_vsim2_en(U32 val);
extern void upmu_set_rg_vsim2_stbtd(U32 val);
extern U32 upmu_get_qi_vsim2_mode(void);
extern void upmu_set_vsim2_srclk_mode_sel(U32 val);
extern void upmu_set_vsim2_ther_shdn_en(U32 val);
extern void upmu_set_vsim2_lp_mode_set(U32 val);
extern void upmu_set_vsim2_lp_sel(U32 val);
extern U32 upmu_get_qi_vrtc_en(void);
extern void upmu_set_vrtc_en(U32 val);
extern void upmu_set_rg_vio28_bist_en(U32 val);
extern void upmu_set_rg_vusb_bist_en(U32 val);
extern void upmu_set_rg_vmc1_bist_en(U32 val);
extern void upmu_set_rg_vmch1_bist_en(U32 val);
extern void upmu_set_rg_vemc_3v3_bist_en(U32 val);
extern void upmu_set_rg_vgp1_bist_en(U32 val);
extern void upmu_set_rg_vgp2_bist_en(U32 val);
extern void upmu_set_rg_vgp3_bist_en(U32 val);
extern void upmu_set_rg_vgp4_bist_en(U32 val);
extern void upmu_set_rg_vgp5_bist_en(U32 val);
extern void upmu_set_rg_vgp6_bist_en(U32 val);
extern void upmu_set_rg_vibr_bist_en(U32 val);
extern void upmu_set_rg_vsim1_bist_en(U32 val);
extern void upmu_set_rg_vsim2_bist_en(U32 val);
extern void upmu_set_rg_vemc_1v8_bist_en(U32 val);
extern void upmu_set_rg_vrtc_bist_en(U32 val);
extern U32 upmu_get_qi_vio28_oc_status(void);
extern U32 upmu_get_qi_vusb_oc_status(void);
extern U32 upmu_get_qi_vmc1_oc_status(void);
extern U32 upmu_get_qi_vmch1_oc_status(void);
extern U32 upmu_get_qi_vemc_3v3_oc_status(void);
extern U32 upmu_get_qi_vgp1_oc_status(void);
extern U32 upmu_get_qi_vgp2_oc_status(void);
extern U32 upmu_get_qi_vgp3_oc_status(void);
extern U32 upmu_get_qi_vgp4_oc_status(void);
extern U32 upmu_get_qi_vgp5_oc_status(void);
extern U32 upmu_get_qi_vgp6_oc_status(void);
extern U32 upmu_get_qi_vibr_oc_status(void);
extern U32 upmu_get_qi_vsim1_oc_status(void);
extern U32 upmu_get_qi_vsim2_oc_status(void);
extern U32 upmu_get_qi_vemc_1v8_oc_status(void);
extern U32 upmu_get_qi_vast_oc_status(void);
extern U32 upmu_get_qi_vast_en(void);
extern void upmu_set_rg_vast_vosel(U32 val);
extern void upmu_set_rg_vast_en(U32 val);
extern void upmu_set_rg_vast_stbtd(U32 val);
extern U32 upmu_get_qi_vast_mode(void);
extern void upmu_set_vast_srclk_mode_sel(U32 val);
extern void upmu_set_rg_vast_sleep(U32 val);
extern void upmu_set_rg_vast_dis_srclken(U32 val);
extern void upmu_set_vast_lp_mode_set(U32 val);
extern void upmu_set_vast_lp_sel(U32 val);
extern void upmu_set_rg_vio28_cal(U32 val);
extern void upmu_set_rg_vio28_ocfb(U32 val);
extern void upmu_set_rg_vio28_ndis_en(U32 val);
extern void upmu_set_rg_vusb_cal(U32 val);
extern void upmu_set_rg_vusb_ocfb(U32 val);
extern void upmu_set_rg_vusb_ndis_en(U32 val);
extern void upmu_set_rg_vmc1_cal(U32 val);
extern void upmu_set_rg_vmc1_stb_sel(U32 val);
extern void upmu_set_rg_vmc1_vosel(U32 val);
extern void upmu_set_rg_vmc1_ocfb(U32 val);
extern void upmu_set_rg_vmc1_ndis_en(U32 val);
extern void upmu_set_rg_vmch1_cal(U32 val);
extern void upmu_set_rg_vmch1_vosel(U32 val);
extern void upmu_set_rg_vmch1_stb_sel(U32 val);
extern void upmu_set_rg_vmch1_db_en(U32 val);
extern void upmu_set_rg_vmch1_ocfb(U32 val);
extern void upmu_set_rg_vmch1_ndis_en(U32 val);
extern void upmu_set_rg_vemc_3v3_cal(U32 val);
extern void upmu_set_rg_vemc_3v3_vosel(U32 val);
extern void upmu_set_rg_vemc_3v3_stb_sel(U32 val);
extern void upmu_set_rg_vemc_3v3_db_en(U32 val);
extern void upmu_set_rg_vemc_3v3_ocfb(U32 val);
extern void upmu_set_rg_vemc_3v3_ndis_en(U32 val);
extern void upmu_set_rg_vgp1_cal(U32 val);
extern void upmu_set_rg_vgp1_vosel(U32 val);
extern void upmu_set_rg_vgp1_stb_sel(U32 val);
extern void upmu_set_rg_vgp1_ocfb(U32 val);
extern void upmu_set_rg_vgp1_ndis_en(U32 val);
extern void upmu_set_rg_vgp2_cal(U32 val);
extern void upmu_set_rg_vgp2_vosel(U32 val);
extern void upmu_set_rg_vgp2_stb_sel(U32 val);
extern void upmu_set_rg_vgp2_ocfb(U32 val);
extern void upmu_set_rg_vgp2_ndis_en(U32 val);
extern void upmu_set_rg_vgp3_cal(U32 val);
extern void upmu_set_rg_vgp3_vosel(U32 val);
extern void upmu_set_rg_vgp3_stb_sel(U32 val);
extern void upmu_set_rg_vgp3_ocfb(U32 val);
extern void upmu_set_rg_vgp3_ndis_en(U32 val);
extern void upmu_set_rg_vgp4_cal(U32 val);
extern void upmu_set_rg_vgp4_vosel(U32 val);
extern void upmu_set_rg_vgp4_stb_sel(U32 val);
extern void upmu_set_rg_vgp4_ocfb(U32 val);
extern void upmu_set_rg_vgp4_ndis_en(U32 val);
extern void upmu_set_rg_vgp5_cal(U32 val);
extern void upmu_set_rg_vgp5_vosel(U32 val);
extern void upmu_set_rg_vgp5_stb_sel(U32 val);
extern void upmu_set_rg_vgp5_ocfb(U32 val);
extern void upmu_set_rg_vgp5_ndis_en(U32 val);
extern void upmu_set_rg_vgp6_cal(U32 val);
extern void upmu_set_rg_vgp6_vosel(U32 val);
extern void upmu_set_rg_vgp6_stb_sel(U32 val);
extern void upmu_set_rg_vgp6_ocfb(U32 val);
extern void upmu_set_rg_vgp6_ndis_en(U32 val);
extern void upmu_set_rg_vsim1_cal(U32 val);
extern void upmu_set_rg_vsim1_vosel(U32 val);
extern void upmu_set_rg_vsim1_stb_sel(U32 val);
extern void upmu_set_rg_vsim1_ocfb(U32 val);
extern void upmu_set_rg_vsim1_ndis_en(U32 val);
extern void upmu_set_rg_vsim2_cal(U32 val);
extern void upmu_set_rg_vsim2_vosel(U32 val);
extern void upmu_set_rg_vsim2_stb_sel(U32 val);
extern void upmu_set_rg_vsim2_ocfb(U32 val);
extern void upmu_set_rg_vsim2_ndis_en(U32 val);
extern void upmu_set_rg_vast_cal(U32 val);
extern void upmu_set_rg_vast_ocfb(U32 val);
extern void upmu_set_rg_vast_ndis_en(U32 val);
extern U32 upmu_get_qi_vemc_1v8_en(void);
extern void upmu_set_rg_vemc_1v8_en(U32 val);
extern void upmu_set_rg_vemc_1v8_stbtd(U32 val);
extern U32 upmu_get_qi_vemc_1v8_mode(void);
extern void upmu_set_vemc_1v8_srclk_mode_sel(U32 val);
extern void upmu_set_vemc_1v8_ther_shdn_en(U32 val);
extern void upmu_set_vemc_1v8_lp_mode_set(U32 val);
extern void upmu_set_vemc_1v8_lp_sel(U32 val);
extern void upmu_set_rg_vemc_1v8_cal(U32 val);
extern void upmu_set_rg_vemc_1v8_vosel(U32 val);
extern void upmu_set_rg_vemc_1v8_stb_sel(U32 val);
extern void upmu_set_rg_vemc_1v8_ocfb(U32 val);
extern void upmu_set_rg_vemc_1v8_ndis_en(U32 val);
extern void upmu_set_rg_vibr_en(U32 val);
extern void upmu_set_rg_vibr_stbtd(U32 val);
extern U32 upmu_get_qi_vibr_mode(void);
extern void upmu_set_vibr_srclk_mode_sel(U32 val);
extern void upmu_set_vibr_ther_shen_en(U32 val);
extern void upmu_set_vibr_lp_mode_set(U32 val);
extern void upmu_set_vibr_lp_sel(U32 val);
extern void upmu_set_rg_vibr_cal(U32 val);
extern void upmu_set_rg_vibr_vosel(U32 val);
extern void upmu_set_rg_vibr_stb_sel(U32 val);
extern void upmu_set_rg_vibr_ocfb(U32 val);
extern void upmu_set_rg_vibr_ndis_en(U32 val);
extern void upmu_set_rg_ldo_ft(U32 val);
extern void upmu_set_digldo_rsv0(U32 val);
extern void upmu_set_digldo_rsv1(U32 val);
extern void upmu_set_vgp1_srclk_en_sel(U32 val);
extern void upmu_set_vgp2_srclk_en_sel(U32 val);
extern void upmu_set_vgp3_srclk_en_sel(U32 val);
extern void upmu_set_vgp4_srclk_en_sel(U32 val);
extern void upmu_set_vgp6_srclk_en_sel(U32 val);
extern void upmu_set_vsim1_srclk_en_sel(U32 val);
extern void upmu_set_vsim2_srclk_en_sel(U32 val);
extern void upmu_set_vgp5_srclk_en_sel(U32 val);
extern void upmu_set_vgp1_on_ctrl(U32 val);
extern void upmu_set_vgp2_on_ctrl(U32 val);
extern void upmu_set_vgp3_on_ctrl(U32 val);
extern void upmu_set_vgp4_on_ctrl(U32 val);
extern void upmu_set_vgp5_on_ctrl(U32 val);
extern void upmu_set_vgp6_on_ctrl(U32 val);
extern void upmu_set_vsim1_on_ctrl(U32 val);
extern void upmu_set_vsim2_on_ctrl(U32 val);
extern void upmu_set_vibr_on_ctrl(U32 val);
extern void upmu_set_vibr_srclk_en_sel(U32 val);
extern void upmu_set_rg_thrdet_sel(U32 val);
extern void upmu_set_thr_hwpdn_en(U32 val);
extern void upmu_set_rg_strup_thr_sel(U32 val);
extern void upmu_set_rg_thr_tmode(U32 val);
extern void upmu_set_thr_det_dis(U32 val);
extern void upmu_set_rg_vref_bg(U32 val);
extern void upmu_set_rg_strup_iref_trim(U32 val);
extern void upmu_set_rg_rst_drvsel(U32 val);
extern void upmu_set_rg_en_drvsel(U32 val);
extern void upmu_set_rg_usbdl_keydet_en(U32 val);
extern void upmu_set_rg_usbdl_en(U32 val);
extern void upmu_set_rg_pmu_lev_ungate(U32 val);
extern void upmu_set_rg_pmu_rsv(U32 val);
extern U32 upmu_get_pmu_thr_status(void);
extern U32 upmu_get_pmu_thr_deb(void);
extern void upmu_set_thr_test(U32 val);
extern void upmu_set_bias_gen_en_sel(U32 val);
extern void upmu_set_bias_gen_en(U32 val);
extern void upmu_set_strup_pwron_sel(U32 val);
extern void upmu_set_strup_pwron(U32 val);
extern void upmu_set_bias_gen_en_force(U32 val);
extern void upmu_set_strup_pwron_force(U32 val);
extern void upmu_set_strup_ft_ctrl(U32 val);
extern void upmu_set_pwrbb_deb_en(U32 val);
extern void upmu_set_dduvlo_deb_en(U32 val);
extern void upmu_set_vtcxo_2_pg_enb(U32 val);
extern void upmu_set_vio28_pg_enb(U32 val);
extern void upmu_set_va28_pg_enb(U32 val);
extern void upmu_set_va_pg_enb(U32 val);
extern void upmu_set_vtcxo_pg_enb(U32 val);
extern void upmu_set_vio18_pg_enb(U32 val);
extern void upmu_set_vsram_pg_enb(U32 val);
extern void upmu_set_vm_pg_enb(U32 val);
extern void upmu_set_vcore_pg_enb(U32 val);
extern void upmu_set_vproc_pg_enb(U32 val);
extern U32 upmu_get_qi_osc_en(void);
extern U32 upmu_get_just_pwrkey_rst(void);
extern void upmu_set_uvlo_l2h_deb_en(U32 val);
extern void upmu_set_clr_just_rst(U32 val);
extern void upmu_set_strup_con8_rsv0(U32 val);
extern void upmu_set_strup_ext_pmic_sel(U32 val);
extern void upmu_set_strup_ext_pmic_en(U32 val);
extern void upmu_set_strup_auxadc_en_sel(U32 val);
extern void upmu_set_strup_pwroff_preoff_en(U32 val);
extern void upmu_set_strup_pwroff_seq_en(U32 val);
extern U32 upmu_get_rg_adc_rdy_c0(void);
extern U32 upmu_get_rg_adc_out_c0(void);
extern U32 upmu_get_rg_adc_rdy_c1(void);
extern U32 upmu_get_rg_adc_out_c1(void);
extern U32 upmu_get_rg_adc_rdy_c2(void);
extern U32 upmu_get_rg_adc_out_c2(void);
extern U32 upmu_get_rg_adc_rdy_c3(void);
extern U32 upmu_get_rg_adc_out_c3(void);
extern U32 upmu_get_rg_adc_rdy_c4(void);
extern U32 upmu_get_rg_adc_out_c4(void);
extern U32 upmu_get_rg_adc_rdy_c5(void);
extern U32 upmu_get_rg_adc_out_c5(void);
extern U32 upmu_get_rg_adc_rdy_c6(void);
extern U32 upmu_get_rg_adc_out_c6(void);
extern U32 upmu_get_rg_adc_rdy_c7(void);
extern U32 upmu_get_rg_adc_out_c7(void);
extern U32 upmu_get_rg_adc_rdy_wakeup_pchr(void);
extern U32 upmu_get_rg_adc_out_wakeup_pchr(void);
extern U32 upmu_get_rg_adc_rdy_wakeup_swchr(void);
extern U32 upmu_get_rg_adc_out_wakeup_swchr(void);
extern U32 upmu_get_rg_adc_rdy_lbat(void);
extern U32 upmu_get_rg_adc_out_lbat(void);
extern U32 upmu_get_rg_adc_out_c0_trim(void);
extern U32 upmu_get_rg_adc_out_c1_trim(void);
extern U32 upmu_get_rg_adc_out_c2_trim(void);
extern U32 upmu_get_rg_adc_out_c3_trim(void);
extern U32 upmu_get_rg_adc_out_c4_trim(void);
extern U32 upmu_get_rg_adc_out_c5_trim(void);
extern U32 upmu_get_rg_adc_out_c6_trim(void);
extern U32 upmu_get_rg_adc_out_c7_trim(void);
extern U32 upmu_get_rg_adc_out_wakeup_pchr_trim(void);
extern U32 upmu_get_rg_adc_out_wakeup_swchr_trim(void);
extern U32 upmu_get_rg_adc_out_lbat_trim(void);
extern U32 upmu_get_rg_adc_out_avg_deci(void);
extern void upmu_set_rg_spl_num(U32 val);
extern void upmu_set_rg_avg_num(U32 val);
extern void upmu_set_rg_buf_pwd_on(U32 val);
extern void upmu_set_rg_adc_pwd_on(U32 val);
extern void upmu_set_rg_buf_pwd_b(U32 val);
extern void upmu_set_rg_adc_pwd_b(U32 val);
extern void upmu_set_rg_auxadc_chsel(U32 val);
extern void upmu_set_rg_auxadc_auto_str_en(U32 val);
extern void upmu_set_rg_auxadc_auto_str(U32 val);
extern void upmu_set_rg_adc_trim_comp(U32 val);
extern void upmu_set_rg_auxadc_bist_enb(U32 val);
extern void upmu_set_rg_auxadc_start(U32 val);
extern void upmu_set_rg_lbat_debt_min(U32 val);
extern void upmu_set_rg_lbat_debt_max(U32 val);
extern void upmu_set_rg_lbat_det_prd_15_0(U32 val);
extern void upmu_set_rg_lbat_det_prd_19_16(U32 val);
extern U32 upmu_get_rg_lbat_max_irq_b(void);
extern void upmu_set_rg_lbat_en_max(U32 val);
extern void upmu_set_rg_lbat_irq_en_max(U32 val);
extern void upmu_set_rg_lbat_volt_max(U32 val);
extern U32 upmu_get_rg_lbat_min_irq_b(void);
extern void upmu_set_rg_lbat_en_min(U32 val);
extern void upmu_set_rg_lbat_irq_en_min(U32 val);
extern void upmu_set_rg_lbat_volt_min(U32 val);
extern U32 upmu_get_rg_lbat_debounce_count_max(void);
extern U32 upmu_get_rg_lbat_debounce_count_min(void);
extern U32 upmu_get_rg_ni_comp(void);
extern void upmu_set_rg_da_dac(U32 val);
extern void upmu_set_rg_auxadc_cali(U32 val);
extern void upmu_set_rg_buf_cali(U32 val);
extern void upmu_set_rg_auxadc_rsv(U32 val);
extern void upmu_set_rg_da_dac_sel(U32 val);
extern void upmu_set_rg_aux_out_sel(U32 val);
extern void upmu_set_rg_arb_prio_2(U32 val);
extern void upmu_set_rg_arb_prio_1(U32 val);
extern void upmu_set_rg_arb_prio_0(U32 val);
extern void upmu_set_efuse_offset_ch0_trim(U32 val);
extern void upmu_set_efuse_gain_ch0_trim(U32 val);
extern void upmu_set_rg_vbuf_en(U32 val);
extern void upmu_set_rg_vbuf_byp(U32 val);
extern void upmu_set_rg_vbuf_calen(U32 val);
extern void upmu_set_rg_thermal_adc_oe(U32 val);
extern void upmu_set_rg_thermal_adc_ge(U32 val);
extern void upmu_set_rg_adc_trim_ch_sel(U32 val);
extern void upmu_set_rg_source_ch0_norm_sel(U32 val);
extern void upmu_set_rg_source_ch0_lbat_sel(U32 val);
extern void upmu_set_flash_rsv0(U32 val);
extern void upmu_set_flash_dim_duty(U32 val);
extern void upmu_set_flash_ther_shdn_en(U32 val);
extern void upmu_set_flash_en(U32 val);
extern void upmu_set_flash_dim_div(U32 val);
extern void upmu_set_flash_rsv1(U32 val);
extern void upmu_set_flash_sel(U32 val);
extern void upmu_set_flash_sfstren(U32 val);
extern void upmu_set_flash_sfstr(U32 val);
extern void upmu_set_flash_mode(U32 val);
extern void upmu_set_kpled_rsv0(U32 val);
extern void upmu_set_kpled_dim_duty(U32 val);
extern void upmu_set_kpled_ther_shdn_en(U32 val);
extern void upmu_set_kpled_en(U32 val);
extern void upmu_set_kpled_dim_div(U32 val);
extern void upmu_set_kpled_rsv1(U32 val);
extern void upmu_set_kpled_sel(U32 val);
extern void upmu_set_kpled_sfstren(U32 val);
extern void upmu_set_kpled_sfstr(U32 val);
extern void upmu_set_kpled_mode(U32 val);
extern void upmu_set_isink_rsv0(U32 val);
extern void upmu_set_isink_dim0_duty(U32 val);
extern void upmu_set_isink_dim0_fsel(U32 val);
extern void upmu_set_isink_rsv1(U32 val);
extern void upmu_set_isink_dim1_duty(U32 val);
extern void upmu_set_isink_dim1_fsel(U32 val);
extern void upmu_set_isink_rsv2(U32 val);
extern void upmu_set_isink_dim2_duty(U32 val);
extern void upmu_set_isink_dim2_fsel(U32 val);
extern void upmu_set_isink_rsv3(U32 val);
extern void upmu_set_isinks_ch2_en(U32 val);
extern void upmu_set_isinks_ch1_en(U32 val);
extern void upmu_set_isinks_ch0_en(U32 val);
extern void upmu_set_isink_rsv4(U32 val);
extern void upmu_set_isinks2_chop_en(U32 val);
extern void upmu_set_isinks1_chop_en(U32 val);
extern void upmu_set_isinks0_chop_en(U32 val);
extern void upmu_set_isinks_ch0_step(U32 val);
extern void upmu_set_isink0_chop_mode(U32 val);
extern void upmu_set_isink0_test_reg(U32 val);
extern void upmu_set_isinks_ch0_mode(U32 val);
extern void upmu_set_isinks_ch1_step(U32 val);
extern void upmu_set_isink1_chop_mode(U32 val);
extern void upmu_set_isink1_test_reg(U32 val);
extern void upmu_set_isinks_ch1_mode(U32 val);
extern void upmu_set_isinks_ch2_step(U32 val);
extern void upmu_set_isink2_chop_mode(U32 val);
extern void upmu_set_isink2_test_reg(U32 val);
extern void upmu_set_isinks_ch2_mode(U32 val);
extern void upmu_set_rg_trim_en(U32 val);
extern void upmu_set_rg_trim_sel(U32 val);
extern void upmu_set_rg_ldo_bist(U32 val);
extern void upmu_set_rg_isinks_rsv(U32 val);
extern void upmu_set_isinks_breath0_trf_sel(U32 val);
extern void upmu_set_isinks_breath0_ton_sel(U32 val);
extern void upmu_set_isinks_breath0_toff_sel(U32 val);
extern void upmu_set_isinks_breath1_trf_sel(U32 val);
extern void upmu_set_isinks_breath1_ton_sel(U32 val);
extern void upmu_set_isinks_breath1_toff_sel(U32 val);
extern void upmu_set_isinks_breath2_trf_sel(U32 val);
extern void upmu_set_isinks_breath2_ton_sel(U32 val);
extern void upmu_set_isinks_breath2_toff_sel(U32 val);
extern void upmu_set_isink0_sfstr_en(U32 val);
extern void upmu_set_isink1_sfstr_en(U32 val);
extern void upmu_set_isink2_sfstr_en(U32 val);
extern void upmu_set_isink0_sfstr_tc(U32 val);
extern void upmu_set_isink1_sfstr_tc(U32 val);
extern void upmu_set_isink2_sfstr_tc(U32 val);
extern void upmu_set_rg_audaccdetrsv(U32 val);
extern void upmu_set_accdet_con0_rsv1(U32 val);
extern void upmu_set_rg_audaccdetvin1pulllow(U32 val);
extern void upmu_set_rg_audaccdettvdet(U32 val);
extern void upmu_set_rg_audaccdetanaswctrl(U32 val);
extern void upmu_set_audaccdetanaswctrl_sel(U32 val);
extern void upmu_set_accdet_con0_rsv0(U32 val);
extern void upmu_set_rg_audaccdetvthcal(U32 val);
extern void upmu_set_accdet_seq_init(U32 val);
extern void upmu_set_accdet_en(U32 val);
extern void upmu_set_accdet_mbias_pwm_idle(U32 val);
extern void upmu_set_accdet_vth_pwm_idle(U32 val);
extern void upmu_set_accdet_cmp_pwm_idle(U32 val);
extern void upmu_set_accdet_mbias_pwm_en(U32 val);
extern void upmu_set_accdet_vth_pwm_en(U32 val);
extern void upmu_set_accdet_cmp_pwm_en(U32 val);
extern void upmu_set_accdet_pwm_width(U32 val);
extern void upmu_set_accdet_pwm_thresh(U32 val);
extern void upmu_set_accdet_fall_delay(U32 val);
extern void upmu_set_accdet_rise_delay(U32 val);
extern void upmu_set_accdet_debounce0(U32 val);
extern void upmu_set_accdet_debounce1(U32 val);
extern void upmu_set_accdet_debounce2(U32 val);
extern void upmu_set_accdet_debounce3(U32 val);
extern void upmu_set_accdet_ival_sel(U32 val);
extern void upmu_set_accdet_ival_mem_in(U32 val);
extern void upmu_set_accdet_ival_sam_in(U32 val);
extern void upmu_set_accdet_ival_cur_in(U32 val);
extern void upmu_set_accdet_irq_clr(U32 val);
extern U32 upmu_get_accdet_irq(void);
extern void upmu_set_accdet_pwm_en_sw(U32 val);
extern void upmu_set_accdet_mbias_en_sw(U32 val);
extern void upmu_set_accdet_vth_en_sw(U32 val);
extern void upmu_set_accdet_cmp_en_sw(U32 val);
extern void upmu_set_accdet_in_sw(U32 val);
extern void upmu_set_accdet_pwm_sel(U32 val);
extern void upmu_set_accdet_test_mode5(U32 val);
extern void upmu_set_accdet_test_mode4(U32 val);
extern void upmu_set_accdet_test_mode3(U32 val);
extern void upmu_set_accdet_test_mode2(U32 val);
extern void upmu_set_accdet_test_mode1(U32 val);
extern void upmu_set_accdet_test_mode0(U32 val);
extern U32 upmu_get_accdet_cmp_clk(void);
extern U32 upmu_get_accdet_vth_clk(void);
extern U32 upmu_get_accdet_mbias_clk(void);
extern U32 upmu_get_accdet_state(void);
extern U32 upmu_get_accdet_mem_in(void);
extern U32 upmu_get_accdet_sam_in(void);
extern U32 upmu_get_accdet_cur_in(void);
extern U32 upmu_get_accdet_in(void);
extern U32 upmu_get_accdet_cur_deb(void);
extern void upmu_set_accdet_rsv_con0(U32 val);
extern void upmu_set_accdet_rsv_con1(U32 val);
extern void upmu_set_rg_spk_gainl(U32 val);
extern void upmu_set_spk_ther_shdn_l_en(U32 val);
extern void upmu_set_spk_oc_shdn_dl(U32 val);
extern void upmu_set_spk_trim_en_l(U32 val);
extern void upmu_set_spkmode_l(U32 val);
extern void upmu_set_spk_en_l(U32 val);
extern U32 upmu_get_spk_trim_done_l(void);
extern void upmu_set_spk_offset_l_mode(U32 val);
extern void upmu_set_spk_lead_l_sw(U32 val);
extern void upmu_set_spk_offset_l_sw(U32 val);
extern U32 upmu_get_spk_offset_l_ov(void);
extern U32 upmu_get_spk_lead_l_flag(void);
extern U32 upmu_get_spk_lead_l_flag_deg(void);
extern U32 upmu_get_spk_offset_l(void);
extern void upmu_set_rg_spk_oc_en_l(U32 val);
extern void upmu_set_rg_spkab_oc_en_l(U32 val);
extern void upmu_set_rg_spk_test_en_l(U32 val);
extern void upmu_set_rg_spk_drc_en_l(U32 val);
extern void upmu_set_rg_spkrcv_en_l(U32 val);
extern void upmu_set_rg_spkab_obias_l(U32 val);
extern void upmu_set_rg_spk_slew_l(U32 val);
extern void upmu_set_rg_spk_force_en_l(U32 val);
extern void upmu_set_rg_spk_intg_rst_l(U32 val);
extern void upmu_set_rg_spk_gainr(U32 val);
extern void upmu_set_spk_ther_shdn_r_en(U32 val);
extern void upmu_set_spk_oc_shdn_dr(U32 val);
extern void upmu_set_spk_trim_en_r(U32 val);
extern void upmu_set_spkmode_r(U32 val);
extern void upmu_set_spk_en_r(U32 val);
extern U32 upmu_get_spk_trim_done_r(void);
extern void upmu_set_spk_offset_r_mode(U32 val);
extern void upmu_set_spk_lead_r_sw(U32 val);
extern void upmu_set_spk_offset_r_sw(U32 val);
extern U32 upmu_get_spk_offset_r_ov(void);
extern U32 upmu_get_spk_lead_r_flag(void);
extern U32 upmu_get_spk_lead_r_flag_deg(void);
extern U32 upmu_get_spk_offset_r(void);
extern void upmu_set_rg_spk_oc_en_r(U32 val);
extern void upmu_set_rg_spkab_oc_en_r(U32 val);
extern void upmu_set_rg_spk_test_en_r(U32 val);
extern void upmu_set_rg_spk_drc_en_r(U32 val);
extern void upmu_set_rg_spkrcv_en_r(U32 val);
extern void upmu_set_rg_spkab_obias_r(U32 val);
extern void upmu_set_rg_spk_slew_r(U32 val);
extern void upmu_set_rg_spk_force_en_r(U32 val);
extern void upmu_set_rg_spk_intg_rst_r(U32 val);
extern U32 upmu_get_spk_ab_oc_l_deg(void);
extern U32 upmu_get_spk_d_oc_l_deg(void);
extern U32 upmu_get_spk_ab_oc_r_deg(void);
extern U32 upmu_get_spk_d_oc_r_deg(void);
extern void upmu_set_spk_oc_thd(U32 val);
extern void upmu_set_spk_oc_wnd(U32 val);
extern void upmu_set_spk_trim_thd(U32 val);
extern void upmu_set_spk_trim_wnd(U32 val);
extern void upmu_set_spk_trim_div(U32 val);
extern void upmu_set_spk_td3(U32 val);
extern void upmu_set_spk_td2(U32 val);
extern void upmu_set_spk_td1(U32 val);
extern void upmu_set_rg_spk_octh_d(U32 val);
extern void upmu_set_rg_spkab_ovdrv(U32 val);
extern void upmu_set_rg_spk_fbrc_en(U32 val);
extern void upmu_set_rg_spk_vcm_ibsel(U32 val);
extern void upmu_set_rg_spk_vcm_sel(U32 val);
extern void upmu_set_rg_spk_en_view_clk(U32 val);
extern void upmu_set_rg_spk_en_view_vcm(U32 val);
extern void upmu_set_rg_spk_ccode(U32 val);
extern void upmu_set_rg_spk_ibias_sel(U32 val);
extern void upmu_set_rg_btl_set(U32 val);
extern void upmu_set_spk_test_mode1(U32 val);
extern void upmu_set_spk_test_mode0(U32 val);
extern void upmu_set_spk_vcm_fast_en(U32 val);
extern void upmu_set_spk_rsv0(U32 val);
extern void upmu_set_rg_spkpga_gain(U32 val);
extern void upmu_set_rg_spk_rsv(U32 val);
extern void upmu_set_spk_td_done(U32 val);
extern void upmu_set_spk_td_wait(U32 val);
extern void upmu_set_spk_trim_stop_l_sw(U32 val);
extern void upmu_set_spk_trim_stop_r_sw(U32 val);
extern void upmu_set_spk_trim_en_l_sw(U32 val);
extern void upmu_set_spk_trim_en_r_sw(U32 val);
extern void upmu_set_spk_outstg_en_l_sw(U32 val);
extern void upmu_set_spk_outstg_en_r_sw(U32 val);
extern void upmu_set_spk_en_l_sw(U32 val);
extern void upmu_set_spk_en_r_sw(U32 val);
extern void upmu_set_spk_depop_en_l_sw(U32 val);
extern void upmu_set_spk_depop_en_r_sw(U32 val);
extern void upmu_set_spkmode_l_sw(U32 val);
extern void upmu_set_spkmode_r_sw(U32 val);
extern void upmu_set_spk_rst_l_sw(U32 val);
extern void upmu_set_spk_rst_r_sw(U32 val);
extern void upmu_set_spk_vcm_fast_sw(U32 val);
extern void upmu_set_spk_en_mode(U32 val);
extern void upmu_set_fg_sw_rstclr(U32 val);
extern void upmu_set_fg_charge_rst(U32 val);
extern void upmu_set_fg_time_rst(U32 val);
extern void upmu_set_fg_offset_rst(U32 val);
extern void upmu_set_fg_sw_clear(U32 val);
extern U32 upmu_get_fg_latchdata_st(void);
extern void upmu_set_fg_sw_read_pre(U32 val);
extern void upmu_set_fg_sw_cr(U32 val);
extern void upmu_set_rg_fgclksrc(U32 val);
extern void upmu_set_fg_autocalrate(U32 val);
extern void upmu_set_fg_cal(U32 val);
extern void upmu_set_fg_vmode(U32 val);
extern void upmu_set_fg_on(U32 val);
extern U32 upmu_get_fg_car_35_32(void);
extern U32 upmu_get_fg_car_31_16(void);
extern U32 upmu_get_fg_car_15_00(void);
extern U32 upmu_get_fg_nter_29_16(void);
extern U32 upmu_get_fg_nter_15_00(void);
extern void upmu_set_fg_bltr(U32 val);
extern void upmu_set_fg_bftr(U32 val);
extern U32 upmu_get_fg_current_out(void);
extern void upmu_set_fg_adjust_offset_value(U32 val);
extern U32 upmu_get_fg_offset(void);
extern void upmu_set_rg_inputclksel(U32 val);
extern void upmu_set_rg_fganalogtest(U32 val);
extern void upmu_set_rg_spare(U32 val);
extern void upmu_set_fg_adc_autorst(U32 val);
extern void upmu_set_fg_adj_offset_en(U32 val);
extern void upmu_set_vol_osr_h(U32 val);
extern void upmu_set_vol_osr(U32 val);
extern void upmu_set_fg_osr_h(U32 val);
extern void upmu_set_fg_osr(U32 val);
extern U32 upmu_get_rg_fgvmode(void);
extern U32 upmu_get_fg_rst(void);
extern U32 upmu_get_fgcal_en(void);
extern U32 upmu_get_fgadc_en(void);
extern void upmu_set_fg_slp_en(U32 val);
extern U32 upmu_get_fg_adc_rstdetect(void);
extern U32 upmu_get_fg_h_int_sts(void);
extern U32 upmu_get_fg_l_int_sts(void);
extern void upmu_set_vol_fir1bypass(U32 val);
extern void upmu_set_fg_fir2bypass(U32 val);
extern void upmu_set_fg_fir1bypass(U32 val);
extern U32 upmu_get_vol_current_out(void);
extern U32 upmu_get_fg_cic2(void);
extern void upmu_set_fg_slp_cur_th(U32 val);
extern void upmu_set_fg_slp_time(U32 val);
extern void upmu_set_fg_det_time(U32 val);
extern void upmu_set_fg_srcvolten_ftime(U32 val);
extern void upmu_set_fg_test_mode1(U32 val);
extern void upmu_set_fg_test_mode0(U32 val);
extern void upmu_set_fg_rsv1(U32 val);
extern void upmu_set_fg_vmode_sw(U32 val);
extern void upmu_set_fg_fgadc_en_sw(U32 val);
extern void upmu_set_fg_fgcal_en_sw(U32 val);
extern void upmu_set_fg_rst_sw(U32 val);
extern void upmu_set_fg_mode(U32 val);
extern void upmu_set_stmp_mode(U32 val);
extern void upmu_set_mix_xosc32_stp_cali(U32 val);
extern void upmu_set_mix_xosc32_stp_lpdrst(U32 val);
extern void upmu_set_mix_xosc32_stp_lpden(U32 val);
extern U32 upmu_get_mix_xosc32_stp_lpdtb(void);
extern void upmu_set_mix_xosc32_stp_pwdb(U32 val);
extern U32 upmu_get_mix_xosc32_stp_cpdtb(void);
extern void upmu_set_mix_eosc32_opt(U32 val);
extern void upmu_set_mix_efuse_xosc32_enb_opt(U32 val);
extern U32 upmu_get_mix_rtc_xosc32_enb(void);
extern U32 upmu_get_mix_stp_rtc_ddlo(void);
extern void upmu_set_mix_stp_bbwakeup(U32 val);
extern void upmu_set_mix_eosc32_vct_en(U32 val);
extern void upmu_set_mix_eosc32_stp_rsv(U32 val);
extern void upmu_set_mix_dcxo_stp_test_deglitch_mode(U32 val);
extern void upmu_set_mix_rtc_stp_xosc32_enb(U32 val);
extern void upmu_set_mix_pmu_stp_ddlo_vrtc_en(U32 val);
extern void upmu_set_mix_pmu_stp_ddlo_vrtc(U32 val);
extern void upmu_set_mix_dcxo_stp_lvsh_en(U32 val);
extern void upmu_set_mix_eosc32_stp_chop_en(U32 val);
extern void upmu_set_rg_dc2ac_en_vaudp12(U32 val);
extern void upmu_set_rg_aud_dac_pwl_up_va28(U32 val);
extern void upmu_set_rg_aud_dac_pwr_up_va28(U32 val);
extern void upmu_set_rg_auddacrpwrup_vaudp12(U32 val);
extern void upmu_set_rg_auddaclpwrup_vaudp12(U32 val);
extern void upmu_set_rg_audhprscdisable_vaudp12(U32 val);
extern void upmu_set_rg_audhplscdisable_vaudp12(U32 val);
extern void upmu_set_rg_audhsscdisable_vaudp12(U32 val);
extern void upmu_set_rg_audhprmuxinputsel_vaudp12(U32 val);
extern void upmu_set_rg_audhplmuxinputsel_vaudp12(U32 val);
extern void upmu_set_rg_audhsmuxinputsel_vaudp12(U32 val);
extern void upmu_set_rg_audhprpwrup_vaudp12(U32 val);
extern void upmu_set_rg_audhplpwrup_vaudp12(U32 val);
extern void upmu_set_rg_audhspwrup_vaudp12(U32 val);
extern void upmu_set_rg_linenoiseenh_vaudp12(U32 val);
extern void upmu_set_rg_hpout_shortvcm_vaudp12(U32 val);
extern void upmu_set_rg_hpoutputreset0_vaudp12(U32 val);
extern void upmu_set_rg_hpinputreset0_vaudp12(U32 val);
extern void upmu_set_rg_hpoutputstbenh_vaudp12(U32 val);
extern void upmu_set_rg_hpinputstbenh_vaudp12(U32 val);
extern void upmu_set_rg_prechargebuf_en_vaudp12(U32 val);
extern void upmu_set_rg_audbgbon_vaudp12(U32 val);
extern void upmu_set_rg_audhsstartup_vaudp12(U32 val);
extern void upmu_set_rg_audhpstartup_vaudp12(U32 val);
extern void upmu_set_rg_audhsbsccurrent_vaudp12(U32 val);
extern void upmu_set_rg_audhprbsccurrent_vaudp12(U32 val);
extern void upmu_set_rg_audhplbsccurrent_vaudp12(U32 val);
extern void upmu_set_rg_hsout_shortvcm_vaudp12(U32 val);
extern void upmu_set_rg_hpoutstb_rsel_vaudp12(U32 val);
extern void upmu_set_rg_hsoutputreset0_vaudp12(U32 val);
extern void upmu_set_rg_hsinputreset0_vaudp12(U32 val);
extern void upmu_set_rg_hsoutputstbenh_vaudp12(U32 val);
extern void upmu_set_rg_hsinputstbenh_vaudp12(U32 val);
extern void upmu_set_rg_line_pull0v_vaudp12(U32 val);
extern void upmu_set_rg_audhprfinetrim_vaudp12(U32 val);
extern void upmu_set_rg_audhplfinetrim_vaudp12(U32 val);
extern void upmu_set_rg_audhptrim_en_vaudp12(U32 val);
extern void upmu_set_rg_audhprtrim_vaudp12(U32 val);
extern void upmu_set_rg_audhpltrim_vaudp12(U32 val);
extern void upmu_set_rg_abidec_reserved_vaudp12(U32 val);
extern void upmu_set_rg_abidec_reserved_va28(U32 val);
extern void upmu_set_rg_audibiaspwrdn_vaudp12(U32 val);
extern void upmu_set_rg_audbiasadj_1_vaudp12(U32 val);
extern void upmu_set_rg_audbiasadj_0_vaudp12(U32 val);
extern void upmu_set_rg_chargeoption_depop_va28(U32 val);
extern void upmu_set_rg_depop_isel_va28(U32 val);
extern void upmu_set_rg_depop_vcmgen_en_va28(U32 val);
extern void upmu_set_rg_depop_rsel_va28(U32 val);
extern void upmu_set_rg_depop_ren_va28(U32 val);
extern void upmu_set_rg_audivlmuxsel_vaudp12(U32 val);
extern void upmu_set_rg_audivlstartup_vaudp12(U32 val);
extern void upmu_set_rg_audivlpwrup_vaudp12(U32 val);
extern void upmu_set_rg_audivlmute_vaudp12(U32 val);
extern void upmu_set_rg_sel_delay_vcore(U32 val);
extern void upmu_set_rg_sel_encoder_96k_va28(U32 val);
extern void upmu_set_rg_sel_decoder_96k_va28(U32 val);
extern void upmu_set_rg_rstb_encoder_va28(U32 val);
extern void upmu_set_rg_rstb_decoder_va28(U32 val);
extern void upmu_set_rg_va28refgen_en_va28(U32 val);
extern void upmu_set_rg_va33refgen_en_va33(U32 val);
extern void upmu_set_rg_vbatrefgen_en_vbat(U32 val);
extern void upmu_set_rg_vbatprereg_pddis_en_vbat(U32 val);
extern void upmu_set_rg_lcldo_enc_remote_sense_va28(U32 val);
extern void upmu_set_rg_lcldo_enc_pddis_en_va28(U32 val);
extern void upmu_set_rg_lcldo_vosel_va33(U32 val);
extern void upmu_set_rg_lcldo_remote_sense_va33(U32 val);
extern void upmu_set_rg_lcldo_pddis_en_va33(U32 val);
extern void upmu_set_rg_hcldo_vosel_va33(U32 val);
extern void upmu_set_rg_hcldo_remote_sense_va33(U32 val);
extern void upmu_set_rg_hcldo_pddis_en_va33(U32 val);
extern void upmu_set_rg_audpmu_reserved_vaudp12(U32 val);
extern void upmu_set_rg_audpmu_reserved_va28(U32 val);
extern void upmu_set_rg_audpmu_reserved_va33(U32 val);
extern void upmu_set_rg_audpmu_reserved_vbat(U32 val);
extern void upmu_set_da_nvreg_en_vaudp12(U32 val);
extern void upmu_set_rg_acc_dcc_sel_audglb_va28(U32 val);
extern void upmu_set_rg_audglb_pwrdn_va28(U32 val);
extern void upmu_set_rg_nvreg_pull0v_vaudp12(U32 val);
extern void upmu_set_rg_ncp_remote_sense_va18(U32 val);
extern void upmu_set_da_hcldo_en_va33(U32 val);
extern void upmu_set_da_lcldo_en_va33(U32 val);
extern void upmu_set_da_lcldo_enc_en_va28(U32 val);
extern void upmu_set_da_vbatprereg_en_vbat(U32 val);
extern void upmu_set_rg_audpreampiddtest(U32 val);
extern void upmu_set_rg_audpreamprpgatest(U32 val);
extern void upmu_set_rg_audpreamplpgatest(U32 val);
extern void upmu_set_rg_audpreamprinputsel(U32 val);
extern void upmu_set_rg_audpreamplinputsel(U32 val);
extern void upmu_set_rg_audpreampron(U32 val);
extern void upmu_set_rg_audpreamplon(U32 val);
extern void upmu_set_rg_audadc3rdstagereset(U32 val);
extern void upmu_set_rg_audadc2ndstagereset(U32 val);
extern void upmu_set_rg_audadc2ndstageiddtest(U32 val);
extern void upmu_set_rg_audadc1ststageiddtest(U32 val);
extern void upmu_set_rg_audadcclksel(U32 val);
extern void upmu_set_rg_audadcrinputsel(U32 val);
extern void upmu_set_rg_audadclinputsel(U32 val);
extern void upmu_set_rg_audadcrpwrup(U32 val);
extern void upmu_set_rg_audadclpwrup(U32 val);
extern void upmu_set_rg_audrctunelsel(U32 val);
extern void upmu_set_rg_audrctunel(U32 val);
extern void upmu_set_rg_audadcffbypass(U32 val);
extern void upmu_set_rg_audadcbypass(U32 val);
extern void upmu_set_rg_audadcflashiddtest(U32 val);
extern void upmu_set_rg_audadcrefbufiddtest(U32 val);
extern void upmu_set_rg_audadcdaciddtest(U32 val);
extern void upmu_set_rg_audadcdacfbcurrent(U32 val);
extern void upmu_set_rg_audadcnodem(U32 val);
extern void upmu_set_rg_audrctunersel(U32 val);
extern void upmu_set_rg_audrctuner(U32 val);
extern void upmu_set_rg_audadctestdata(U32 val);
extern void upmu_set_rg_audadcdacnrz(U32 val);
extern void upmu_set_rg_audadcfsreset(U32 val);
extern void upmu_set_rg_audadcdactest(U32 val);
extern void upmu_set_rg_audadcnopatest(U32 val);
extern void upmu_set_rg_audadcwidecm(U32 val);
extern void upmu_set_rg_audspareva18(U32 val);
extern void upmu_set_rg_audspareva28(U32 val);
extern void upmu_set_rg_audsparevaudp(U32 val);
extern void upmu_set_rg_audsparevmic(U32 val);
extern void upmu_set_rg_audmicbiasvref(U32 val);
extern void upmu_set_rg_audpwdbmicbias(U32 val);
extern void upmu_set_rg_auddigmicbias(U32 val);
extern void upmu_set_rg_auddigmicnduty(U32 val);
extern void upmu_set_rg_auddigmicpduty(U32 val);
extern void upmu_set_rg_auddigmicen(U32 val);
extern void upmu_set_rg_audlsbufrmute(U32 val);
extern void upmu_set_rg_audlsbufrgain(U32 val);
extern void upmu_set_rg_audlsbuflmute(U32 val);
extern void upmu_set_rg_audlsbuflgain(U32 val);
extern void upmu_set_rg_audlsbufrpwrup(U32 val);
extern void upmu_set_rg_audlsbuflpwrup(U32 val);
extern void upmu_set_rg_audlsbuf2iddtest(U32 val);
extern void upmu_set_rg_audlsbufiddtest(U32 val);
extern void upmu_set_rg_audlsbufrinputsel(U32 val);
extern void upmu_set_rg_audlsbuflinputsel(U32 val);
extern void upmu_set_rg_audencspareva18(U32 val);
extern void upmu_set_rg_audencspareva28(U32 val);
extern void upmu_set_rg_clksq_monen_va28(U32 val);
extern void upmu_set_rg_audenc_reserved(U32 val);
extern void upmu_set_rg_audpreampr_reserved(U32 val);
extern void upmu_set_rg_audpreamprgain(U32 val);
extern void upmu_set_rg_audpreampl_reserved(U32 val);
extern void upmu_set_rg_audpreamplgain(U32 val);
extern void upmu_set_rg_audzcdmuxsel_vaudp12(U32 val);
extern void upmu_set_rg_audzcdclksel_vaudp12(U32 val);
extern void upmu_set_rg_audzcdtimeoutmodesel(U32 val);
extern void upmu_set_rg_audzcdgainstepsize(U32 val);
extern void upmu_set_rg_audzcdgainsteptime(U32 val);
extern void upmu_set_rg_audzcdenable(U32 val);
extern void upmu_set_rg_audlinegain(U32 val);
extern void upmu_set_rg_audhprgain(U32 val);
extern void upmu_set_rg_audhplgain(U32 val);
extern void upmu_set_rg_audhsgain(U32 val);
extern void upmu_set_rg_audivrgain(U32 val);
extern void upmu_set_rg_audivlgain(U32 val);
extern U32 upmu_get_rg_audintgain2(void);
extern U32 upmu_get_rg_audintgain1(void);
extern void upmu_set_rg_divcks_chg(U32 val);
extern void upmu_set_rg_divcks_on(U32 val);
extern void upmu_set_rg_divcks_prg(U32 val);
extern void upmu_set_rg_pwd_ncp(U32 val);

extern kal_uint32 upmu_get_reg_value(kal_uint32 reg);

#endif // _MT6320_PMIC_COMMON_H_
