
/*****************************************************************************
 *
 * Filename:
 * ---------
 *   memory_info.h
 *
 * Project:
 * --------
 *   Android
 *
 * Description:
 * ------------
 *   This Module defines the memory information related setting.
 *
 * Author:
 * -------
 *  EMI auto generator V0.01
 *
 *   Memory Device database last modified on 2011/1/29
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * $Revision$
 * $Modtime$
 * $Log$
 *
 *------------------------------------------------------------------------------
 * WARNING!!!  WARNING!!!   WARNING!!!  WARNING!!!  WARNING!!!  WARNING!!! 
 * This file is generated by EMI Auto-gen Tool.
 * Please do not modify the content directly!
 * It could be overwritten!
 *============================================================================
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#ifndef __MT65XX_MEM_INFO_H__
#define __MT65XX_MEM_INFO_H__

struct DRAM_SETTINGS{
  unsigned short  NAND_ID;
  unsigned int BANKS_NR;
  unsigned int CFG_PHYS_SDRAM_0_SIZE;
  unsigned int CFG_PHYS_SDRAM_0_START;
  unsigned int CFG_PHYS_SDRAM_1_SIZE;
  unsigned int CFG_PHYS_SDRAM_1_START;
  unsigned int CFG_PHYS_SDRAM_2_SIZE;
  unsigned int CFG_PHYS_SDRAM_2_START;
  unsigned int CFG_PHYS_SDRAM_3_SIZE;
  unsigned int CFG_PHYS_SDRAM_3_START;
};

struct DRAM_SETTINGS dram_settings[]=
{

	{
		0xADBC,		//NAND_ID
		2,		//DRAM_BANKS_NR
		(SZ_256M - RIL_SIZE),		//CFG_PHYS_SDRAM_0_SIZE
		RIL_SIZE,		//CFG_PHYS_SDRAM_0_START
		(SZ_256M),		//CFG_PHYS_SDRAM_1_SIZE
		(0x10000000),		//CFG_PHYS_SDRAM_1_START
		0x0,		//CFG_PHYS_SDRAM_2_SIZE
		0x0,		//CFG_PHYS_SDRAM_2_START
		0x0,		//CFG_PHYS_SDRAM_3_SIZE
		0x0,		//CFG_PHYS_SDRAM_3_START
	},
	{
		0xECBC,		//NAND_ID
		1,		//DRAM_BANKS_NR
		(SZ_256M - RIL_SIZE),		//CFG_PHYS_SDRAM_0_SIZE
		RIL_SIZE,		//CFG_PHYS_SDRAM_0_START
		(0),		//CFG_PHYS_SDRAM_1_SIZE
		(0),		//CFG_PHYS_SDRAM_1_START
		0x0,		//CFG_PHYS_SDRAM_2_SIZE
		0x0,		//CFG_PHYS_SDRAM_2_START
		0x0,		//CFG_PHYS_SDRAM_3_SIZE
		0x0,		//CFG_PHYS_SDRAM_3_START
	}
};

#endif


