obj-y := mtprof.o bootprof.o sched_monitor.o monitor_debug_out.o
obj-$(CONFIG_MT_LOCK_DEBUG) += lockprof.o
obj-$(CONFIG_MT_ENG_BUILD) += mt_debug_config.o
mtprof-y += prof_ctl.o prof_main.o
obj-y += mt_prv_lock.o
