

#ifndef __CFG_CAMERA_FILE_MAX_SIZE_H__
#define __CFG_CAMERA_FILE_MAX_SIZE_H__

#define MAXIMUM_NVRAM_CAMERA_DEFECT_FILE_SIZE       4096 //BYTE 81920
#define MAXIMUM_NVRAM_CAMERA_SHADING_FILE_SIZE      81920 //BYTE 81920--> 16000 for meta tool limitation

#define MAXIMUM_NVRAM_CAMERA_PARA_FILE_SIZE         10240
#define MAXIMUM_NVRAM_CAMERA_3A_FILE_SIZE           4096
#define MAXIMUM_NVRAM_CAMERA_SENSOR_FILE_SIZE       4096
#define MAXIMUM_NVRAM_CAMERA_LENS_FILE_SIZE		    400 

#endif
