MTK_CPU = arm_cortexa7

MTK_SEC_SECRO_AC_SUPPORT = yes 


TARGET_ARCH_VARIANT = armv7-a-neon

MODEM_UMTS_TDD128_MODE = no

MTK_ENGINEERMODE_INTERNAL_APP = yes

MTK_FIRST_MD = 1
MTK_FOTA_ENTRY = no
MTK_FLIGHT_MODE_POWER_OFF_MD = yes

MTK_SCOMO_ENTRY = no

MTK_OGM_PLAYBACK_SUPPORT = no

MTK_MTKPS_PLAYBACK_SUPPORT = no
MTK_CHKIMGSIZE_SUPPORT = no
MTK_MMPROFILE_SUPPORT=yes

MTK_DP_FRAMEWORK = yes
MTK_ION_SUPPORT = yes

MTK_ENABLE_MD1 = no
MTK_ENABLE_MD2 = no

MTK_FD_SUPPORT=yes
MTK_FD_FORCE_REL_SUPPORT=yes

CUSTOM_KERNEL_SSW=ssw_generic

MTK_SWIP_VORBIS=yes

MULTI_CH_PLAYBACK_SUPPORT=no

MTK_MERGE_INTERFACE_SUPPORT=yes

MTK_PRODUCT_INFO_SUPPORT=yes

HAVE_MTKLOUDNESS_EFFECT=yes
MTK_VSS_SUPPORT = yes

NATIVE_AUDIO_PREPROCESS_ENABLE=yes


MTK_USES_VR_DYNAMIC_QUALITY_MECHANISM=yes
MTK_PQ_SUPPORT=yes    
MTK_FM_RX_AUDIO=FM_DIGITAL_INPUT

MTK_BWC_SUPPORT = yes

MTK_FLV_PLAYBACK_SUPPORT=yes


MTK_LCEEFT_SUPPORT = yes 

MTK_WFD_SUPPORT=yes






MTK_BAIDU_MAP_SUPPORT = no

MTK_BAIDU_SEARCH_BAR_SUPPORT = no

# Specify HDMI external IC type.
CUSTOM_KERNEL_HDMI=

# To control whether enable or disable HDMI feature. If choose yes,  phone's screen can be demonstrated on TV via HDMI cable.
MTK_HDMI_SUPPORT=no

MTK_SPM_MCDI_ENABLE = yes


MTK_VIDEO_THUMBNAIL_PLAY_SUPPORT = yes 


MTK_FENCE_SUPPORT = yes 


MTK_MD_SHUT_DOWN_NT = yes 

